### ISSUE TITLE
consider using RPATH instead of RUNPATH.

### ISSUE THREAD

**Issue by amosbird** [NixOS/nix#1002]
My team is developing a project which highly depends on LD_LIBRARY_PATH. It has its own libc configuration and more. However I still want to use some developing tools from nixpkgs such as maven. Why does nix change from RPATH to RUNPATH? I think not being affected by env vars is purer.

related issues:  #902, NixOS/nixpkgs#16767 NixOS/nixpkgs#16769

**Comment by wmertens** [comment]
I thought the builds use rpath?

**Comment by martinetd** [comment]
I've just been hit by this (nixos using runpath instead of rpath like everyone else) as well, for some project with plugins in libdir ( 
https://github.com/cea-hpc/robinhood/blob/92648d119585a38429c052538ae69bdc73bbb7cf/src/plugin.c#L44 ), which would just have worked had we been using rpath...
(we use runpath everywhere btw, at least in a meson build all currently building binaries only have runpath set)


There are two main differences between rpath and runpath:
 * loading order vs. `LD_LIBRARY_PATH` as described here. glibc at least loads rpath -> `LD_LIBRARY_PATH` -> runpath
 * path lookup recursion for parent objects: if runpath is NOT set on the object initiating a new mapping (e.g. dlopen from within a lib will be seen by glibc as coming from that lib), then rpaths will be looked up for that lib and for whatever loaded that lib and for whatever loaded THAT lib etc recursively until no parent as well as main mapping if it wasn't the parent.
If runpath is set on the object initiating the mapping then after LD_LIBRARY_PATH and that one binary's runpath check everything is over.


Well, ok, this doesn't seem so bad, I just have to add the proper runpath to the lib that does the `dlopen()` right?...
But here comes the trick, when using asan since asan has `__interceptor_dlopen` that will catch dlopen, glibc will think the dlopen comes from asan and only check for asan's runpath, ignoring whatever I have set... And basically I have no means of overwriting that short of patching the program to use absolute path somehow (which sucks for tests, I don't want to hardcode a check to decide if it's a build dir or not to use different plugins path)!!
At least stuff like asan with dlopen() interceptors really shouldn't be using runpath, that just breaks everything.


Sorry for the rant but I did look at various threads of rpath vs. runpath for nixos and all seem to only care about library loading order, but it's a much bigger change than that, and getting different behaviour between nixos and other distros when debugging why the heck plugin doesn't load wasn't fun so I hope this will at least serve as a documentation purpose... I don't think this can reasonably be changed now because going back to rpath would likely break valid usecases that required LD_LIBRARY_PATH having higher precedence (I wonder what though!)

**Comment by edolstra** [comment]
From the `ld.so` manpage: "Use of DT_RPATH is deprecated."

And the reason why we switched from RPATH from RUNPATH is indeed that RPATH does not respect LD_LIBRARY_PATH overrides (so you can't override `libGL.so` to use the system's OpenGL implementation).
