### ISSUE TITLE
'cache.nixos.org' hardcoded in 'download-from-binary-cache.pl'

### ISSUE THREAD

**Issue by skvl** [NixOS/nix#1004]
If *.nix-defexpr/channels/binary-caches/nixpkgs* is not available and there is no *nix.conf* than hardcoded address *cache.nixos.org* is used.

**Comment by edolstra** [comment]
What is the issue?

**Comment by domenkozar** [comment]
@skvl please provide a sscce.org

**Comment by skvl** [comment]
* Setup *Nix* on some *Linux* machine (not *NixOS*)

    It would be set in *single-user* mode. Thus there would be no */etc/nix/nix.conf*
* Corrupt *.nix-defexpr/channels/binary-caches/nixpkgs* (for example write *___cache.nixos.org*)
* Run `nix-env -i ...`
* It would try *___cache.nixos.org* first then it would download *cache.nixos.org*
* Add empty *nix.conf* (or empty *binary_caches=...*)
* Run `nix-env -i ...` again

**Comment by copumpkin** [comment]
@skvl thanks for more detail, but in general, you'll get better responses on things like this if you provide an explicit explanation of what you think the _bad outcome_ is. You literally just stated what happens and assume that we understand why you consider that to be a bad thing, and when @edolstra asked what was wrong with the behavior, you simply explained how to replicate it rather than what you see the problem being.

@edolstra one bad outcome I could see from this could be for an organization that set up a private binary cache because it doesn't trust your Hydra build infrastructure (perhaps they're paranoid that your servers might be compromised, or whatever). That organization would prefer an error message rather than implicitly falling back on an untrusted binary cache. Am I misunderstanding something, or would that happen?

**Comment by skvl** [comment]
@copumpkin thanks very much for advice.

I have just thought that *hardcode* is something bad so I decided to notify about that. Not rare I use *hardcoded* values in my project before configs. But it is possible just to forget such values after config.

@edolstra feel free to close issue if this in not a real issue.

**Comment by copumpkin** [comment]
@skvl the point I raised seems like a potential concern, right? @edolstra or would something else prevent the tool from reaching out to the binary cache I don't want?
