### ISSUE TITLE
nix repl --help shows some raw html

### ISSUE THREAD

**Issue by lolbinarycat** [NixOS/nix#10265]
**Describe the bug**

there are `<span>` elements in the Options section.

**Steps To Reproduce**

1. run `nix repl --help`
2. scroll to the "Options" section
3. each option will look like `<span id="opt-stdin">--stdin</span>`

**Expected behavior**

there should not be raw html

**`nix-env --version` output**
nix-env (Nix) 2.18.1

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by thufschmitt** [comment]
This has been fixed by https://github.com/NixOS/nix/commit/22513c91dcd7cb74c5fc1e4da9273947739931b6 (and backported as https://github.com/NixOS/nix/commit/184a20ec04eb79272999babe5a4105b6755b9b3d).

[2.18.2](https://github.com/NixOS/nix/releases/tag/2.18.2) was released a few weeks ago, and should have the fix.
