### ISSUE TITLE
warn when failing to disable sandbox instead of silently ignoring the option

### ISSUE THREAD

**Issue by lolbinarycat** [NixOS/nix#10272]
**Describe the bug**

accoring to [this forum post](https://discourse.nixos.org/t/cant-run-non-sandboxed-builds-on-nixos-18-09/1110) you need to be a trusted user to run `nix-build` with sandbox disabled.  however, when failing to disable the sandbox, instead of a warning being printed, it just silently fails with no warning

**Steps To Reproduce**
run the following as a user that is not in `trusted-users`:
`nix-build --no-sandbox -E 'derivation { name = "no-chroot-test"; builder = "/bin/sh"; args = [ "-c" "echo ok > $out" ]; system = builtins.currentSystem; __noChroot = true; }'`

if run as a trusted user (eg. root), the command runs successfully.

**Expected behavior**

error or warning about being unable to disable the sandbox

**`nix-env --version` output**

nix-env (Nix) 2.18.1

**Additional context**

none of the documentation i read mentioned this as a limitation

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by lolbinarycat** [comment]
ideally this warning should also appear with `--option sandbox false` and `--arg { sandbox = false; }`

this could be implemented fairly easily in nixpkgs, but that has the obvious disadvantage of only working when nixpkgs is being evaluated.

**Comment by thufschmitt** [comment]
Hum, this was fixed long ago by https://github.com/NixOS/nix/pull/2931, but then reverted by https://github.com/NixOS/nix/commit/a59e77d9e54e8e7bf0f3c3f40c22cd34b7a81225 because it was badly interfering with `experimental-features`. But the revert was too brutal (except for experimental features, it rarely makes sense to ignore this warning), and is anyway useless now since the experimental features are ignored by the daemon altogether (https://github.com/NixOS/nix/pull/5071).

Do you want to open a PR to revert https://github.com/NixOS/nix/commit/a59e77d9e54e8e7bf0f3c3f40c22cd34b7a81225 ?

**Comment by lolbinarycat** [comment]
reverting that seems like a good idea, what do i need to do for that?

**Comment by thufschmitt** [comment]
https://github.com/NixOS/nix/pull/10274
