### ISSUE TITLE
Weird behaviour with NUL code points in strings

### ISSUE THREAD

**Issue by lheckemann** [NixOS/nix#10317]
**Describe the bug**
`builtins.fromJSON` allows crafting strings that contain the null code point by representing it as `\u0000`.
However, these are considered as terminating strings in a number of places, such as in the printing code or equality tests:
```
nix-repl> builtins.fromJSON ''"foo\u0000bar"''
"foo"
nix-repl> builtins.fromJSON ''"foo\u0000bar"'' == "foo"
true
```
Nevertheless, they are not actually truncated from the beginning:
```
nix-repl> builtins.fromJSON ''{ "lol": 1, "lol\u0000": 2 }'' // builtins.fromJSON ''{ "lol\u0000": 3 }'' // { lol = 4; }
{ lol = 4; "lol" = 3; }
```

**Steps To Reproduce**

Play around with fromJSON on JSON representations of strings containing \u0000 in various ways.

**Expected behavior**

Not quite clear, since Nix's syntax (AFAIK) has no native way to represent NUL. Sound-ish behaviours would probably be to truncate the strings as soon as part of fromJSON (comparatively easy, but also kind of wrong), or to ensure that none of the string-handling code stops at NULs.

**`nix-env --version` output**
nix-env (Nix) 2.18.1

**Additional context**

This was not originally discovered by me. It was brought to my attention (this time) and discussed a little on Matrix: https://matrix.to/#/!NBBFPbiuttRgTqbrcY:nixos.org/$2aTf5XblwYtjptsravT2dA2DBc_m6RMaDmxE7xYUtqs?via=nixos.org&via=matrix.org&via=nixos.dev

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by edolstra** [comment]
We should probably throw an error if `fromJSON` encounters a nul character.

**Comment by piegamesde** [comment]
I don't see why NUL code points should be handled specially in any way.

**Comment by fricklerhandwerk** [comment]
Triaged in Nix maintainer meeting:

This is worth fixing, somehow. Assigned @roberth

**Comment by NaN-git** [comment]
I'm also in favor of throwing an error, when a null character is encountered because any change is a change of the Nix language, which should not happen silently. The current behaviour makes no sense and another issue is that the symbol table uses `std::string`, i.e. it can handle null characters, but in all other places Nix uses C-strings, e.g. `builtins.attrNames` will return a truncated key, if it contains a null character. Thus null characters in symbols make no sense at the moment.

The long term fix would be to remove C-strings from Nix completely. They are inefficient, potentially insecure and several operations can be optimized, if the size would be known.

An option would be to represent a string as
```
struct NixString
{
    size_t size;
    char str[0];
};
```
If one bit of `size` would be reserved to indicate a string with less than 128 bytes, then short strings can be stored without any overhead because only one byte is required to store the length and the remaining bytes of `size` can store the first characters of the string (the actual size would be encoded in the LSBs of `size` on little endian machines and in the MSBs on big endian machines). Strings with less than `sizeof(size_t)` bytes would have no overhead either because the Boehm GC returns at least pointer aligned pointers and `malloc` has larger alignment anyhow.
Reserving one bit of `size` would limit the max. string length on 32 bit machines to `2**31 - 1` bytes, although this shouldn't be a limitation because whether an allocation with more than `2**31` bytes can succeed depends on the OS anyhow.
This can be combined with the optimization of storing short strings inline in the `Value` struct.

**Comment by piegamesde** [comment]
While this specific instance of NUL bytes not being handle correctly has been addressed, as far as I can tell there are still many other which remain. So can we maybe please keep this issue open as a tracker until a more thorough and permanent solution has been implemented?
