### ISSUE TITLE
`error: hash mismatch importing path` when `nix copy`ing a NixOS system to a remote host.  

### ISSUE THREAD

**Issue by RyanGibb** [NixOS/nix#10415]
**Describe the bug**

I an getting an `error: hash mismatch importing path` for my [NixOS configuration](https://github.com/RyanGibb/nixos) source path when copying it to a remote machine.

**Steps To Reproduce**

```
$ nix build -L .#nixosConfigurations.duck.config.system.build.toplevel
$ nix copy --to ssh-ng://root@duck ./result/ --no-check-sigs
error: hash mismatch importing path '/nix/store/7g1ndri1x7pizk1n0rld99mc14xmd5vq-source';
         specified: sha256:1c81kr9msl9dy5pld1dw824mnbqx3r91zzlwnnac4wcbz64r32fk
         got:       sha256:0450lrbg2vvs83ql59v19v5h0a5gqarn0f2lazp9qyad8b7svrhd
```

**Expected behavior**

No error.

**`nix-env --version` output**

nix-env (Nix) 2.18.1

**Comment by thufschmitt** [comment]
I suspect that your path is somehow corrupted. Can you try `nix store verify /nix/store/7g1ndri1x7pizk1n0rld99mc14xmd5vq-source` to confirm?

**Comment by RyanGibb** [comment]
Though, I'm still unsure why this is repeatably getting corrupted.

**Comment by roberth** [comment]
Could be a bad file system, bad hardware, or a bad radiation environment.

It's not always easy to distinguish these, but I've blamed and switched away from ext4 and btrfs. My zfs journey is young. I've had a broken SSD and I have once found a single bit flip in the Nix store by making a backup of a corrupted path. I'd like to blame that one on high energy cosmic particle radiation.

If it's truly repeatable it'd be interesting to make backups and compare them instead of just repairing - not using Nix, but `cp`, `tar` or any of the backup tools to be sure.

I'll close this for now because it's not actionable, and a new issue will get more attention when you open one.
