### ISSUE TITLE
nixos.org is out of date wrt latest Nix release

### ISSUE THREAD

**Issue by roberth** [NixOS/nix#10743]
**Describe the bug**

I don't know how nixos.org picks up our releases, but multiple things are out of sync:

- The download points to 2.22
  - `curl -IHEAD -vL https://nixos.org/nix/install 2>&1 | grep nix-`
- https://nixos.org/manual/nix/stable/index.html has the manual of 2.21
- https://nixos.org/manual/nix/unstable/index.html also has a version of 2.21
- https://nixos.org/download/ says latest is 2.21

Who's responsible here?

cc @fricklerhandwerk do you know?

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by fricklerhandwerk** [comment]
@Garbas maintains nixos.org. I think we're now at the point with nix.dev where we can redirect.

**Comment by fricklerhandwerk** [comment]
Triaged in Nix team meeting:

- @fricklerhandwerk: Ideally we'd only have installation instructions in one place, as proposed and rejected in https://github.com/NixOS/nixos-homepage/pull/1141#issuecomment-1790721590
  - I would want to supply instructions to install the Nix as shipped with the latest stable Nixpkgs/NixOS, because there's a use case (or sequence of events) where you'd install the latest Nix and set up Home Manager with a pinned Nixpkgs, and that may downgrade Nix to be unable to read the store database...
    - @roberth: would be good, Nix doesn't exist in isolation (also downgrades should just work) 
  - regardless, I'll have in my queue to set up the redirect for the Nix manual
