### ISSUE TITLE
Building Nix fails with stack overflow during doc generation on Amazon Linux

### ISSUE THREAD

**Issue by amarshall** [NixOS/nix#11085]
**Describe the bug**

Building Nix after baff34d728844870e62deea7847bbe1e97dfe157 via nixpkgs’s nix derivation on Amazon Linux results in the following error:

```
error: stack overflow (possible infinite recursion)
make: *** [doc/manual/local.mk:111: doc/manual/src/command-ref/new-cli] Error 1
make: *** Waiting for unfinished jobs....
  GEN    doc/manual/nix.conf.5
rm src/nix/generated-doc/files/profiles.md
error: builder for '/nix/store/z83afiad0yd76dbp00ydl8364a3sh677-nix-2.20.7.drv' failed with exit code 2;
```

**Steps To Reproduce**

1. Run Amazon Linux 2023 (primarily used ami-0649bea3443ede307) or Amazon Linux 2 (was unable to reproduce on NixOS, Ubuntu, or macOS)
2. Build Nix via nixpkgs’s nix derivation (was unable to reproduce with Nix’s own `package.nix`)
3. Build Nix 2.20 or later (really any version with baff34d728844870e62deea7847bbe1e97dfe157)

**Expected behavior**

Building Nix succeeds.

**`nix-env --version` output**

nix-env (Nix) 2.23.3

**Additional context**

- Primarily tested on x86_64-linux, but this also occurs on aarch64-linux
- Bisected to baff34d728844870e62deea7847bbe1e97dfe157; reverting that resolves
- I’m unsure what about Amazon Linux’s configuration causes this to occur there but not on other systems (they do have an *increased* stack size limit (10240) vs. other systems (8192), but reducing it did not change anything)
- Fails on current master (0363dbf2b956674d95b8597d2fedd20fc2b529df)
- The Nix version used to execute the build seems to not matter much (fails on 2.23.3, 2.20.8, 2.18.5)

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by roberth** [comment]
Stack overflows in the regular expression implementation are usually caught by our stack protection page and handler, which is the only source of this message, and the linked commit corroborates that.
The evaluator is used to process documentation for the manual, so it makes sense that you encounter it during the build.

Possible workaround: build without documentation, `./configure --disable-doc-gen`.

Possible solutions:

- We've previously [attempted](https://github.com/NixOS/nix/pull/9508) to switch our regex implementation to boost, which is more developed than the glibc one, but it produced different behavior, which is a no-go for the Nix language. The original contributor did not try to resolve the problem. Perhaps it's possible to configure boost correctly.
- It may be possible to remove the offending `match` call. You may run into problems with other expressions, but this would at least unblock a normal build for you.
  -  Introduce an [`hasInfix`](https://nixos.org/manual/nixpkgs/stable/index.html#function-library-lib.strings.hasInfix) primop that uses simple string matching instead of regular expressions.
  - Implement `hasInfix` by first splitting large strings. (Fun, but not also wasteful)
  - Probably the overflow happens because of a long _match_ not a long input:
    - Introduce a new primop like `match` that can be configured to match at arbitrary positions
    - Special-case regexes of the form `.*` something `.*`

**Comment by roberth** [comment]
> what system configuration would cause the stack overflow detection to be triggered only on some systems.

Afaik, just stack size as in `ulimit`.
I think we can rule out standard library differences, because you're building a derivation.

> * they do have an _increased_ stack size limit (10240)

If that statement applies to the hard limit, it may not be relevant, because the soft limit is already hard enough for us, as I don't think we try to increase the soft limit. Maybe we should!
