### ISSUE TITLE
How to set build-max-jobs to the number of CPUs I have?

### ISSUE THREAD

**Issue by nh2** [NixOS/nix#1127]
Current http://nixos.org/nix/manual/ says:

> **build-max-jobs**
>
>    This option defines the maximum number of jobs that Nix will try to build in parallel. The default is 1. You should generally set it to the number of CPUs in your system (e.g., 2 on an Athlon 64 X2). It can be overridden using the --max-jobs (-j) command line switch.

Looking at docs for `--max-jobs`:

> **--max-jobs, -j**
>
>    Sets the maximum number of build jobs that Nix will perform in parallel to the specified number. The default is specified by the build-max-jobs configuration setting, which itself defaults to 1.

So these two default to `1`.

However, looking at the changelog for `D.4. Release 1.8`:

> The configuration option `build-max-jobs` now defaults to the number of available CPU cores.

So I assume at some point it was changed back to `1`, but this didn't make it into a changelog?

Is there a value I can set `build-max-jobs` or `--max-jobs` to to get it auto-choose the number of CPUs I have?

**Comment by nh2** [comment]
And another question: `--max-jobs` also seems to determine the number of parallell binary cache downloads (which I'd like to have much higher than my number of CPUs as connection initiation is slow and I have fast internet).

Is there a way to set the number of parallel downloads independently of the compile parallelism?

(I guess a similar questions comes from https://www.reddit.com/r/NixOS/comments/5bke41/nixpkgs_configuring_parallel_fetch_from_binary/)

**Comment by nh2** [comment]
An example of parallel download making a big difference for download time (plotted are `--max-jobs 40`, `4` and `1`):

![screenshot from 2016-11-12 04-11-12](https://cloud.githubusercontent.com/assets/399535/20235329/3e296306-a88f-11e6-9683-8abdaece47c2.png)

**Comment by vcunat** [comment]
The `build-max-jobs` situation is a typo in changelog, apparently; `build-cores` is what's detected since de4cdd0d47adc70a4db12397a42c18ee50b4e662, though setting it to 0 is also taken by our nixpkgs stdenv as hint to auto-detect that anyway (`$NIX_BUILD_CORES`).

Separate control of the number of *substituted* paths in parallel would be a nice enhancement.

**Comment by srghma** [comment]
I dont understand:
1. is `build-max-jobs` should be deprecated in favor of `build-cores`? 
2. can I set `build-max-jobs` to 0 to use all available cores?

**Comment by edolstra** [comment]
You can set `max-jobs` to `auto` (7251d048fa812d2551b7003bc9f13a8f5d4c95a5). No, it's not deprecated since it serves a different purpose (`max-jobs` is about the number of derivations that Nix will build in parallel, while `cores` is about parallelism *inside* a derivation, e.g. what `make -j` will use).
