### ISSUE TITLE
After restoring from a Time Machine backup, I can no longer reinstall Nix

### ISSUE THREAD

**Issue by ivyjsgit** [NixOS/nix#11323]
## Platform

- [ ] Linux: 
- [x] macOS
- [ ] WSL

## Additional information
I've recently restored my Mac from a Time Machine backup using recovery assistant. I had to reinstall nix because for some reason it wasn't installed properly anymore.

I've tried deleting the users that it complains about using dscl, but I am not able to continue through the script because it continues to complain about the users existing

## Output

<details><summary>Output</summary>

```log
---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo launchctl kickstart -k system/org.nixos.darwin-store

to launch the Nix volume mounter


~~> Setting up the build group nixbld
            Exists:	Yes

~~> Setting up the build user _nixbld1

---- oh no! --------------------------------------------------------------------
It seems the build user _nixbld1 already exists, but with the UID
with the UID ''. This script can't really handle that right
now, so I'm going to give up.

If you already created the users and you know they start from
 and go up from there, you can edit this script and change
NIX_FIRST_BUILD_UID near the top of the file to  and try
again.

We'd love to help if you need it.

You can open an issue at
https://github.com/NixOS/nix/issues/new?labels=installer&template=installer.md

Or get in touch with the community: https://nixos.org/community
```

</details>

## Priorities

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by ivyjsgit** [comment]
To fix this, I had to 
change the NIX_FIRST_BUILD_UID in install-darwin-multi-user.sh to read

export NIX_FIRST_BUILD_UID="${NIX_FIRST_BUILD_UID:-600}"

instead of

export NIX_FIRST_BUILD_UID="${NIX_FIRST_BUILD_UID:-301}"

and then I had to redelete all nix users

**Comment by abathur** [comment]
The error message isn't exactly the same, but this may be related (or at least similar) to a known problem with macOS not cleanly migrating users and groups when people set up a new system with Migration Assistant:

- #6078

This might also be related to an issue where the same error has been reported (but none of them mentioned migration/recovery, and I don't think we've isolated a cause yet):
- #10948

Since you've already tried to reinstall, I'd recommend just following uninstall instructions before reinstalling it: https://nixos.org/manual/nix/stable/installation/uninstall.html#macos

**Comment by tomberek** [comment]
Closing as duplicate, feel free to reach out if you need more help.
