### ISSUE TITLE
nix-shell very slow on macOS

### ISSUE THREAD

**Issue by NfNitLoop** [NixOS/nix#11345]
## Platform

- [ ] Linux: 
- [X] macOS  (v15 beta. `uname -a` = Darwin Bovajxa.local 24.0.0 Darwin Kernel Version 24.0.0: Mon Jul  1 21:56:49 PDT 2024; root:xnu-11215.0.132.501.1~1/RELEASE_ARM64_T6020 arm64)
- [ ] WSL

## Additional information

I'm a new user to Nix, following the instructions in [Declarative Shell Environments][1]. Oddly, using a declarative environment via a shell.nix file is **much slower** than just specifying it ad hoc. 

[1]: https://nix.dev/tutorials/first-steps/declarative-shell

The contents of my `shell.nix` is just: 

```nix
let
  nixpkgs = fetchTarball "https://github.com/NixOS/nixpkgs/tarball/nixos-24.05";
  pkgs = import nixpkgs { config = {}; overlays = []; };
in

pkgs.mkShellNoCC {
  packages = with pkgs; [
    cowsay
    lolcat
  ];
}
```

## Output

<details><summary>Output</summary>

With declarative shell:

```log
> time nix-shell --run "cowsay moo"
 _____
< moo >
 -----
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||
        9.86 real         1.93 user         1.84 sys
```

ad hoc:

```
> time nix-shell -p cowsay --run "cowsay moo"
install: skipping file '/dev/fd/63', as it was replaced while being copied
 _____
< moo >
 -----
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||
        1.07 real         0.51 user         0.15 sys
```

</details>

## Priorities

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by tomberek** [comment]
In the first case, you will be fetching a tarball that can change over time (https://github.com/NixOS/nixpkgs/tarball/nixos-24.05), so if you are past the tarball-ttl time (default is an hour), then you will re-fetch that tarball. This branch changes due to backports and security fixes.

In the second case, you are automatically getting the Nixpkgs form NIX_PATH, essentially from '<nixpkgs>'. This is already on your system and likely has not changed unless you've run a `nix channel --update`. Therefore it is already present, no downloading, no un-tar-ing necessary.

You can verify this by modifying the fetchTarball call:
```patch
- nixpkgs = fetchTarball "https://github.com/NixOS/nixpkgs/tarball/nixos-24.05";
+ nixpkgs = <nixpkgs>;
```

or by including a hash to prevent the re-fetching:

```patch
- nixpkgs = fetchTarball "https://github.com/NixOS/nixpkgs/tarball/nixos-24.05";
+   nixpkgs = fetchTarball {
+       url = "https://github.com/NixOS/nixpkgs/tarball/311b3ee3078b6a7cdbbbf5c249d1722bc431af1a";
+       sha256 = "sha256:1hv27fkcnbwglf8kx0dgl9dqpr3jp3g04hfabmj2gscvz8k8nrcy";
+   };


So, the first form is saying "please keep re-checking what the latest release-24.05 is, then give me cowsay." While the second or the modifying forms are saying "use the Nixpkgs i already have, then give me cowsay". 

I'm not sure what to

**Comment by tomberek** [comment]
Perhaps change the documentation at nix.dev?

**Comment by NfNitLoop** [comment]
> if you are past the tarball-ttl time (default is an hour), then you will re-fetch that tarball

That's not what I observed. I could rerun the command multiple times back-to-back and they'd all take 9+ seconds. It's not just once an hour.

When I do pass the hour threshold, I see 

```
unpacking 'https://github.com/NixOS/nixpkgs/tarball/nixos-24.05' into the Git cache…
…
       11.94 real         1.98 user         1.94 sys
```

Which is more understandable.

It seems like it might be re-downloading & reprocessing that tarball every run, even though it hasn't changed. Shouldn't it do something like an HTTP GET with an `If-Modified-Since` (or the Etag `If-None-Match`) header to avoid that overhead?

> Therefore it is already present, no downloading, no un-tar-ing necessary.

I'm a new user -- Is 1 second to run `cowsay` normal/acceptable in that case, then?

**Comment by NfNitLoop** [comment]
> Perhaps change the documentation at nix.dev? https://github.com/NixOS/nix.dev/issues

Definitely seems worth documenting. I stopped reading the tutorial at that point, and I wouldn't yet know how to get from

```nix
nixpkgs = fetchTarball "https://github.com/NixOS/nixpkgs/tarball/nixos-24.05";
```
to
```nix
   nixpkgs = fetchTarball {
       url = "https://github.com/NixOS/nixpkgs/tarball/311b3ee3078b6a7cdbbbf5c249d1722bc431af1a";
       sha256 = "sha256:1hv27fkcnbwglf8kx0dgl9dqpr3jp3g04hfabmj2gscvz8k8nrcy";
   };
```

**Comment by tomberek** [comment]
Fair point about the behavior for under the hour TTL. That was a bug (fixed in https://github.com/NixOS/nix/pull/11285) so that should be on it's way. That should make the two cases behave the same under repeated runs and remove the 8s to download and unpack.

Regarding the 1s  to run cowsay. This is mainly the time to evaluate Nixpkgs. There are a few options to bypass the need for evaluation.
1. Install to your default profile:
    - `nix-env --install --file '<nixpkgs>' --attr cowsay`
    - `cowsay moo`
2. Install to a local profile (`nix-env -iA:
    - `nix-env --install --file '<nixpkgs>' --attr cowsay --profile ./my-tools`
    - `./my-tools/bin/cowsay moo`
3. Create a result symlink only:
    - `nix-build '<nixpkgs>' --attr cowsay`
    - `./result/bin/cowsay moo`
4. flakes have a CLI-level cache allowing us to skip evaluation, so this is nearly instant for repeated runs after the first download:
    - `nix run nixpkgs#cowsay moo`
