### ISSUE TITLE
A way to temporarily install dependencies and then have them auto delete after

### ISSUE THREAD

**Issue by RustoMCSpit** [NixOS/nix#11724]
# Description of the new feature/enhancement

If someone wants to build an app from source, they need dependencies. However, people do not want to clog up their systems with useless dependencies. Having the ability to install a multitude of dependencies and have them auto delete automatically once the terminal is closed would be ideal.

e.g. https://github.com/minetest/minetest/issues/15198#issuecomment-2420730855

# Proposed technical implementation details (optional)

something along the lines of
``` 
sudo apt install -t g++ make libc6-dev cmake libpng-dev libjpeg-dev libxi-dev libgl1-mesa-dev libsqlite3-dev libogg-dev libvorbis-dev libopenal-dev libcurl4-gnutls-dev libfreetype6-dev zlib1g-dev libgmp-dev libjsoncpp-dev libzstd-dev libluajit-5.1-dev gettext
```

the terminal would then check which of these are already installed and ignore them, but download those that arent temporarily. you could then close the app and the ones that were downloaded would delete whilst the ones that were already on your system would stay

(i use linux by the way, so the sudo command would be something else)

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by roberth** [comment]
This sounds a lot like the "nix shell" functionality we already have.
- [`nix develop`](https://nix.dev/manual/nix/latest/command-ref/new-cli/nix3-develop)
- [`nix-shell`](https://nix.dev/manual/nix/latest/command-ref/nix-shell)
- commands only: [`nix shell`](https://nix.dev/manual/nix/2.24/command-ref/new-cli/nix3-env-shell)

I think it would be annoying if those dependencies are removed eagerly on shell exit, as that could happen by mistake or for the purpose of extending it, so I don't think this should be the default behavior for `nix-shell`/`nix shell`/`nix develop`, ie the commands that already provide this functionality, and relying on the garbage collector to delete them, instead of doing it immediately.

I wouldn't discount the need for a flag that collects the relevant deps immediately, but it seems that you're not using these commands yet, so I kindly suggest to reopen if in your experience such a flag is really needed; otherwise collecting the garbage later seems preferable. Also feel free to ask questions, especially if I misunderstood.

**Comment by RustoMCSpit** [comment]
> I wouldn't discount the need for a flag that collects the relevant deps immediately, but it seems that you're not using these commands yet,

something like that, and a way to delete those deps afterwards without deleting the deps i already had

**Comment by RustoMCSpit** [comment]
> Also feel free to ask questions, especially if I misunderstood.

no you wouldnt have misunderstood, i know little about nix!
