### ISSUE TITLE
CLI

### ISSUE THREAD

**Issue by ItzEmoji** [NixOS/nix#11755]
**Is your feature request related to a problem? Please describe.**
A So, the CLI of nix pkg manager looks just disgusting and it should be more colorful and more structured, and yes your pkg like nixpkgs is just crazy and the Community just grows, but this awful ui is just making it less attrative 

**Describe the solution you'd like**
A Get inspiration by like nala like he did with Apt this just look crazy good and i would like that on nix and yes i k there is a nix gui but it doesn't change it. 

**Describe alternatives you've considered**
A Nothing

**Additional context**
You guys you make alot of good work like no joke your nixpkgs repo is litterly bigger then the aur and more up to date Ty guys

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by roberth** [comment]
Hi @ItzEmoji, thanks for the kind words.

It's not clear to me where your criticism applies. Do you use the old `nix-<...>` CLI commands or the new `nix <subcommand>` commands?

Could you open one or two issues about specific cases you think are most deserving of improvements?

I'll close this for now. We do care about how Nix looks and feels and we make such improvements every now and then, but in order to have a readable conversation about that, it helps to discuss one specific thing in each issue. It will have to be read many times, when discussing the improvement, when reviewing it, by contributors who'd like to implement it, etc, so having individual and specific issues helps keep that conversation focused. So feel free to open an issue for a specific improvement.
