### ISSUE TITLE
After macOs 15.1 update nix get nuked, the installer fails at reinstalling it

### ISSUE THREAD

**Issue by boborbt** [NixOS/nix#11805]
## Platform

- [ ] Linux: 
- [X] macOS
- [ ] WSL

## Additional information

As mentioned in the subject, macOs 15.1 update nukes the nixos installation. Trying reinstalling nix fails.

## Output

Please see the stderr and stdout outputs in the attached files.
[stderr.log](https://github.com/user-attachments/files/17623895/stderr.log)
[stdout.log](https://github.com/user-attachments/files/17623896/stdout.log)

**Comment by cole-h** [comment]
How do you mean "nix get nuked"? It's no longer available on your PATH? If so, you may want to take a look at this issue: https://github.com/NixOS/nix/issues/3616

This happens because macOS updates overwrite the various profile files that we write the "please add Nix tools to the PATH" snippet to.

**Comment by boborbt** [comment]
> How do you mean "nix get nuked"? It's no longer available on your PATH? If so, you may want to take a look at this issue: #3616

Unfortunately I’m not able to be very specific since I removed and reinstalled nix to workaround the problem. From what I remember the whole /nix directory appeared to be empty, but I learnt that during one of the first checks I did and I’m now afraid I missed something less dramatic like the issue you are mentioning. 

I’ll report more information here in case I’ll encounter the problem again.

**Comment by abathur** [comment]
Since it doesn't sound like we have anything actionable here for now, I'm going to tentatively close this specific issue.

If you do run into this again and open a new issue, can you include a single copy of the output of the process in your terminal instead of the split stderr/out files? (I didn't see anything obvious in the stderr log here, but it's generally more helpful to see any error messages in context rather than separate.)
