### ISSUE TITLE
Resolve `//path` to flake root

### ISSUE THREAD

**Issue by msanft** [NixOS/nix#12070]
## Is your feature request related to a problem?

Users of flakes in repositories with somewhat-nested tree layouts often get into positions where they have to:

```nix
import ../../../../foo.nix
```

This is error-prone. For example, if `foo.nix` gets moved around, it's easy to add a `../` too much, causing errors.
Furthermore, this is very much not nice to look at.

## Proposed solution

Resolve a path of form `//path` to the flake's root directory. If I have a `flake.nix` in `/home/me/my-project/flake.nix`, and the project layout is as follows:

- `/home/me/my-project/foo/bar.nix`:
  - `"foo"`
- `/home/me/my-project/some/deeply/nested/tree/package.nix`:
  - `import //foo/bar.nix`

Evaluating `/home/me/my-project/some/deeply/nested/tree/package.nix` should return `"foo"`.

## Alternative solutions

Passing `self` around should work, but having a short-hand path operation for this would be nice.

## Checklist

- [x] checked [latest Nix manual] \([source])
- [x] checked [open feature issues and pull requests] for possible duplicates

[latest Nix manual]: https://nixos.org/manual/nix/unstable/
[source]: https://github.com/NixOS/nix/tree/master/doc/manual/source
[open feature issues and pull requests]: https://github.com/NixOS/nix/labels/feature

---

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by roberth** [comment]
I'm not entirely convinced that we need this. (Excuse my ignorance)

It might be symptomatic of a lacking attrset-based structure, which doesn't scale well beyond a few function calls, because you're not benefiting from the implicit memoization that attrsets like the `packages` output attribute provide. (We do implicitly memoize files' top level values, but that's inconsequential for most files, which contain functions)

In my experience, relative references tend to be replaced by references not necessarily to `self` but to attributes with in it, or in some other fixpoint, like `mkScope`, or `config` in flake-parts.

`mkScope`/`callPackage` example:
https://github.com/NixOS/nix/blob/3f3feae33e3381a2ea5928febe03329f0a578b20/src/nix/package.nix#L5-L8

What should the behavior be for subflakes?

> if `foo.nix` gets moved around

In my opinion, we should use content aware tools that do this kind of thing automatically.
This feature only solves half of the problem, and makes expressions prone to the inverse problem: when you move a subtree with internal references, you'll have to update the `//` paths to refer to the new location of the subtree. This wouldn't be necessary if the paths were relative.

**Comment by roberth** [comment]
Implementing this as proposed would be a breaking change to the expression language, because it changes the interpretation of

```nix
nix-repl> foo = { bar = true; }

nix-repl> { } //foo
{ bar = true; }

```

It also makes the following ambiguous - either:

```nix
nix-repl> { __functor = self: arg: arg + "/bar"; } //foo
//foo/bar

```

or

```nix
nix-repl> { __functor = self: arg: arg + "/bar"; } //foo
{ __functor = <...>; bar = true; }
```

**Comment by msanft** [comment]
Thanks for your replies @roberth!

> This feature only solves half of the problem, and makes expressions prone to the inverse problem: when you move a subtree with internal references, you'll have to update the // paths to refer to the new location of the subtree. This wouldn't be necessary if the paths were relative.

That's definitely a fair point I didn't consider very much so far. In general, my suggestion was very much tied to the one-flake structure.

> Implementing this as proposed would be a breaking change to the expression language

Oopsie! I didn't consider this case as well. For me, that's definitely outweighing the benefits of such a shorthand. 

Considering the points you've made, if you wouldn't object to it, I'd close this issue then.

**Comment by roberth** [comment]
No problem. I have to say I quite liked the idea at first, but it doesn't seem to be a great fit.
We could consider it again if/when we have [language versioning](https://github.com/NixOS/rfcs/pull/137).
