### ISSUE TITLE
Wait for build users instead of failing

### ISSUE THREAD

**Issue by expipiplus1** [NixOS/nix#1216]
It would be nice to have the option of waiting for a build user to become free instead of failing to build.

I'm talking about this error: `error: all build users are currently in use; consider creating additional users and adding them to the ‘nixbld’ group`

Is there ever a case where failing is the preferred option to waiting? Hopefully waiting can become the default behaviour.

**Comment by waynr** [comment]
For anyone else who encounters this problem, the way I solved it was by bumping my `nixbld<N>` users from 10 to 100. My multi user nix build is happily chugging along now.

**Comment by jonringer** [comment]
For NixOS users who may stumble upon this thread, the setting is `nix.nrBuildUsers = <int>;` in your /etc/nixos/configuration.nix

https://nixos.org/nixos/options.html#nrbuildusers

**Comment by Gabriel439** [comment]
One thing that triggers this problem is enabling distributed builds when dealing with a large number of cores (32+)

The reason why is that,  by default, the setting for `nix.nrBuildUsers` is essentially `max 32 nix.maxJobs`, which is fine when all builds are local because `nix.maxJobs` then never exceeds `nix.nrBuildUsers`.  However, things break down if the number of build slots across all available remote builders plus the number of local build slots exceeds `nix.nrBuildUsers`, because then you run the risk of exhausting the available Nix users.

The fix is to increase the `nix.nrBuildUsers` option like @waynr suggested, but if you don't want to guess what the value should be then set it to be the sum of all available build slots across all machines that builds can be delegated to (including the local machine).

For example, if your NixOS configuration were:

```nix
{ nix.maxJobs = 32;

  nix.distributedBuilds = true;

  nix.buildMachines = [
    { hostName = "example.com";
      sshUser = "example";
      sshKey = "/root/.ssh/id_rsa";
      system = "x86_64-linux";
      maxJobs = 32;
      speedFactor = 1;
      supportedFeatures = [ "kvm" ];
      mandatoryFeatures = [ "perf" ];
    }
  ];
}
```

Then the correct setting for `nix.nrBuildUsers` would be `64` (32 for the local machine and 32 for the remote builder).

This could potentially be mitigated at the NixOS level by changing the default value for `nix.maxJobs` to factor in the `nix.buildMachines` option when calculating how many builders to create.  However, that wouldn't fix people using Nix the package manager on a non-NixOS system.

**Comment by balsoft** [comment]
Is there any work on this?

**Comment by balsoft** [comment]
I've created a _working_ solution for this, but it's not ideal. I'll submit a PR once I'm sure that it at least somewhat works.

**Comment by balsoft** [comment]
Created a PR.

**Comment by domenkozar** [comment]
Fixed in https://github.com/NixOS/nix/pull/3564

**Comment by expipiplus1** [comment]
Thanks!

**Comment by shmish111** [comment]
I had this on a machine with 96 cores when `nrBuildUsers` was set to `auto`. I had to change it to 96. I would imagine that `auto` should look at the number of cores on the machine no?
