### ISSUE TITLE
When will 1.12 come out?

### ISSUE THREAD

**Issue by kballard** [NixOS/nix#1219]
#921 was supposedly fixed many months ago, but there's still no release that actually includes the fixes. I assume this is expected to go in 1.12, since there have been two dot releases of 1.11 since then that don't include the changes. The milestone for 1.12 isn't very useful, all it contains is 2 documentation bugs. I'd really like to know when 1.12 is actually expected to come out, as #921 is a serious issue for using Nix on macOS.

**Comment by kballard** [comment]
Alternatively, is there any chance the relevant fixes for #921 could go into 1.11?

**Comment by edolstra** [comment]
There is no ETA at the moment, sorry.

**Comment by copumpkin** [comment]
@kballard it's tricky to backport things to 1.11 since 1.12 rewrote a huge chunk of Nix in C++ (it used to be in perl). Having said that I do think it could make sense to put #921 into a 1.11.7 if 1.12 is very far out.

@edolstra I do think it could be helpful to write down the criteria you'd use to consider a 1.12 release. Perhaps something like "once we add decent support for the `nix foo` command and have gained some confidence in the stability of the new C++ code, I think it'd make sense to release"

How do you normally go about getting folks to test pre-release versions? I see `nixUnstable` in nixpkgs but I think most people just ignore it.

**Comment by veprbl** [comment]
If we are talking about porting https://github.com/NixOS/nix/commit/fb2dd3210072a03526e881cd2547cf4c2df4ba52 , it should not be tricky at all. The only C++ change seems to be achievable by similar change to https://github.com/NixOS/nix/blob/4f3cf06c97cb1f15c74b51b60673a0ed9af0a603/scripts/download-from-binary-cache.pl.in#L44 .

**Comment by copumpkin** [comment]
Didn't @edolstra end up reverting that?

**Comment by veprbl** [comment]
Made a PR. Any volunteers to test? :)
