### ISSUE TITLE
Remove the build hook mechanism

### ISSUE THREAD

**Issue by edolstra** [NixOS/nix#1221]
Like the substituter mechanism, we can use the Store abstraction instead. I.e. we call `remoteStore->buildPaths(...)` directly rather than calling an external process that does the same thing.

**Comment by expipiplus1** [comment]
Would this just be an internal change to Nix? If not, how would this affect those of us who are using `NIX_BUILD_HOOK` with things other than `build-remote.pl`?

**Comment by edolstra** [comment]
It would break your build hook. What are you using `NIX_BUILD_HOOK` for?

**Comment by expipiplus1** [comment]
I'm using `NIX_BUILD_HOOK` with `nix-instantiate` and `nix-store --realise` in order to easily get machine readable output of the build in progress. By using a build hook with these tools I can have precise control over what's being built when, and the output of the builder.

It's also been useful in getting some better `--dry-run` functionality as described [here](https://github.com/NixOS/nix/issues/666#issuecomment-277542784) too.

**Comment by veprbl** [comment]
@expipiplus1 
Which entity executes ```NIX_BUILD_HOOK``` in your scenario? I'm asking because both ```nix-build``` and  ```nix-store -r``` will try to lock the output path, so you can't have one just call another.

**Comment by ledettwy** [comment]
Would doing this prevent implementation of use cases like https://github.com/NixOS/nix/issues/1914?

**Comment by edolstra** [comment]
@ledettwy No, it shouldn't affect that.

**Comment by volth** [comment]
This also un-fixes https://github.com/NixOS/nix/issues/1118
Since ```--no-build-hook``` is removed there is no way to force local build

**Comment by edolstra** [comment]
@volth You can force a local build by passing `--builders ''`.

**Comment by volth** [comment]
Yes, but it requres to be a trusted user.
I understand that adding builders requires privilegies, but removing?

**Comment by edolstra** [comment]
You're right, it requires a trusted user. We could require the untrusted user's `builders` to be a subset of the daemons `builders` though.

**Comment by srghma** [comment]
I've come from here https://github.com/NixOS/nixpkgs/issues/28816 and I'm looking for a way to pass impure env variable to `nix-build`

Building locally should help, but I can't make the example work, can someone help me

```
code=`<<'EOF'
with import <nixpkgs> {};
stdenv.mkDerivation {
  name="impure";
  phases=["buildPhase"];
  impureEnvVars=["IMPURE"];
  buildPhase=''
    env | grep IMPURE
    if [ -z $IMPURE ]; then
      echo "Error"
      exit 1
    fi
    echo "foo" > $out
  '';
}
EOF`
export IMPURE=iop; nix-build -E "$code"
```

result

```
$ code=`<<'EOF'
with import <nixpkgs> {};
stdenv.mkDerivation {
  name="impure";
  phases=["buildPhase"];
  impureEnvVars=["IMPURE"];
  buildPhase=''
    env | grep IMPURE
    if [ -z $IMPURE ]; then
      echo "Error"
      exit 1
    fi
    echo "foo" > $out
  '';
}
EOF`
export IMPURE=iop; nix-build -E "$code"

these derivations will be built:
  /nix/store/dvsl63bq4qmlrs79wbxvc3vrbxzw6xad-impure.drv
building '/nix/store/dvsl63bq4qmlrs79wbxvc3vrbxzw6xad-impure.drv'...
building
impureEnvVars=IMPURE
buildPhase=env | grep IMPURE
if [ -z $IMPURE ]; then
Error
builder for '/nix/store/dvsl63bq4qmlrs79wbxvc3vrbxzw6xad-impure.drv' failed with exit code 1
error: build of '/nix/store/dvsl63bq4qmlrs79wbxvc3vrbxzw6xad-impure.drv' failed
```

**Comment by arianvp** [comment]
I'm using build hooks to incrementally push things to the cache (as opposed to only after a full derivation built). Is there a better mechanism for doing this?

**Comment by arianvp** [comment]
Nevermind. I'm using `post-build` hooks. sorry

**Comment by Ericson2314** [comment]
I have wondered whether as part of a migration we could have a `build-hook://` store too.

**Comment by edolstra** [comment]
Nix team discussion: The consensus is that we want to get rid of the build hook. There may be some issues around derivation cancellation, but that's not a big problem right now.

As a first step, we could remove the `build-hook` setting.

**Comment by domenkozar** [comment]
Is there an alternative? This will break many existing CI setups.

**Comment by Ericson2314** [comment]
Alternative to which part? Overriding the build hook?

If that is in wide use, then yes we'll have to approach this the other way of doing a `remoteBuildersNg` (`haskellPackagsNg`, I remember you!) and then migrating people over to it, and then getting rid of the old build-hook way.

**Comment by L-as** [comment]
What is the point in removing it if it's e.g. only 100 lines of code to maintain?

I still do think remote building shouldn't go through the hook, but the hook might still be useful to keep around (for CI, as noted above).

OTOH, wouldn't the C API be a suitable replacement too?

**Comment by Ericson2314** [comment]
Closely related to #5025

**Comment by roberth** [comment]
Discussed in meeting today:

- Removing the build hook
  - Might need refactor using coroutines
  - @xokdvium: Lix have done some work in this direction
  - @Ericson2314: Multiple protocol replacements are in development, not just Lix but also the STA Hydra improvements (gRPC)
  - @Ericson2314: Would like to get rid of `ssh:`
  - @edolstra: May want an asynchronous interface (initiating separately from waiting and such)

**Comment by lisanna-dettwyler** [comment]
I have [software](https://github.com/lisanna-dettwyler/nix-scheduler-hook) that depends on the build hook mechanism. What is the recommended way to modify such software to continue working without needing to be invoked as a build hook?

**Comment by lisanna-dettwyler** [comment]
I've done some reading, and it looks like the suggested ways to deal with this are to implement a custom store in a plugin, or to masquerade as a `--builders`  machine with an SSH frontend and reimplementing the nix-daemon's builder protocol, which looks to be non-trivial.

There's a drawback to implementing this as a custom store, in that starting the build locally with `--store` will not copy the build result back to the submitter. In the case of my build hook (submitting builds to HPC cluster schedulers), it would also have to track state in-between invocations of nix (nix build && nix copy), because there is no guarantee that the local store used on the job's cluster node is on a shared filesystem, so the custom store wouldn't otherwise know from where in the cluster to retrieve a built path.

You could in theory only use the custom store plugin in a `--builders` machine, with the `remote-store` attribute, so that the custom store can track state in memory. However, this would require specifying your localhost as a builder, which feels like a hack.

**Comment by Ericson2314** [comment]
@lisanna-dettwyler sorry for not responding earlier, but I would want to make sure that if/when this happens, your slurm work isn't just left out to dry.

I don't know exactly what things would look like, but it is quite possible that there could be a "universal" new store that essentially implements the old build hook protocol or something very much like it. I would consider it a bit fishy if that *weren't* possible.

**Comment by Ericson2314** [comment]
BTW: #12687 doesn't link this, but has a TODO saying it should be reverted once this is done.
