### ISSUE TITLE
fetchTarball and implicit dependencies on tar and gzip?

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nix#1234]
I haven't tied down a proper reproduction yet, but a friend of mine reported that `fetchTarball` complained about a missing `tar` and `gzip` dependency when he tried using it, which seems like a known issue from [here](https://github.com/NixOS/nix/blob/master/src/libstore/download.cc#L611-L612).

cc @edolstra

**Comment by copumpkin** [comment]
It looks like we'll have similar issues with `git` and https://github.com/NixOS/nix/blob/master/src/libexpr/primops/fetchgit.cc.

**Comment by Shou** [comment]
The work done in https://github.com/NixOS/nix/pull/2498 might be generally relevant here

**Comment by FRidh** [comment]
related https://github.com/NixOS/nix/issues/2419

**Comment by vcunat** [comment]
If these properties remain, they should certainly be documented in https://nixos.org/nix/manual/#ssec-builtins

Another possible approach: nix already has a runtime dependency on a minimalistic busybox for the sandbox shell, so we might just build it with a couple more utilities and use those instead of `$PATH`.  Quick test: ATM it has du size 160k, and adding `CONFIG_TAR y` only bumped it to 176k (including space for one extra symlink).

**Comment by edolstra** [comment]
The dependency on `tar` is removed by #2748 (especially 5351f1bd36647617d26193f31ea58ef11d78280c).

**Comment by 3noch** [comment]
Can this be closed then?

**Comment by edolstra** [comment]
Yes, thanks!
