### ISSUE TITLE
Backport fetchTarball hash

### ISSUE THREAD

**Issue by FRidh** [NixOS/nix#1299]
Could we have 06bbfb6004942bfcddd930e746ee7a2bfe5c3872 in 1.11.x?

**Comment by taktoa** [comment]
Seconded; we could really use this here at Awake Security.

**Comment by taktoa** [comment]
In the mean time, you can use

```nix
import <nix/fetchurl.nix> {
  url = "https://example.com/foo.tar.gz";
  sha256 = "0hk0zxxibl7r62nmzaf4qbdrqack5xs7skcys82bqi8glf2qjr7z";
  system = builtins.currentSystem;
  executable = false;
  unpack = true;
}
```

**Comment by FRidh** [comment]
Interesting. I knew `fetchTarball` shared code path and the only difference was the `unpack` parameter, but I didn't know you could just import it.

We could create a `fetchTarball` function in Nixpkgs that utilizes this until Nix 1.12 is stable. @edolstra, is there any reason against doing that?

**Comment by edolstra** [comment]
@FRidh 06bbfb6 does not cherry-pick straightforwardly on the 1.11 branch, so I'd prefer not to, sorry.

`builtins.fetchTarball` and `<nix/fetchurl.nix>` are very different in that the former doesn't rely on import-from-derivation. Import-from-derivation should generally be avoided in Nixpkgs because it causes builds at evaluation time (which fails in read-only mode, e.g. in `nix-env -qa`).

**Comment by FRidh** [comment]
Thank you for the clarification. I'm a happy user of 1.12 so I don't *really* mind.
