### ISSUE TITLE
1.11 release with builtins.exec

### ISSUE THREAD

**Issue by shlevy** [NixOS/nix#1300]
https://github.com/NixOS/nix/commit/967f23198101e88d974636e47f359401ee93489b and https://github.com/NixOS/nix/commit/eb6f3d5159f0bce25b2c8afb19bc55cf5c56ec70 add a pretty significant convenience to nix that we would like to take advantage of.

**Comment by edolstra** [comment]
Sorry, but I don't really want to start adding bleeding-edge features that have seen little testing to our maintenance branch. For example, if it turns out that the `exec` interface needs tweaking (as we did in eb6f3d5159f0bce25b2c8afb19bc55cf5c56ec70), we can't because users may be using it already. So we're stuck with it forever.

**Comment by shlevy** [comment]
OK. How should we do the testing? Can we make a plan for this?

**Comment by shlevy** [comment]
OK, I've pushed a release of https://github.com/shlevy/nix-plugins with a copy of builtins.exec, and I'll use that for my more extensive testing.

**Comment by PlumpMath** [comment]
nix 2.4 + nix-darwin
I tried https://github.com/shlevy/nix-plugins , but nix is broken unrecoverable.
I just wanted to do builtins.exec...
