### ISSUE TITLE
S3BinaryCacheStore is eventually consistent

### ISSUE THREAD

**Issue by edolstra** [NixOS/nix#1420]
S3 provides read-after-write consistency for new keys, but only if you haven't previously done a GET or HEAD request on that key (http://docs.aws.amazon.com/AmazonS3/latest/dev/Introduction.html#ConsistencyModel). Unfortunately, when uploading a NAR file, `BinaryCacheStore::addToStore()` first checks whether that file already exists (to prevent a potentially big re-upload). As a result we get eventual consistency, so subsequent GETs on the NAR file might fail for a while.

This might explain intermittent NAR 404 failures seen in the past (e.g. https://github.com/NixOS/nixpkgs/issues/14874#issuecomment-213479517, https://github.com/NixOS/nixpkgs/issues/14874#issuecomment-282573367, https://github.com/NixOS/nixpkgs/issues/14874#issuecomment-283894488).

The obvious fix is not to check for existence, but that can cause unnecessary re-uploads of existing files. However, this will only happen if different store paths have the same NAR contents, so it's probably not a big deal.

This issue also affects .narinfo files, but there a 404 is an expected result. (Though eventual consistency could lead to incomplete closures, e.g. where a .narinfo is visible, but the .narinfo for a dependency is not). Unfortunately, this is unfixable because it's always possible that somebody has done a prior lookup of a non-existent .narinfo.

**Comment by zimbatm** [comment]
Another way to check for the existence of a file is to list the files in the bucket using a very specific "prefix". https://docs.aws.amazon.com/AmazonS3/latest/API/v2-RESTBucketGET.html

Ex: `aws s3 ls s3://bucket-name/filename`

**Comment by butterflya** [comment]
You can follow https://aws.amazon.com/premiumsupport/knowledge-center/data-integrity-s3/. 

In short, you get the hash back from Amazon of what you uploaded, then you put that hash in some piece of persistent storage (I am assuming that you have some server from which you upload the files to S3). Then in the new implementation of `BinaryCacheStore::addToStore()` you use this persistent storage for your existence query. 

This is also the approach taken by http://www.stackdriver.com/eventual-consistency-really-eventual/ (but I thought of it independently).

I am not sure which clients can do GET requests, but if this set contains the entire world, you need to make it slightly more complex. 

Before every "update" of S3 you call `rand` (possibly multiple times to concatenate the result). Let's suppose the existing files on S3 are in buckets like /foo/bar/baz. Then you do an S3 `cp` operation from /foo/bar/baz to /foo<random>/bar/baz. This results in a doubling of the stored data on S3. 

If a client now wants to do download something, they need to obtain this random number from you in order to find anything new. As such the probability of the event you described as `this is unfixable` can be made arbitrarily small. 

All you need to decide on last is how long you want to keep non-updated versions available. Since there are no "updates" anymore on files on S3, there is no eventual consistency problem anymore, and the old files can be deleted immediately after the full cp operation is complete and the random number has been made available via a location which is consistent. Hosting a single number seems a reasonable cost and is likely even optimal. For hosting this consistent random number, you could use Amazon DynamoDB with strong read consistency for what is probably going to be less than one USD per year.

I believe I have addressed all problems now.

**Comment by edolstra** [comment]
Closing since S3 is now [strongly consistent](https://aws.amazon.com/s3/consistency/)!
