### ISSUE TITLE
Run command as root in nix?

### ISSUE THREAD

**Issue by lukego** [NixOS/nix#1436]
How should I run a command as root under nix? (On Linux but not necessarily NixOS.)

For example for something like this to succeed:

```
$ nix-build -E '(import <nixpkgs> {}).runCommand "root" {} "sudo whoami"'
```

Generally I need to introduce some impurities into an expression and I am not sure how to adapt the method we use on NixOS (https://github.com/snabblab/snabblab-nixos/blob/master/modules/sudo-in-builds.nix).

**Comment by edolstra** [comment]
This is not supported. It may have worked previously, but setuid commands like sudo no longer work (see #1429).

**Comment by lukego** [comment]
Thanks for the heads-up @edolstra. This could become a huge headache for me. Snabb has a ~20 server Hydra cluster that is mostly running commands as root under Nix. The commands need root to access special hardware and they are too performance sensitive to run inside a VM (the whole thing is a bare metal performance regression test suite.)

Sounds like we need to stick with Nix pre-1.11.10 indefinitely?

**Comment by edolstra** [comment]
Let's continue this in #1429.

**Comment by masaeedu** [comment]
So assuming I use nix to install something like `tsocks` on my ubuntu system, and now need to execute `tsocks` under sudo, this is not supported?

**Comment by copumpkin** [comment]
No, Nix is a pure build tool and by construction doesn't ever make changes to the system it's running on, and even has mechanisms to actively prevent tools from even seeing the outside world (network, rest of filesystem, other PIDs, etc.)

**Comment by masaeedu** [comment]
@copumpkin Nix may be a pure build tool, but the tools it builds are not. Same for proxychains, tunsocks, tsocks, redsocks, a few dozen other tools I've installed today. I don't understand what the point of having `docker` in nixpkgs is if there's no proper way to run `dockerd`.

I've been hacking around it by `sudo su`-ing and then executing the nix profile from the user I installed nix under, but this seems like a hack that violates how nix expects to be used.

**Comment by copumpkin** [comment]
Nix makes no attempt to manage the _runtime_ of packages it builds, so they do "impure" things all the time, and can run as superuser or do whatever.

All I'm saying is that running something as `sudo` inside a Nix _build_ is unsupported. If you build a program that then runs `sudo` (or needs to be run under) at runtime Nix has no stance (positive or negative) on that. In that sense, Nix is a _build_ tool, sort of like a much fancier `make` or whatever (minus the occasional `make install` targets that perform systemwide side-effects).

The usual approach with something like `dockerd` is that `systemd` or another init system would manage the daemon for you. Nix provides the binaries but your init system takes care of running them with the privileges they need. NixOS manages this automatically for you, but on other distros you need to do that sort of thing yourself.

Another ramification of this design is that if a package's binaries need `setuid`, Nix won't let them do that natively, for security purposes. Again, NixOS manages this stuff automatically for you by maintaining a systemwide privileged list of `setuid` programs, but on other platforms you have to handle that sort of thing for you. It's not always pretty but generally works pretty well for us.

@masaeedu anyway, this discussion will probably be more effective on the https://github.com/NixOS/nixpkgs issue tracker, which covers common packaging needs vs. actual use of the build/management tool in this repo. You might be best served by posting an issue with your question on the tracker over there, since there are a lot more folks monitoring that issue tracker and you'll probably get more help with your specific needs. We also have good IRC channels (#nixos on freenode) and a mailing list (nix-devel) if you prefer that sort of thign.

**Comment by masaeedu** [comment]
@copumpkin Ok, thanks. The issue I'm having is not using using sudo in builds, but rather how to share an env and symlinks setup between different users (specifically my primary user and root). I'll go check out the IRC.

**Comment by copumpkin** [comment]
Cool, sounds good 😄 keep in mind that because the majority of our users are in Europe, IRC is quieter than usual right now. Also, NixCon is happening today so many of the core contributors are also going to be less attentive
