### ISSUE TITLE
[docs][question] What does wantMassQuery do?

### ISSUE THREAD

**Issue by dtzWill** [NixOS/nix#1503]
I can infer from looking through the code, which other than parsing+caching seems to only be used here:

https://github.com/NixOS/nix/blob/561e977f51c1d9ec55e4a70791958d4e214df465/src/libstore/local-store.cc#L832

Which roughly seems to be whether Nix queries large sets of paths at once from the cache or not.  Is that correct?

* Any guidance on when this should/shouldn't be set? Perhaps disable it on caches that only are expected to have a small set of paths? Or on caches that might not put up well with huge number of queries?

* Is there support for more directly querying a cache for its contents without large number of requests? Some sort of manifest/index?

As for manifest/etc making it efficient to update clients without re-downloading manifest would be useful...
downside is this approach would leak what paths exist, but I'm not sure how important that is (does anyone rely on this?).

Anyway, mostly just curious what the official high-level description of this flag does! :innocent:

Thanks!

**Comment by grahamc** [comment]
https://github.com/NixOS/nix/blob/4aee93d5ce6cf77e314e93074b9da1dcff8979e9/tests/binary-cache.sh#L14 WantMassQuery is used when nix-env is passed `-s` (`--status`). Passing `-s` to `nix-env -qas` could result in many 10s of thousands of queries to your binary cache, and maybe you don't want that since you don't actually host a cache of nixpkgs, so it would return almost entirely 404's and be a waste of your resources and the user's time.

**Comment by dtzWill** [comment]
Thanks! I guess at this point that's either the right explanation (no one corrected it) or as good as we'll get.  And it matches what I was inferring although didn't appreciate the "status" comment (and explanation you provided kindly).

Appreciate the explanation, hopefully this helps anyone hosting a nix cache themselves in the future.
