### ISSUE TITLE
Install script should set a desired umask

### ISSUE THREAD

**Issue by dezgeg** [NixOS/nix#1560]
Problem report noticed in IRC: macOS installation failed if `umask` is 077: https://pastebin.com/p1ppRyqM

**Comment by edolstra** [comment]
CC @grahamc

**Comment by Anton-Latukha** [comment]
This is just what I thought about today.
This is what scripts should check or set.
That is why I have a lot of requirement checks.
http://teaching.idallen.com/cst8177/13w/notes/000_script_style.html#umask

**Comment by Anton-Latukha** [comment]
@edolstra 
Until grahamc gets here.

I think Nix doesn't have any requirements of `umask` in single-user, it is understandable. If we get to make installed working for Linux.

Of course `umask 077` breaks multi-user capability.

But it needs to be described by developer, what are file-permission requirements for Nix multi-user.
What is done from users inside `/nix` , and what workers do inside `/nix`.

To do things right `/nix` probably should be owned by a certain group, and access to `/nix` must be regulated by including user/workers there. And that goes right into installer.

That also means: checks and messages must be present, - if installed finds `/nix` already exists.
From my point of view.

I am in Linux installer see, of course that `/nix` is created just for current user. And result of deployment is default group of user.

Information about what happens in `/nix` must be passed from you to the people who make installers.
I am also interested to know.

Regarding permissions, what I found in manual is a piece about daemon:
```shell
$ chgrp nix-users /nix/var/nix/daemon-socket
$ chmod ug=rwx,o= /nix/var/nix/daemon-socket
```

But other requirements are obscure.
Probably, if users that can get access to binaries, they get to use nix-daemon, that runs workers inside `/nix`. Workers and Nix symlink binaries to users HOME. But since links are invoked with checks on permissions of objects they point - to we have question about user access to `/nix` folder to those files.
It needs more clear description or requirements.
Maybe I read less than needed.

**Comment by cahlbin** [comment]
I ran into a similar issue on _macOS_, having system `umask 0007`, multi-user mode installation. The issue was that my non-privileged user could not source `/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh`. Resolved by manually running `sudo chmod -R o+rX /nix/store` post-installation.
