### ISSUE TITLE
Put hydra-eval-jobs into Nix itself

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nix#1564]
Probably with a more neutral name 😄 

I'm trying to replicate its behavior with nix-instantiate so I can integrate similar functionality into another system I already have in place and it's proving to be pretty miserable without just bringing in `hydra-eval-jobs` from Hydra. But unfortunately Hydra claims to not be supported on Darwin, so I can't install the package there.

Ultimately it seems like something producing a giant summary of all .drvs and other metadata (including license!) from a nix repo is something that Nix should be doing. I'm going to cross-post this ticket to the Hydra repo too for visibility.

cc @edolstra

**Comment by bjornfor** [comment]
> Ultimately it seems like something producing a giant summary of all .drvs and other metadata (including license!) from a nix repo is something that Nix should be doing

Absolutely!

**Comment by ocharles** [comment]
https://github.com/ocharles/micro-ci would benefit from this, too.

**Comment by dtzWill** [comment]
:+1:

**Comment by periklis** [comment]
@copumpkin i've started weeks ago to enable hydra for darwin, but actually work stuff got in my way: https://github.com/NixOS/nixpkgs/pull/33985

Hydra eval jobs seems to compile correctly, but the queue-runner makes some trouble. Some tests fail because of [this reason](/NixOS/nixpkgs/pull/33985#issuecomment-358623593). Maybe you have some time to look on this and we can finally have a hydra on darwin at all.

**Comment by tfc** [comment]
I would really like to see this, too. I was just about to duplicate this ticket but then found that @copumpkin had the same idea years ago! 👍 

In addition to the nicer composability with other CIs, it would allow for:

- easier configuration of hydra with patched nix versions that impact evaluation
- i could locally run exactly the same command that hydra would run for me so i can see if my stuff even evaluates
- it would be nicer to configure if my hydra should evaluate expressions with `restrictEval = false/true` and other things.

**Comment by tfc** [comment]
Isn't this something that would also be useful for Hercules CI? @roberth @domenkozar

**Comment by LnL7** [comment]
This was actually done recently in e375da6899a939d5b987eff8a5a85fd083b24849, but removed again later.

**Comment by roberth** [comment]
@tfc Hercules CI aims to behave like `nix-build` rather than Hydra, so it doesn't really have this problem.

@copumpkin's needs can be satisfied with a nix file that traverses attrsets, adding `recurseForDerivations = true`; this can then be built with `nix-build`. Retrieving metadata can be done similarly with some functions and `nix-instantiate --json --strict`. This way, Hydra's specific evaluation behavior can evolve independently of Nix.

I wonder if this issue is going to be relevant after the introduction of flakes.

**Comment by roberth** [comment]
> Hercules CI aims to behave like nix-build rather than Hydra

This has raised questions about `nix-build`'s traversal behavior. `nix-build` does traverse nested attribute sets, but only when those nested sets all have `recurseForDerivations = true;`, which can be added per layer with `lib.recurseIntoDerivations`.
