### ISSUE TITLE
User land nix packages support

### ISSUE THREAD

**Issue by pjotrp** [NixOS/nix#16]
For cluster computing where you don't get root it would be very useful to have nixpkgs in user space. It would be so very useful!

Also, if that facility existed - package managers for languages and browsers could be based on Nix packaging (think Ruby/rvm, Firefox plugins, etc).

**Comment by knedlsepp** [comment]
I just saw the NixCon presentation of @domenkozar, where he talked about the state of python packaging. In the last few minutes he mentioned that even though python packaging is made simpler on `nix`, there is no real movement of pythonistas towars nix [because the `conda` package manager already offers what nix has to offer](https://www.youtube.com/watch?v=ADSM4vR2EQ0#t=2300). In my opinion this is mainly because of exactly this issue. The conda people solve the $HOME installation via [a relative setting of the RUNPATH in libraries](http://conda.pydata.org/docs/building/shared-libraries.html), whereas in `nix` this requires rebuilding everything.

What exactly would be necessary to make this happen?

- [ ] Removing the store prefix from being included in the hashing. (https://github.com/NixOS/nix/issues/166)
- [ ] Making sure no absolute paths to `/nix/...` (in binaries/scripts), but only relative ones make it into the store.

Implementing such a solution would make `nix` so much more versatile. Thus I ask the question again, is the second goal really that unreachable? How do the conda people do it?

**Comment by carlthome** [comment]
This came back up again today when trying to get a peer to try Nix.

Especially for us from the Python ML side, this remains a huge benefit of the Anaconda ecosystem (that you get binaries that "just work" without ever leaving userland). Many also just stick to living with pip inside a long-running Docker container (which unlike Nix, tends to be preinstalled by IT departments) and don't give Nix a try.

Any updates on this since the last post? The user expectation is that curl:ing down the Nix installer should just work on non-root systems (for the running user only) and it would simplify adoption in university/enterprise compute clusters a lot.
