### ISSUE TITLE
Tell user why a given path is live when it can't be deleted

### ISSUE THREAD

**Issue by shlevy** [NixOS/nix#171]
```
$ nix-store --delete  /nix/store/ixmvap0270115iwkz6fljjccghvnf928-nixos-13.10pre34775.a63b4dc
finding garbage collector roots...
error: cannot delete path `/nix/store/ixmvap0270115iwkz6fljjccghvnf928-nixos-13.10pre34775.a63b4dc' since it is still alive
0 store paths deleted, 0.00 MiB freed
```

And

```
$ nix-store -q --roots  /nix/store/ixmvap0270115iwkz6fljjccghvnf928-nixos-13.10pre34775.a63b4dc
/nix/var/nix/profiles/system-53-link`
```

Would be nice if instead the first command output:

```
$ nix-store --delete  /nix/store/ixmvap0270115iwkz6fljjccghvnf928-nixos-13.10pre34775.a63b4dc
finding garbage collector roots...
error: cannot delete path `/nix/store/ixmvap0270115iwkz6fljjccghvnf928-nixos-13.10pre34775.a63b4dc' since it is still alive (reachable from /nix/var/nix/profiles/system-53-link)
0 store paths deleted, 0.00 MiB freed
```

**Comment by jb55** [comment]
:+1: 

I got here by googling "since it is still alive" trying to figure out how to delete something

**Comment by qknight** [comment]
Yes, that would be a **huge usability boost**!

**Comment by nh2** [comment]
@shlevy Issue was just closed but it's not clear to me what the resolution is.

**Comment by shlevy** [comment]
There has been no movement and I'm not interested in pursuing this.

**Comment by nh2** [comment]
@shlevy OK but you don't have to close issues in which you have no more interest, lots of other people continue to have interest, and being the original reporter doesn't put any obligation on you to pursue it, in case this is what you were worried about.

So it would be nice if you could re-open the issues you just closed :)

**Comment by shlevy** [comment]
@nh2 Closing the issue is the only way to remove it from my global github list of issues. Anyone is free to open a new issue with a reference to this one.

**Comment by nh2** [comment]
> Closing the issue is the only way to remove it from my global github list of issues.

@shlevy Well, that's a bummer, I guess then we do have to open a new issue.

It would be nice though if you could post a list of all nix-related issues you closed, as you probably filed a couple of useful ones, so that we can copy those and they don't get forgotten.

Also, just as an aside: I am not sure if your approach of trying to keep your list of issues (I assume you mean [this personalised page](github.com/issues) is a practical/effective one, as owners of the respective issue trackers can re-open issues at will and thus mess with you global issues list. You'd have to post explicitly on each issue that you don't want that. So it seems like Github does not really support the workflow you have in mind.

**Comment by nh2** [comment]
# Reopened issue is at https://github.com/NixOS/nix/issues/1810

Please re-subscribe there whoever is interested in that.
