### ISSUE TITLE
nixUnstable doesn't tab-complete unless a character has been entered

### ISSUE THREAD

**Issue by bgamari** [NixOS/nix#1742]
One of the nice uses of tab-completion in `nix-repl` is to get a sense for which bindings are currently in scope. Unfortunately, it seems that `nix repl` preclude this use since it only tab-completes if at least one character has been entered at the prompt.

**Comment by dtzWill** [comment]
This looks like a functionality regression when switching to linenoise-ng in #1703, relevant source in linenoise-ng:

https://github.com/arangodb/linenoise-ng/blob/4754bee2d8eb3c4511e6ac87cac62255b2011e2f/src/linenoise.cpp#L2589

As mentioned in the comments there, this is an intentional change to facilitate pasting text with leading tabs.

Assuming that's not a use-case we care about, fixing this should be straightforward (removing that check).
