### ISSUE TITLE
Feature freeze for nix 1.12?

### ISSUE THREAD

**Issue by shlevy** [NixOS/nix#1806]
nix 1.12 has been in development for 2 years, and new features (e.g. pure mode) keep getting added with no roadmap or timeline. As a step toward a release, it would be great if we could schedule a point after which no new features would go into 1.12 (instead slated for 1.13) and only fixes, documentation, polish, etc. would be merged in.

**Comment by dtzWill** [comment]
Can you comment on why you closed this?

**Comment by shlevy** [comment]
I'm no longer interested in pursuing this and closing it is the only way to remove it from my list of open issues.

I will note that I have pursued the goal of some kind of timeline for the 1.12 release for a year at least, through several communication channels, and not received any kind of response or even acknowledgment from @edolstra , so I don't recommend any one else to bother, though of course they are free to do so.

**Comment by gilligan** [comment]
Well that *sucks* ;( I was hoping that there was any kind of organization going on between the (few) maintainers of nix.

Is there really no plan or roadmap of any kind *at all*? Considering this is the nix project and not some random joe’s movies catalog bash script I find that somewhat unsettling.

**Comment by grahamc** [comment]
I just want to note that I/we've been doing underlying organizational work in the background for several months on a few fronts. I think we'll be able to get to a better place here soon. It has taken quite some time because in a lot of ways, this sort of work is harder than code changes. I'm hopeful I'll have some good news soon.

**Comment by wmertens** [comment]
@grahamc perfect is the enemy of good - even though it can be very hard to show incomplete work (guilty), it would be good if you can already hint on what you are working on so that we can cheer from the sidelines.

**Comment by grahamc** [comment]
@wmertens unfortunately, in this case I think it would be risky to show incomplete work. However maybe it is a small comfort to know I'm not aiming for perfect 🙃. I'll try not to go more than a week without a further update.

**Comment by grahamc** [comment]
Just a quick note: There has been some cool progress and traction on the organizational work. I'm feeling hopeful. Consider this the further update for the week, and I hope to have more information to share in another week or so.

**Comment by dtzWill** [comment]
Thanks!! This sort of work is hard, very important, and commonly a challenge in open-source projects. Just want to say your efforts are appreciated and let us know how we can best help!

**Comment by grahamc** [comment]
Eelco, Rob, Shea, and I have been talking over the past couple weeks on how to improve Nix’s project organization. More on that quite soon, but here is something definite:

 - Nix 1.12 is now feature-frozen
 - Nix 1.12 will be released as Nix 2.0
 - It will be 2.0 because it removes some functionality which was in 1.11, like nix-push
 - Nix 2.0’s new UI will still be marked "unstable" to allow us to change it, and evolve it based on user feedback.
 - NixOS Unstable will update very soon to use Nix 2.0-pre
 - 18.03 will ship with Nix 2.0

**Comment by dtzWill** [comment]
This is extraordinarily minor but since 2.0 is in our near future thought I'd share a Nixpkgs patch I'm sitting on--maybe someone can apply it as part of setting default to 2.0?

Otherwise warnings are emitted at least once on ever `nix` invocation due to use of obsolete (removed) setting, which is annoying :innocent: .

```
From 1dff8ba74e88f519a835eade0a9ba9172d627f79 Mon Sep 17 00:00:00 2001
From: Will Dietz <w@wdtz.org>
Date: Tue, 30 Jan 2018 15:34:42 -0600
Subject: [PATCH] drop obsolete nix.conf setting "signed-binary-caches"

---
 nixos/modules/services/misc/nix-daemon.nix | 3 ---
 1 file changed, 3 deletions(-)

diff --git a/nixos/modules/services/misc/nix-daemon.nix b/nixos/modules/services/misc/nix-daemon.nix
index beca820d2d6..9036fc18c9c 100644
--- a/nixos/modules/services/misc/nix-daemon.nix
+++ b/nixos/modules/services/misc/nix-daemon.nix
@@ -47,9 +47,6 @@ let
         trusted-binary-caches = ${toString cfg.trustedBinaryCaches}
         binary-cache-public-keys = ${toString cfg.binaryCachePublicKeys}
         auto-optimise-store = ${boolToString cfg.autoOptimiseStore}
-        ${optionalString cfg.requireSignedBinaryCaches ''
-          signed-binary-caches = *
-        ''}
         trusted-users = ${toString cfg.trustedUsers}
         allowed-users = ${toString cfg.allowedUsers}
         $extraOptions
-- 
2.16.1
```

**Comment by edolstra** [comment]
@dtzWill Thanks, https://github.com/NixOS/nixpkgs/commit/700e21d6dac4683ef40f20127a6eb2a74b9bd8c6 does that and bunch of other 2.0 related config changes.

**Comment by mogorman** [comment]
I take it there is no way to get my trivial 2 year old patch in before the freeze

**Comment by grahamc** [comment]
Here is an update: https://github.com/NixOS/rfcs/pull/25

**Comment by copumpkin** [comment]
Sorry about that, @mogorman. Hoping that with more of us keeping an eye on the PR landscape it'll be harder for work like yours to get lost.
