### ISSUE TITLE
nix-repl does not auto-call functions with default values

### ISSUE THREAD

**Issue by ledettwy** [NixOS/nix#1979]
(related to: https://github.com/NixOS/nix/issues/1978)

nix-repl refuses to build the following expression:
```
nix-repl> :b with import <nixpkgs> {}; { arg2 ? null }: runCommand "test" {} ''touch $out;''
error: expression does not evaluation to a derivation, so I can't build it
```

However, nix-build can successfully build that expression. Seems like nix-repl's `:b` is not auto-calling functions with default values for some reason.

nix-repl and nix-build from Nix 2.0

**Comment by regnat** [comment]
That looks like a normal behavior for me: the auto-calling of functions is a convenience for `nix-build`, but there is no need for it on nix-repl as you can simply write

```
nix-repl> :b (with import <nixpkgs> {}; { arg2 ? null }: runCommand "test" {} ''touch $out;'') {}
these derivations will be built:
  /nix/store/ihg4gb0iq94gyfxwkjwfwfxa2xkx3465-test.drv
building '/nix/store/ihg4gb0iq94gyfxwkjwfwfxa2xkx3465-test.drv'...
warning: you did not specify '--add-root'; the result might be removed by the garbage collector
/nix/store/01pshaqnp8861h6mgr4p664jmc1bf24s-test
this derivation produced the following outputs:
  out -> /nix/store/01pshaqnp8861h6mgr4p664jmc1bf24s-test
```

**Comment by shlevy** [comment]
Yes, this is working as designed.

**Comment by copumpkin** [comment]
@ledettwy just to elaborate a bit, I get that the discrepancy might be a bit confusing and welcome suggestions to improve the confusion aspect of it.

At the same time, I think most users don't expect REPLs to do stuff like that, because the REPL has no way of knowing your intent when you ask for a function value. You might for example want to see if something is a function or not, and auto-calling it on your behalf would obscure the truth and be confusing in the other direction. There's some argument for doing some special magic behind the `:b` command but I think that would also be a confusing deviation in behavior from the rest of the REPL.

**Comment by ledettwy** [comment]
Thanks for the feedback and comments everyone. The current behavior makes sense and seems valuable.
