### ISSUE TITLE
linenoise embeds non-free ConvertUTF{.cpp,.h}

### ISSUE THREAD

**Issue by infinity0** [NixOS/nix#2014]
Hi, in the process of Debian packaging this piece of software [we noticed](https://github.com/KaiHa/nix-debian/pull/1#issuecomment-375931810) that the source code of nix includes non-free (and buggy, unmaintained, obsolete) code from Unicode Inc, specifically in the linenoise embedded library.

The solution as suggested by Debian (and adopted by [Ghostscript](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=823100)) is to rewrite the code to use libicu instead.

**Comment by dtzWill** [comment]
Hmm well that's unfortunate.  Following your links (thanks!) I found that many projects include this, to the dismay of Debian packaging teams I'm sure.  One project jumped at me, LLVM:

https://lintian.debian.org/full/pkg-llvm-team@lists.alioth.debian.org.html#llvm-toolchain-6.0_1_x3a6.0~_x2brc2-1

Which is interesting because:
* May be source of fixes / improvements: 
  * https://github.com/llvm-mirror/llvm/blob/master/lib/Support/ConvertUTF.cpp
  * https://github.com/llvm-mirror/llvm/blob/master/lib/Support/ConvertUTFWrapper.cpp
* Perhaps this isn't a deal-breaker for Debian --so the time/resources it takes to resolve this aren't necessarily standing between Debian users and Nix goodness? :)

ICU seems an awfully heavy dependency, I'm not even sure what Nix's official stance on UTF8 is anyway --perhaps removing utf8 support from our REPL is best short-term solution?

**Comment by shlevy** [comment]
:+1: for removing UTF8 support for now. ICU is pretty damn heavy... Maybe some day we can have it enabled optionally at runtime if it's available.

**Comment by dtzWill** [comment]
(Perhaps moving to editline would be worth (re-)considering?)

**Comment by shlevy** [comment]
@dtzWill How hard would it be to quickly remove utf-8 support while we investigate longer-term solutions?

**Comment by edolstra** [comment]
Just revert 21f515724c74d802bb89fdeb9e6dd24ad8497fb7? What was the reason for switching to linenoise-ng anyway?

**Comment by dtzWill** [comment]
It doesn't look very easy to remove.  We could also revert to linenoise (not linenoise-ng) although that'd be unfortunate functionality-wise.

**Comment by dtzWill** [comment]
Since I was curious what it would take / act like, here's a quick port to using editline (no ncurses): https://github.com/dtzWill/nix/tree/feature/editline

Using linenoise-ng was done so that completions were listed instead of only being available one-at-a-time.  See https://github.com/NixOS/nix/pull/1703 .

**Comment by edolstra** [comment]
@dtzWill Switching to editline seems good to me in principle.

**Comment by infinity0** [comment]
The issue was reported to [LLVM upstream](https://bugs.llvm.org/show_bug.cgi?id=32962) and they have it marked as "P release blocker" for nearly a year now, sigh.

editline sounds good to me, removing an embedded library is an extra bonus IMO.

**Comment by dtzWill** [comment]
Reverting to linenoise (no -ng) and picking up the contents of a PR that optionally list completions:

https://github.com/dtzWill/nix/tree/experimental/linenoise-list-all

(I just grabbed the code from the PR, we may wish to merge that with linenoise master for fixes?)

Not sure what is best way to go, but if not editline then modifying linenoise (as in that branch) looks pretty easy--much easier than de-UTF8'ing linenoise-ng.

Hope this helps!

**Comment by shlevy** [comment]
@dtzWill I'd prefer to defer to your technical opinion here, given that we're not OK embedding ConvertUTF. Should we do linenoise or editline? Can you open a PR for whichever?

**Comment by dtzWill** [comment]
Okay! I probably won't be able to get to this for a few days at least, but if that's alright I'll put together a PR for folks to review/test out.

**Comment by cstrahan** [comment]
FWIW, I've opened an issue upstream (and in a fork that looks nice):

* https://github.com/arangodb/linenoise-ng/issues/20
* https://github.com/AmokHuginnsson/replxx/issues/12

**Comment by dtzWill** [comment]
I'm still not sure why using libeditline wasn't the clear winner, haha.  Maybe because I didn't have a good way to vendor it?

Poking at the branch I linked above, seems good to me?
https://github.com/dtzWill/nix/tree/feature/editline

I fear I'm missing something, but for now I'll create a PR for it so we can poke at it and see if it works as we'd like.
