### ISSUE TITLE
Nix allows mixing nested attrpaths and top-level sets... In an order dependent way

### ISSUE THREAD

**Issue by shlevy** [NixOS/nix#2077]
> nix-repl> { x.q = 3; x = { y = 3; z = 3; }; }
> error: attribute 'x' at (string):1:12 already defined at (string):1:3
> 
> nix-repl> { x = { y = 3; z = 3; }; x.q = 3; } 
> { x = { ... }; }

**Comment by shlevy** [comment]
Thanks to @ryantrinkle for finding this.

**Comment by NinjaTrappeur** [comment]
Hey,

I investigated a bit on this problem. It turns out being a bit more complicated than it seems.

Everything boils down to how we determine an attrPaths. As it is, the parser makes the assumption that the path is defined by the left-side part of a binding. So basically, it does not support mixed nested attrpaths.

This problem can lead to the example found by @ryantrinkle, but it can also lead to some more nasty behaviors not throwing any error:

```
nix-repl> { x = { y.y = 1; }; x = { y.z = 2; };  }.x.y   
{ z = 2; }

```

I think this issue is more of a bug than an improvement.

I see two options here:

1. Forbidding altogether mixed nested attrpaths and throwing an error every time we encounter that case.
2. Rewriting the addAttr function in parser.y: we need to extract the paths from e (the Expr) when it's an ExprAttrs and inject them in a AttrPath set.

I am more in favor of solution 2, but it wont come for free performance-wise.

Solution 1 may break some existing nix expression and make some people angry.

What do you think?
