### ISSUE TITLE
Separate trust from caching (feature suggestion)

### ISSUE THREAD

**Issue by Warbo** [NixOS/nix#2122]
Apologies if this has been suggested before (there are a lot of open issues!)

As far as I understand it, Nix currently allows trusted binary caches: these are queried using a derivation's *input* hash (since we don't know the output hash at this point), and the cache gives us a corresponding output/binary. The cache has to be trusted, since we can't verify that the binaries are legitimate (without building them ourselves, which defeats the point of a cache).

It seems to me that we can decouple the trust from the binaries: we don't need to trust the binary provider, as long as we can verify those binaries. Instead, we could query a trusted server with a derivation's input hash, and it could reply with the *output* hash (which, again, we have to trust because we can't verify it cheaply). We can then fetch the binary from any untrusted server, and check its output against the trusted hash.

The particular use-case I had in mind was having the trusted server return the IPFS hashes of the output (potentially among other things, kind of like a metalink or magnet URL), then fetching those hashes from a local IPFS node.

In addition, since a trusted collection of hashes would be reasonably small (compared to all of the associated build products), we could also download all of them at once (similar to Haskell's `cabal update` command). This would let us perform builds offline, or over an intranet, as long as the binaries are pinned on an accessible IPFS node. This functionality wouldn't have to be specific to IPFS though.

**Comment by lheckemann** [comment]
We can already have untrusted binary caches, with the additional benefit that no separate "trusted server" is needed, thanks to nix's support for signing. The `trusted-public-keys` setting is essentially independent of the `substituters` setting.

**Comment by edolstra** [comment]
@Warbo Nix's substitution mechanism works slightly differently from what you describe. It doesn't query derivations, but using output paths (which are listed in the derivation). These output paths are signed as @lheckemann mentioned, so you don't need to trust the distribution server.

However, the model that you describe (a signed mapping from derivations to outputs) will be needed for the intensional / content-addressable store model since there the output path isn't known in advance. That belongs more in #296 though.
