### ISSUE TITLE
General fixupPhase patchShebangs strategy is in conflict with OS X (and BSD flavor) for wrapped interpreter

### ISSUE THREAD

**Issue by wavewave** [NixOS/nix#238]
A stdenv derivation replaces shebang line in shell scripts during `fixupPhase`. Current strategy is that when this meets `#!/usr/bin/env (interpreter command)`, it replaces the whole line with actual command for the interpreter. Therefore, for example, the first line of a python script starting with   

```
#!/usr/bin/env python
```

is changed to

```
#!/nix/store/....-python-2.7.6-wrapper/bin/python
```

This works in linux systems, but does not work on BSD flavored systems   like OS X since they do not allow another shell script to play a role as an interpreter.
A relevant link is here:
http://www.in-ulm.de/~mascheck/various/shebang/#interpreter-script

I suggest to keep `/usr/bin/env` as `/nix/store/...-coreutils-../bin/env` when being replaced by `patchShebangs` during `fixupPhase`

**Comment by imz** [comment]
Is this really the wrong place to post such an issue (I also have one)?

I thought that nixpkgs is for package descriptions (rules to build them), whereas this looks like an issue in the tool that manages the building and installing of packages, namely nix, doesn't it?

Have there been any follow-up messages to your issue report?

**Comment by shlevy** [comment]
@imz `patchShebangs` is part of the standard environment for building packages in nixpkgs, nix itself knows nothing about it.

**Comment by imz** [comment]
@shlevy Ok, thanks for the clarification! I'm just getting to know nix, trying things out.

(And my issue turned out not to be an issue of nix. Strangely, a script installed user-locally under nix failed to run in eshell in Emacs, whereas the same program could run this way when installed as a system package from my distro, and the path from shebang appeared in an error message. Actually, it runs well in a normal terminal, and I remembered that I had a similar issue with building stuff in a kind of sandbox from eshell. -- < https://bugzilla.altlinux.org/show_bug.cgi?id=30673>)
