### ISSUE TITLE
windows staking

### ISSUE THREAD

**Issue by dtlgc** [NixOS/nix#2598]
Nix Windows UI 1.0.1 Staking
I have been staking for several week - transactions show staking but no new nix is put in the wallet.
One transaction listed in my wallet:
 7eccf21f06c9ea2c17b4d8be8d72dd924633f3e9fc7cd13e3b1f5e5946d4ef38

The staking window does not show any transactions being staked. But does show a staking total above the on/off toggle. All of my transactions start with a N letter on the public net.

**Comment by dtlgc** [comment]
Date | Category | Confirmations | Address | Amount
-- | -- | -- | -- | --
2/11/2018 13:06 | stake | 2564 | NZcTNc3Av5kqt6KTUhpAaZPux9hqAqmdPV | 5970.565563
2/11/2018 13:45 | stake | 2545 | NZcTNc3Av5kqt6KTUhpAaZPux9hqAqmdPV | 5965.749438
3/11/2018 7:45 | stake | 2056 | NZcTNc3Av5kqt6KTUhpAaZPux9hqAqmdPV | 5972.974242
3/11/2018 7:53 | stake | 2048 | NZcTNc3Av5kqt6KTUhpAaZPux9hqAqmdPV | 5968.158123
3/11/2018 22:23 | stake | 1641 | NZcTNc3Av5kqt6KTUhpAaZPux9hqAqmdPV | 5970.56709
4/11/2018 1:12 | stake | 1557 | NZcTNc3Av5kqt6KTUhpAaZPux9hqAqmdPV | 5975.383268
4/11/2018 16:30 | stake | 1133 | NZcTNc3Av5kqt6KTUhpAaZPux9hqAqmdPV | 5977.792587
5/11/2018 3:36 | stake | 822 | NZcTNc3Av5kqt6KTUhpAaZPux9hqAqmdPV | 5980.202121
5/11/2018 10:16 | stake | 637 | NZcTNc3Av5kqt6KTUhpAaZPux9hqAqmdPV | 5972.976786
5/11/2018 19:55 | stake | 370 | NZcTNc3Av5kqt6KTUhpAaZPux9hqAqmdPV | 1264.51759

No Stake results are showing in wallet - wallet is encrypted with a password

**Comment by vcunat** [comment]
Seems spammy.

**Comment by dtlgc** [comment]
Why - it is legitimate issue

**Comment by 7c6f434c** [comment]
The reason it seemed spammy is that it is filed against the wrong Nix. This is the Nix package manager repository as stated in README.md (which happens to lack an official GUI, as well as any reasonable Windows support). It doesn't include any cryptocurrency functionality on its own, and cryptocurrency packages in Nixpkgs do not have any special status.

Sorry for misclassifying: your issue is indeed not spam, just in the wrong place.

I am not sure which NIX you use, and whether it is opensource…

**Comment by dtlgc** [comment]
OK - thanks for the reply.

**Comment by vcunat** [comment]
Oh, right, I didn't realize, thanks for figuring out the problem :-)

**Comment by copumpkin** [comment]
For anyone wondering, they were talking about https://nixplatform.io/
