### ISSUE TITLE
error while preallocating on nfs

### ISSUE THREAD

**Issue by xaverdh** [NixOS/nix#2707]
I get the following error message while running `nix run --store $HOME/.nix -f channel:nixpkgs-unstable hello -c hello`:

error: preallocating file of 12044580 bytes: Not supported

I am running a static nix binary compiled from https://github.com/NixOS/nixpkgs/pull/56281, with the setup according to https://matthewbauer.us/blog/static-nix.html.

I think the problem may be that the nfs filesystem in question does not implement posix_fallocate (properly).
But the errno is not what the code at https://github.com/NixOS/nix/blob/44e86304b611a955f4e934fc160f3f4a0a2b1c92/src/libutil/archive.cc#L334 expects.

Is there any chance this can be made more robust?

**Comment by dtzWill** [comment]
To address this sort of thing I've been using this change for quite some time:

98b8c0b3c0f890d6426ae7375e09ea445e200832

I encountered this when using musl (and perhaps NFS as well), and remember it as a known intentional difference in behavior vs. glibc.  This mailing list thread touches on some of this at least:

https://www.openwall.com/lists/musl/2018/04/26/3

**Comment by xaverdh** [comment]
Thanks for the quick reply! I will try that patch.
Any chance that this will get upstreamed?

**Comment by edolstra** [comment]
@dtzWill Thanks, I've applied your patch.
