### ISSUE TITLE
Manual: Explain pros and cons of single and multi user installation

### ISSUE THREAD

**Issue by nomeata** [NixOS/nix#2799]
There are instructions for either single- and multi-user installations in the manual, but no guidance what to pick (besides “however opting in to the multi-user installation is highly recommended”, without explaining why it is recommended.)

I assume that a multi-user installation is needed if there are, well, multiple users on that host. Are there other advantages?

One disadvantage I found is that with the multi-user setup it is harder for nix to use a remote builder that is accessed via the user’s SSH setup (keys, complicated settings in `~.ssh/config`).

Anything else that a new nix user should know before making the decision (which, I assume, can only be fixed by a complete reinstallation, losing all of `/nix/store`)?

**Comment by leira** [comment]
This issue is sitting here for more than 2 years now, and mentioned in 2 discourse threads, yet no one care to explain it.

I checked the blame, this line "however opting in to the multi-user installation is highly recommended" was added by @grahamc in commit [c3e508d](https://github.com/NixOS/nix/commit/c3e508d9245f9439343d88d827c2d7c369ebfc88). Can you please explain why multi-user installation is preferred? What about on macos, where typically there is only a single user?

**Comment by leira** [comment]
@edolstra Thanks for the explanation!

**Comment by ghostbuster91** [comment]
For other people who came here looking for the answer like me, nowadays official documentation covers that topic very well. https://nixos.org/manual/nix/stable/installation/multi-user.html

**Comment by nomeata** [comment]
I guess that's good enough then? Closing this issue.
