### ISSUE TITLE
nix-shell --pure

### ISSUE THREAD

**Issue by CSVdB** [NixOS/nix#2813]
Right now, `nix dev-shell` forms a modern version of `nix-shell --impure`. There is no modernization of `nix-shell --pure` yet though.

**Comment by matthewbauer** [comment]
Nice to see ```dev-shell``` being added!

But I always thought ```--pure``` was a weird feature. Why would you want a pure shell? Doesn't ```nix build``` already provide a pure environment for you? I don't see the use in providing a halfway between ```nix build``` and ```nix dev-shell```.

**Comment by AmineChikhaoui** [comment]
@matthewbauer You can't do development inside `nix build`, so `--pure` is actually useful to make sure you're not inheriting anything from your local environment.

**Comment by matthewbauer** [comment]
I just don't think anyone really wants purity when doing development. Some might think they do, which is why things like Docker are popular. But, there are many good reasons to inherit from the local environment. Things like localizations, timezones, dev tools, and other user configurations need to come from the parent environment to work correctly. Breaking these things in pursuit of "purity" seems like a bad idea. Otherwise, you can always do:

```
env -i nix dev-shell
```

to get the pure environment

**Comment by mkenigs** [comment]
Was looking at this as well as #3107. Instead of passing env vars through an rcfile, would it work to just set all of them before the call to exec or maybe use execvpe instead? Then if pure is desired just clear everything other than exceptions beforehand.

Think this would potentially help #3107 - environment would be set independent of what shell is used, but bashFunctions could be run only in the case of bash.

Would that work/be helpful for me try to PR?

**Comment by CMCDragonkai** [comment]
Is there documentation on dev-shell?

**Comment by edolstra** [comment]
`nix dev-shell` has an option `--ignore-environment` now, so this can be closed.

**Comment by CMCDragonkai** [comment]
Is nix dev-shell deprecating nix-shell?

On 2 February 2020 22:50:53 GMT+11:00, Eelco Dolstra <notifications@github.com> wrote:
>`nix dev-shell` has an option `--ignore-environment` now, so this can
>be closed.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/NixOS/nix/issues/2813#issuecomment-581127760

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by zimbatm** [comment]
@CMCDragonkai this is only touching the flakes branch of nix. Everybody should keep using `nix-shell` until flakes is ready.
