### ISSUE TITLE
Intensional store model

### ISSUE THREAD

**Issue by Mathnerd314** [NixOS/nix#296]
Currently, if any change is made to the build package script, e.g. adding an extra newline in installPhase, then the package and all of its dependencies will be rebuilt because the derivation hash changed. With an intensional store model, only the package will be rebuilt, and the dependencies will remain unchanged, reducing build times.

http://nixos.org/~eelco/pubs/phd-thesis.pdf refers to a "prototype implementation" of the intensional store, which appears to be in https://github.com/NixOS/nix/tree/secure; maybe that could be resurrected and merged?

**Comment by Ericson2314** [comment]
I believe this has some interesting interactions with recursive nix (#13).

First of all, once nix exprs can be developed upstream, it will be even more useful to have an easy way to keep HEAD packages up to date. This implies three phases:
 1. Query repo for master tip, potentially a pre-fetch for other hashs -- non-deterministic.
 2. Download srcs, build dependencies (due to prefetch, packge maybe be downloaded) -- deterministic.
 3. eval and build package nixpr -- deterministic.

The building of intentionally non-deterministic pkgs seems a lot safer with an intrusive store. Whereas most builds would automatically extend the user's trusted build mapping (the one inducing an equivalence set over output paths), intentionally non-deterministic builds such as the repo pre-fetch could create a new mapping which the user could optionally subscribe too.

This makes me wonder if even the actions relating to nix-channels could be conceived of as installing non-deterministic packages.

**Comment by Ericson2314** [comment]
On another note, I don't know about OSTree, but http://ipfs.io/ once it is ready would make a fantastic intentional store for Nix--we could really be its killer app. I mentioned it on IRC, but thought i should here too. [Disclaimer: I am not associated with IPFS in any way, but neither have I tried it. I just read its paper once and immediately thought it perfect for Nix.]

**Comment by CMCDragonkai** [comment]
Just to clarify the intensional model is explained on page 143 of the thesis: http://nixos.org/~eelco/pubs/phd-thesis.pdf

I was wondering why it was called "intensional"?

**Comment by shlevy** [comment]
http://en.wikipedia.org/wiki/Intensional_definition

**Comment by CMCDragonkai** [comment]
I have read that before. Could you elaborate as to how this applies to Nix?

**Comment by shlevy** [comment]
The idea is that the store path name reflects the entirety of the properties of the path by containing a hash of its contents.

**Comment by zimbatm** [comment]
When I started using nix I was confused on why we need to calculate the checksum of git repos since the git sha is relatively unique. Now I know the distinction but if we could store git checkouts by their sha it would be really nice and remove a lot of boilerplate.

**Comment by ehmry** [comment]
A cheap and easy thing to do could be to store each store path at a content addressable hard link, and then make a symlink from the input hash to the hard location. Multiple hard links can be made for different hashing schemes, and multiple input symlinks can point to a single output.

I don't know how complicated it would be to perform the switch after build jobs complete and how costly it would be to dereference a symlink for each package reference by inputs.

**Comment by jbenet** [comment]
the IPFS community would love to help with this! let us know how we can. 

cc @whyrusleeping @lgierth @diasdavid @noffle @davidar

**Comment by Ericson2314** [comment]
@jbenet Glad to here it! The PHD thesis is still probably the best resource on the idea itself. https://github.com/NixOS/nix/issues/378 while superficially not about this at all, I think is actually serves as a good resource on the quirks of the current system, and the usecase where it is most wanting.

I'm not any sort of official nix developer, but happy to answer any questions you may have.

**Comment by vcunat** [comment]
@jbenet: actually, I strongly believe that IPFS has much larger potential of use to nix than the intensional store itself (i.e. forcing the use of hashes from *content* instead of derivations for path references). Let's split that thread to #859.

**Comment by wmertens** [comment]
@ehmry I just had the same idea as you :) https://groups.google.com/forum/#!topic/nix-devel/m8Rrv3VpdBo

The difference is that I propose that the build step gets the CAS entries as inputs, not the input hashes. The input hashes would only be used in case the build product needs to refer to itself.

Obviously, this means that build outputs that need to access themselves will have a different $cas for different input hashes, even if the build output is otherwise the same.

Perhaps builds should be done in `/nix/store/build-$randomstring`, then `build-$randomstring` should be replaced with zeroes before calculating the output hash `$cas`, and then replaced again by `$cas`. The `$cas` will be slightly more work to calculate, but still unique and predictable.

**Comment by ehmry** [comment]
@wmertens Yes, I had considered supporting multiple hashing schemes, but I no longer think that is worth the effort so replacing the input hashes seems practical. I had a system like this running, I don't remember any specific problems with CAS entries but the whole eventually collapsed from making too many changes to Nix.

**Comment by edolstra** [comment]
Some progress on this: https://github.com/edolstra/nix/commit/236e87c687065c2aa935542533b1a65282a73347

**Comment by wmertens** [comment]
@edolstra wonderful! I just read the Intensional Store section of your thesis, I now wish I did that long ago ;)

I see that there is still quite a bit of work to do to get to the Intensional Store you laid out there. One thing that stands out is storing the equivalent hashes (`refClasses`) in the database.

I'm particularly curious about how this will play out with Hydra, how the refClasses will be provided over the network.

It would also be interesting to have a crowd-sourced refClasses database, where many builds by somewhat-trusted users show that a certain input hash leads to some CAS hash.

**Comment by wmertens** [comment]
I just realized that this initial progress is already enough to rewrite the entire store into CAS equivalents with a script: move+link all the outputs to CAS paths and then rewrite all the hash references to their CAS hash.

The `refClasses` "database table" is then simply the set of symlinks that point from original to CAS.

Enough to already play with it :) I'll see if I can cook something up this weekend, but I will be happy if someone beats me to it ;)

**Comment by rrnewton** [comment]
I read the intensional store thesis chapter and I think it will be a big improvement, but at the same time there seems to be a small conflict with strict determinism. The hash rewriting policy (sec 6.3.2), allows the derivation to build with its own temporary output location in its environment, and a random hash is suggested for such a purpose.   But such a random hash puts entropy into that build that it could use to create a different output.

If I'm understanding correctly, the minimum example of recompilation avoidance is something like this:

```
bar-1.2 depends on foo-3.4
foo-3.4 builds to bits XYZ
bar-1.2 builds to bits ABC
```

Then `foo-3.4` receives a trivial tweak (e.g. README file), that changes its derivation hash, but not its output bits (still XYZ).  As a result, `bar-1.2` now has its derivation hash change as well, but we want a rock-solid guarantee that `bar-1.2` need *not* be rebuilt, because it only really depends on bits XYZ, and it would just compute bits ABC once again.

That is, the "from scratch guarantee" (like in any incremental computing) is that the full rebuild would have created the same expected bits *if* it were run.  But that's why visibility of `bar-1.2`'s own output path during the build (either random, or based on its derivation hash) would inject entropy that could break this from-scratch guarantee.

**Simple solution:** Why not just set the output path to a constant?  As long as the `bar-1.2` rebuild only sees a constant output path, plus the (intensional) content-based paths of its dependencies, it should have no way to produce a separate output, assuming proper determinism enforcement (CC @RyanGLScott).

As a variation on that, it could be the determinism-enforcement sandbox itself that simulates a directory-rename of the `$out` path.  That is, there could be some random destination on the real file system, `/nix/store/2c8d367ae0c4...-bar-1.2`, but the build process *thinks* it is mapped simply to `/nix/store/bar-1.2` or something.  (Directory "renaming" via syscall rewriting.)

P.S. The current `nix make-content-addressable` patch linked above seems to use a post-facto mechanism for rewriting pointers from derivation-paths to contents-paths.  But post-facto rewriting would put more paths in the environment that the build *should* treat as opaque to guarantee from-stratch consistency.  (Perhaps this is fine, as its generally an assumption made by Nix: store paths should be treated as opaque symbols, even if that is unenforceable.  But again, some rewriting tricks could guarantee that these bits never make their way into any build process's memory.)

**Comment by siraben** [comment]
Still important to me.

**Comment by tomberek** [comment]
Still important, but perhaps this specific issue can be closed. Seems to be well underway with the CA effort. Well done @regnat !

**Comment by Ericson2314** [comment]
Yes, we do have this now!
