### ISSUE TITLE
nix make-content-addressable is hard to use in scripts

### ISSUE THREAD

**Issue by ocharles** [NixOS/nix#3274]
`nix make-content-addressable` only outputs to STDERR, and even the message that is output is too "human" friendly:

```
$ nix make-content-addressable /nix/store/va53dill0x4lg9cb601qb4f1wi20yi53-Main
rewrote '/nix/store/va53dill0x4lg9cb601qb4f1wi20yi53-Main' to '/nix/store/l4zj62p6gfsivyn4wi9rrvhbrjyxqp8r-Main'
```

I think it would be much better if `nix make-content-addressable` just printed the new store path to STDOUT. This would allow scripting like `FOO=$( nix make-content-addressable ... )`

**Comment by edolstra** [comment]
We should add a `--json` option.

**Comment by ocharles** [comment]
While a bit annoying to have to use `jq` or something to actually get the information I want, I could live with that.

**Comment by zimbatm** [comment]
Or both. Outputting the store path would be consistent with `nix-build` and `nix-instantiate`

**Comment by edolstra** [comment]
The "philosophy" for the `nix` command is to have a `--json` flag for consumption by other programs. I.e. not to write random bits of data to stdout like `nix-build` does (because that's not very extensible, e.g. with `nix make-content-addressable` you probably want to output `input path` -> `CA path` mappings).
