### ISSUE TITLE
nix-build --check doesn't validate hash for fixed-output derivations

### ISSUE THREAD

**Issue by DzmitrySudnik** [NixOS/nix#3369]
Hi,

Looks like nix-build --check (same for nix-store -r --check) doesn't validate hashes correctly for fixed output derivations if outputhash didn't change but the output did. Here is my minimal example:
./test1.nix
```
let
  pkgs = import <nixpkgs> {};
in
pkgs.stdenv.mkDerivation rec {
  name = "testtest";

  outputHashAlgo = "sha256";
  outputHash = "0bllx0p5ppdbhcq3ifddrjmbvdlw53f3brjxdcv2f65n1zira4y2";
  outputHashMode = "recursive";

  phases = "buildPhase";

  buildPhase = ''
    mkdir -p $out

    VERSION=1

    echo "Building $VERSION"

    echo "$VERSION" > text.txt

    cp text.txt $out/
  '';
}
```

The outputHash is correct and if I run `nix-build --check ./test1.nix` it works as expected:
```
nix-build --check  ./test1.nix
checking outputs of '/nix/store/i3hmsf14h0z8fl6b1mdsp8b10cc1vmxf-testtest.drv'...
building
Building 1
warning: rewriting hashes in '/nix/store/jazacw0l5zc0gsfbvqan3q5dhr10xb1n-testtest'; cross fingers
/nix/store/jazacw0l5zc0gsfbvqan3q5dhr10xb1n-testtest
```

However if I change the buildPhase script, like set VERSION=2, `nix-build --check` does build it as expected but succeeds even though the output has changed:
```
nix-build --check  ./test1.nix
checking outputs of '/nix/store/170hzq7hm31gzwswkqpxy070j8ww31dq-testtest.drv'...
building
Building 2
warning: rewriting hashes in '/nix/store/jazacw0l5zc0gsfbvqan3q5dhr10xb1n-testtest'; cross fingers
/nix/store/jazacw0l5zc0gsfbvqan3q5dhr10xb1n-testtest
```

So I think that's by itself is an issue since I believe nix should have failed with hash mismatch since it clearly rebuilt the derivation (see it printed "Bulding 2").

But here even more weird behavior which hopefully can help to investigate the issue. If I spoil the outputHash:
```
let
  pkgs = import <nixpkgs> {};
in
pkgs.stdenv.mkDerivation rec {
  name = "testtest";

  outputHashAlgo = "sha256";
  outputHash = "0bllx0p5ppdbhcq3ifddrjmbvdlw53f3brjxdcv2f65n1zira000";  //  I replaced last 3 characters with 000
  outputHashMode = "recursive";

  phases = "buildPhase";

  buildPhase = ''
    mkdir -p $out

    VERSION=2

    echo "Building $VERSION"

    echo "$VERSION" > text.txt

    cp text.txt $out/
  '';
}
```

`nix-build` fails as expected (can't run it with --check right away):
```
nix-build  ./test1.nix        
these derivations will be built:
  /nix/store/27kwjxw2z7v8k92af5lil428wgsz7y1s-testtest.drv
building '/nix/store/27kwjxw2z7v8k92af5lil428wgsz7y1s-testtest.drv'...
building
Building 2
hash mismatch in fixed-output derivation '/nix/store/76cf68ph3077xndriql3py1yggb3mh0x-testtest':
  wanted: sha256:0bllx0p5ppdbhcq3ifddrjmbvdlw53f3brjxdcv2f65n1zira000
  got:    sha256:1j7i9iipr2b07dp4dd3pq1paf137sywcsz8zqkklf04k92hgrzmi
error: build of '/nix/store/27kwjxw2z7v8k92af5lil428wgsz7y1s-testtest.drv' failed
```
However now, if I change the outputHash back to the original 0bllx0p5ppdbhcq3ifddrjmbvdlw53f3brjxdcv2f65n1zira4y2 (which is still wrong, since I changed VERSION=1 to VERSION=2), `nix-build --check` starts to fail as expected:
```
nix-build --check  ./test1.nix
checking outputs of '/nix/store/170hzq7hm31gzwswkqpxy070j8ww31dq-testtest.drv'...
building
Building 2
warning: rewriting hashes in '/nix/store/jazacw0l5zc0gsfbvqan3q5dhr10xb1n-testtest'; cross fingers
hash mismatch in fixed-output derivation '/nix/store/76cf68ph3077xndriql3py1yggb3mh0x-testtest':
  wanted: sha256:0bllx0p5ppdbhcq3ifddrjmbvdlw53f3brjxdcv2f65n1zira4y2
  got:    sha256:1j7i9iipr2b07dp4dd3pq1paf137sywcsz8zqkklf04k92hgrzmi
error: build of '/nix/store/170hzq7hm31gzwswkqpxy070j8ww31dq-testtest.drv' failed
```

I ran it on macos with nix 2.3.1 in multi-user mode, but also reproduced on linux (multiuser) and mac single user.

**Comment by yaroslav-shcherbyniuk** [comment]
I also reproduced the issue with nix 2.3.3 on macOs.

**Comment by dshkyra** [comment]
Looking on the [`nix-store --realise`](https://nixos.org/releases/nix/latest/manual/#rsec-nix-store-realise) command documentation and the [nix source code](https://github.com/NixOS/nix/blob/2.3.1/src/libstore/build.cc#L3311) I see the following explanation of that behaviour.

I believe that before the first run `nix-build --check ./test1.nix` also `nix-build ./test1.nix` was run, so the derivation output (`/nix/store/jazacw0l5zc0gsfbvqan3q5dhr10xb1n-testtest`) was built and registered as valid.

> nix-store --realise
> * If the store path is a derivation, realisation ensures that the output paths of the derivation are valid (i.e., the output path and its closure exist in the file system).

Then, after changing the derivation output, `nix-build --check ./test1.nix` succeeded as it was able to find the fixed output (`/nix/store/jazacw0l5zc0gsfbvqan3q5dhr10xb1n-testtest`) which corresponds to the `outputHash`. `nix-build --check ./test1.nix` built output (`/nix/store/76cf68ph3077xndriql3py1yggb3mh0x-testtest`) of the changed derivation, however didn't register it as valid. As this output was not built before and was not registered as valid there was no error (from the [nix source code](https://github.com/NixOS/nix/blob/2.3.1/src/libstore/build.cc#L3311) the exception is thrown when the derivation output is valid, i.e. built before).

> nix-store --realise --check
> This option allows you to check whether a derivation is deterministic. It rebuilds the specified derivation and checks whether the result is bitwise-identical with the existing outputs, printing an error if that’s not the case. The outputs of the specified derivation must already exist.

Then, after the change of the `outputHash` to the incorrect one, `nix-build ./test1.nix` was able to find the fixed output, tried to build it and failed because of hash mismatch. Output of the derivation (`/nix/store/76cf68ph3077xndriql3py1yggb3mh0x-testtest`) was registered as valid and it impacted the next runs.

`nix-store --verify-path /nix/store/76cf68ph3077xndriql3py1yggb3mh0x-testtest`

Then, `nix-build --check ./test1.nix` failed with the error because the derivation output was registered as valid and an exception is thrown in that case.

Such behaviour seems reasonable to me, maybe a little counter-intuitive (when a build fails, output is registered as valid impacting the next runs of the same command).

**Comment by DzmitrySudnik** [comment]
Thanks @dshkyra  for the detailed walk through the code. But I still believe that it's a bug. The output of the fixed output derivation is defined by the provided hash, and --check should compare contents of two outputs (so the same paths if we're talking about the fixed output derivation and the provided hash didn't change). The fact that it compares some other paths doesn't make sense for me (/nix/store/jazacw0l5zc0gsfbvqan3q5dhr10xb1n-testtest vs /nix/store/76cf68ph3077xndriql3py1yggb3mh0x-testtest).

**Comment by dshkyra** [comment]
@DzmitrySudnik I agree that from perspective how the `--check` flag works it looks inconsistent - the same check may pass or fail depending on what was built before.

I've put a PR NixOS#3369 to improve that.

**Comment by Artturin** [comment]
https://github.com/NixOS/nix/pull/3432 was closed as no longer necessary
