### ISSUE TITLE
Rename 'nix run'

### ISSUE THREAD

**Issue by edolstra** [NixOS/nix#3524]
`nix run` is a bit of a misnomer since it doesn't actually run the specified package(s), it just starts a shell in which the specified packages are available. By contrast, `nix app` does actually run the specified apps.

So maybe we should rename:

* `nix run` -> `nix shell`
* `nix app` -> `nix run`

**Comment by zimbatm** [comment]
There is also `nix dev-shell` which would be quite similar in naming.

**Comment by zimbatm** [comment]
Also related is `nix print-dev-env` which is similar to `nix dev-shell` except that it outputs the environment variables instead of starting a bash sub-shell.

**Comment by samueldr** [comment]
Could it be `nix app-shell`?

**Comment by emilazy** [comment]
I'd really appreciate something shorter than `nix app-shell`; it's the most common Nix command I run.

**Comment by FRidh** [comment]
> Also related is `nix print-dev-env` which is similar to `nix dev-shell` except that it outputs the environment variables instead of starting a bash sub-shell.

How is that supposed to function in case of structured attrs? If if's done by using `.attrs.sh` it won't be very future-proof.

> I'd really appreciate something shorter than `nix app-shell`; it's the most common `nix(1)` command I run.

Auto-completion?

**Comment by emilazy** [comment]
Auto-completion wouldn't work if there are any other commands starting with `app`, and isn't readily available in other environments like editing shell scripts.

The current name for this is `shell`, which is fine in terms of length, although I personally find `shell` a suboptimal name for this command because it only defaults to starting a shell; I often use it with `-c` to get packages in scope for a single comand. My preference would be something like `with`: `nix with nixpkgs#hello` gets you a shell *with* hello, `nix with nixpkgs#python38 -c python ...` runs a Python script *with* a specific version of Python, and so on.

`nix-shell` already has awkward naming when it's used for non-shell-like things like running third-party build systems (e.g. `nix-shell --run 'cargo build'`), or as the interpreter for scripts, etc.; `nix shell` feels a bit like it's going down the same path.

**Comment by matthewbauer** [comment]
Agree with `nix shell` not being ideal. Since we aren't running hooks, lots of things work differently than in nix-shell:

```
$ nix run nixpkgs.pkgconfig nixpkgs.nix -c pkg-config --libs nix-main
No package 'nix' found
```

vs.

```
$ nix-shell -p pkgconfig nix --run 'pkg-config --libs nix-main'
-L/nix/store/pb9l6ahzjjgllibzp2bfq18m4013kaah-nix-2.3.5/lib -lnixmain
```

**Comment by zimbatm** [comment]
`nix shell` should really be `nix env` since it's about creating a new environment (ignoring the potential confusion with `nix-env`).

**Comment by fluffynukeit** [comment]
I understand this issue is closed, but I wanted to add my experience to the discussion.  As of now, my nix command set includes `run`, `develop`, and `shell`.  I'm very happy with the effort to disentangle the isolated shell environments function of `nix-shell` into `nix shell` from the derivation debugging function of `nix-shell` into `nix develop`.  

What I find very confusing about `nix shell` is that I cannot use it with a `mkShell` derivation target, and instead get the "this derivation is not meant to be built" warning.  But, what is more, when I run `nix shell` with a `mkDerivation` target, the `shellHook` of the derivation is not executed.  So I'm running `nix shell` but the `shellHook` is not running.

However, `nix develop` can be used with `mkShell` without the "not meant to be built warning," and likewise I can use the `mkDerivation` target with a `shellHook` and see the `shellHook` get executed.  I thus have to use `nix develop` to run the shell hooks that `nix shell` doesn't run.  But I'm not trying to do a nix derivation development task or any development task for that matter, so I don't want what `nix develop` says it provides in `run a bash shell that provides the build environment of a derivation.`  I certainly would *not* expect it to run `shellHooks` like it does.  I expect `nix shell` to do that.  I'm just trying to get a shell environment with some packages available and hooks sourced using flakes, like `nix-shell` used to do.

This was a frustrating discovery, so I agree with @emilazy  and @zimbatm that `nix shell` is poorly named given the above, but only because it doesn't do what `nix-shell` used to do regarding `shellHooks`.  In fact, given how much has been written already about `nix-shell` and how many derivations already provide `shellHook`s, I think keeping it as `nix shell` and ensuring it does what `nix-shell` did is the only sensible option.  It's pretty much analogous to `$SHELL -c "echo hi"`.

**Comment by bew** [comment]
@fluffynukeit check https://github.com/NixOS/nix/issues/4715 for discussion / bikesheding around the naming of `nix shell`

**Comment by FRidh** [comment]
@fluffynukeit support for `shellHook` was added in https://github.com/NixOS/nix/commit/e81d38c02b267eea93a91de3e8a00b185355d681, without really being clear on what their purpose is. Is it to be expected that they are executed when developing on a derivation (that's what `nix develop` and `nix-shell`) do, or is it meant for some post action when creating an environment with tools? Given `nix-shell` does not support the latter (though it is often used for that), it clearly means the `shellHook` is for when developing on a derivation, which `nix develop` is for.

Probably clearest would be to have two different run-time hooks, `devHook` and `shellHook`, however, changing the purpose of `shellHook` will annoy people as well.

**Comment by fluffynukeit** [comment]
@bew, thanks for the pointer.  I'll review and join there if I can add to the discussion.

@FRidh I don't think that line of reasoning holds up.  `nix-shell` does support creating an environment with tools because it can be used as a shebang to execute a script in a particular environment.  And, even if it's not "officially" supported, using it as a declarative execution environment for non-nix purposes is such a prevalent use case that I don't think it can be confidently claimed that `shellHook`'s purpose is only for developing on a derivation.  It's really for whatever the shellHook writer intended, which is why I think it's a regression to only include that functionality in `nix develop`.  But, even if the historical consensus is that `shellHook` is indeed meant for developing a derivation, a nix neophyte should not be expected to understand the development history of nix in order to make sense of the command and hook names.  `nix shell` -> `shellHook` is about as intuitive as I can imagine.

You do make a fair point that the shellHook writer might have intended them to be used during derivation development and not for a declarative shell environment, so I'd amend my earlier opinion and instead claim that both `nix shell` and `nix develop` should execute shellHooks because they are both forms of subshells and we can't know the intended use case for any particular shellHook.  We'd have to rely on the user to choose their derivations for each invocation appropriately.
