### ISSUE TITLE
builtins.fetchTarball does not attempt to substitute the desired path

### ISSUE THREAD

**Issue by Gabriel439** [NixOS/nix#3543]
The motivation for this issue is that our company uses `builtins.fetchTarball` with an expected hash to pin the `nixpkgs` that we use for our `NIX_PATH`, but this approach to pinning `nixpkgs` does not work well in restricted network environments.  Specifically, we're trying to get this to work in an environment that does have access to a remote cache, but does not have access to GitHub.

The problem is that `builtins.fetchTarball` does not use binary substitution to fetch the desired path if the path is not already present in the `/nix/store`.  In other words, there are only two ways the `builtins.fetchTarball` utility works:

* The desired path is added to the `/nix/store` by other means

  e.g. `nix-store --realise`, `nix copy`, or `nix-store --import`

* The machine has network access to the URL to fetch

So far, the work-around we've settled upon is to explicitly fetch the paths from our cache out-of-band using `nix-store --realise /nix/store/…-source`.  However that creates a new chicken-and-egg problem:

* We can't automatically determine which paths to fetch until `builtins.fetchTarball` suceeds
* `builtins.fetchTarball` doesn't succeed until the paths are in the `/nix/store`
* We can't add the paths to the `/nix/store` until we know which paths to fetch

... so currently we have to hardcode the paths to fetch, which is brittle.

Note that we only verified this problem on an older version of Nix, specifically version 2.0 (179b896acb6deb8fea9614dfbddeaf3b23797bf5), but I checked the relevant code and this issue still appears to not be resolved on `master`.

**Comment by matthewbauer** [comment]
Similarly, "hashedMirrors" is not checked when using fetchTarball, while it is with fetchurl (https://github.com/NixOS/nix/blob/74f94d6640b23d04e6a46a2d0851db6393eebfd6/src/libstore/builtins/fetchurl.cc#L61).

I think there's a slight complication with substitutions via builtins.fetchTarball due to all of the new fetchers (fetchTarball, __fetchurl, fetchGit) not being derivations like pkgs.fetchurl, pkgs.fetchzip, and pkgs.fetchgit are. fetchTarball results end up getting placed in $HOME/.cache/nix/tarballs. Still, I think it's reasonable to expect your binary cache or remote builder to be able to substitute these tarballs for you.

**Comment by PkmX** [comment]
This sounds like #2114.

**Comment by Gabriel439** [comment]
You're right, this is the exact same issue as #2114, so I'll close in favor of that issue, then
