### ISSUE TITLE
builtins.path fails if file disappears even if excluded by filter

### ISSUE THREAD

**Issue by jakubgs** [NixOS/nix#3593]
**Describe the bug**

I have tasks running in parallel in my CI that create a `tmp.*` folder in my repo root with `mktemp`.
This causes some derivations that get files from repo root with `builtins.path` to fail with:
```
getting status of '/xyz/project/tmp.z3UnuiKhhf': No such file or directory
```
Because the file exists when `builtins.path` is invoked but is removed before it finishes.
This happens event though my specified `filter` function excludes that folder.

**Steps To Reproduce**

Create a `default.nix`:
```nix
builtins.path {
  name = "builtins-path-test";
  path = ./.;
  filter = path: type:
    (builtins.genList (x: x*100000) 10000000) == 1;
}
```
The `genList` there is to make it slower.
Then try to create a file and delete it when `nix-instantiate` is running:
```
 $ { touch test; nix-instantiate --eval &; { sleep 0.1; rm test } & }
[2] 31599
[3] 31600

[3]  + done       { sleep 0.1; rm test; }
error: getting status of '/tmp/nix-builtinspath-test/test': No such file or directory

[2]  + exit 1     nix-instantiate --eval
```

**Expected behavior**

I'd expect it to not try to get a status of a file that is excluded by the filter.

**`nix-env --version` output**
```
nix-env (Nix) 2.3.4
```

**Comment by domenkozar** [comment]
Maybe @shlevy has an idea here :)

**Comment by shlevy** [comment]
This happens because [readDirectory](https://github.com/NixOS/nix/blob/546b179d0a89e9f27a02e92004da0f8f08e5041a/src/libutil/util.cc#L271-L292) reads all the dirents at once, but the [PathFilter](https://github.com/NixOS/nix/blob/546b179d0a89e9f27a02e92004da0f8f08e5041a/src/libutil/util.hh#L564) interface only takes a `Path` (it could instead take a [DirEntry](https://github.com/NixOS/nix/blob/546b179d0a89e9f27a02e92004da0f8f08e5041a/src/libutil/util.hh#L89) plus a root path), so we have to [stat](https://github.com/NixOS/nix/blob/546b179d0a89e9f27a02e92004da0f8f08e5041a/src/libexpr/primops.cc#L1048) the file again in order to provide the `type` argument to the function.

**Comment by jakubgs** [comment]
Thanks for taking a look. I don't think it's that important, at least not to me, since I can work around it by moving the `tmp.*` folders outside of the repo root. But I think it's important to document this issue for anyone that might encounter it and become as confused as I was. I spent like an hour debugging my filtering function only to realize it wasn't the issue at all.

**Comment by jakubgs** [comment]
This is kind of an edge case, and might not be worth putting the effort to fix it right now.

It's important that it's documented by this issue tho. I'll close it for now.
