### ISSUE TITLE
Segmentation fault when adding `nixpkgs-overlays` to `NIX_PATH`

### ISSUE THREAD

**Issue by evanrelf** [NixOS/nix#3780]
**Describe the bug**

I get a segmentation fault when adding `nixpkgs-overlays` to `NIX_PATH`. I'm not sure _why_ that causes it, and I don't think my guesses would be useful.

**Steps To Reproduce**

I've created a minimal reproduction of the issue here: https://github.com/evanrelf/nix-segfault-reproduction

**Expected behavior**

Evaluation doesn't infinitely loop, or I get an error about infinite recursion.

**`nix-env --version` output**

```
nix-env (Nix) 2.3.6
```

**Additional context**

See the repo I mentioned above ([link](https://github.com/evanrelf/nix-segfault-reproduction)).

**Comment by FRidh** [comment]
The value of `nixpkgs-overlays` should be a directory with overlays, or an overlay itself. In your case it's the file `overlays/default.nix` which is supposed to be an overlay, but is not. Then, that file imports `import-directory-attrs.nix`, which imports `nixpkgs` again, without setting overlays to en empty list! That is clearly an infinite recursion, because during that import it will want to load your "overlay" again.

**Comment by FRidh** [comment]
It's essentially the same as https://github.com/NixOS/nix/issues/3772.

**Comment by evanrelf** [comment]
> The value of `nixpkgs-overlays` should be a directory with overlays, or an overlay itself. In your case it's the file `overlays/default.nix` which is supposed to be an overlay, but is not.

When providing a file to the `overlays` argument, Nixpkgs will consider that file's expression as the _list_ of overlays, not a single overlay itself ([source](https://github.com/NixOS/nixpkgs/blob/c27e54de99df793756a5314f8fd5dd3e49d31927/pkgs/top-level/impure.nix#L56-L57)), so I believe I'm using it correctly.

That said, I think you're right that I'm inducing infinite recursion since `import-directory-attrs.nix` imports Nixpkgs on its own, which would be a duplicate of #3772.

I was able to solve the issue by configuring Nixpkgs with `overlays = [];` explicitly in `import-directory-attrs.nix`.
