### ISSUE TITLE
preferLocalBuild should not override max-jobs=0

### ISSUE THREAD

**Issue by grahamc** [NixOS/nix#3810]
**Is your feature request related to a problem? Please describe.**

The documented behavior of `max-jobs` defines that even with a value of 0, builds with `preferLocalBuild = true` still build locally. This is a fairly major policy decision that the daemon makes on behalf of the user, and is a decision the user cannot easily override.

Sometimes a machine should perform _absolutely_ no builds, in which case their options to fully disabling builds is to either delete all the build users (not sure nix-daemon would be happy with this) or set the `system` to a bogus value and assume/hope nobody will use it.

**Describe the solution you'd like**

I propose we extend the `features` feature of remote building to local building, too, and use preferLocalBuild as a listed feature.

Concretely, I want to:

1. extend the `nix.conf` to accept a `mandatory-features` option
2. treat derivations where `preferLocalBuild == true` as if they had the "local-preferred" feature
3. add `local-preferred` to the default value of `system-features`

**Backwards Compatibility**

* The current behavior of `max-jobs=0` can be achieved by setting `mandatory-features = local-preferred` and `max-jobs=auto`. 
* Other users may want to set `max-jobs=0` and assign the `local-preferred` feature to a specific builder which is nearby.

**Comment by Ericson2314** [comment]
I would be fine just changing the behavior of `max-jobs = 0`, but the desugaring to `local-preferred` is neat and I like it :)

> This is a fairly major policy decision that the daemon makes on behalf of the user, and is a decision the user cannot easily override.

To be clear, is this a daemon thing in particular? What happens if one is not using the daemon, but has remove builders?

**Comment by grahamc** [comment]
> To be clear, is this a daemon thing in particular? What happens if one is not using the daemon, but has remove builders?

Same behavior :).

**Comment by Ericson2314** [comment]
OK whew. That would have made back-compat much more tricky.

**Comment by domenkozar** [comment]
The reason the user might be using remote builder / binary cache is to avoid HDD space pollution and there's no way to disable that.

**Comment by zupo** [comment]
I'm one of those Nix beginners that was just bitten hard by `preferLocalBuild` overriding max-jobs=0. My colleague and I started the day with a simple task: add https://nixbuild.net/ to our 500+ tiny VPSes hosting 70k websites so that when we run `nixos-rebuild switch`, their memory, CPU and disk don't get completely overused. 

So we followed https://docs.nixbuild.net/getting-started/ and `nix-build`ing the example in that docs worked fined. But for the life of me, we couldn't get `nixos-rebuild switch` to use remote builders. We tried setting `--max-jobs 0` but the thing would keep on building (locally).

After 6 hours, I gave up, and because I'm born under a lucky star I have @domenkozar on speed dial, so I called him up and he cleared up what's going on. I can imagine that if I couldn't randomly call an experienced NixOS person, I'd probably give it another day, and then after wasting 30+ engineering hours, give up.

**Comment by NorfairKing** [comment]
I've been burnt by this in the past as well.
It would be nice if there was a clear way to say "build _all_ of this remotely".

**Comment by domenkozar** [comment]
I wonder however what does `prefer` imply in `preferLocalBuild`? I would expect that in case of `--max-jobs=0` that would mean it no longer prefers the local build. In what scenarios does it prefer the local build even?

**Comment by rickynils** [comment]
I've implemented the simple resolution of this issue in https://github.com/NixOS/nix/pull/4443. It doesn't introduce the system features suggested by @grahamc, but instead makes `max-jobs=0` **not** allow remote building of derivations with `preferLocalBuild = true`.
