### ISSUE TITLE
What does nix registry pin do?

### ISSUE THREAD

**Issue by Mic92** [NixOS/nix#3871]
**Describe the bug**

I am currently trying to write some examples for it at https://nixos.wiki/wiki/Nix_command/registry_pin
However it's not clear to me where the pinning goes and how I can inspect it.
I see that nix downloads my flake when I do this

```
$ nix registry pin templates
```

**Comment by B4dM4n** [comment]
As far as I can tell all `nix registry` commands, except `list`, only operate on the user flake registry which is stored in `$HOME/.config/nix/registry.json`.

They allow to add new or override system wide registry entries. The `pin` command is used to take a system wide or global flake entry and add it to the user registry with the version pinned to the current version of that flake.

To undo a `nix registry pin` the entry that was created in the user flake registry needs to be removed, so the system wide or global entry will be used again.

If a specific version instead of the latest available one is desired the `add` command has to be used instead.

**Examples:**
```shell
% nix registry list
global flake:blender-bin github:edolstra/nix-warez
…
global flake:nix github:NixOS/nix
…

% nix registry pin nix

% nix registry list
user   flake:nix github:NixOS/nix/ed52cf632bf9db90311014600ca0f042ef57ca20
global flake:blender-bin github:edolstra/nix-warez
…
global flake:nix github:NixOS/nix
…

% nix registry add nix github:NixOS/nix/cdc23866444b1ef863f917ec0adaaa9bec31126b

% nix flake info nix
Resolved URL:  github:NixOS/nix/cdc23866444b1ef863f917ec0adaaa9bec31126b
Locked URL:    github:NixOS/nix/cdc23866444b1ef863f917ec0adaaa9bec31126b
Description:   The purely functional package manager
Path:          /nix/store/94bmpb9nzxy7ngz6668ncy6vlck26i28-source
Revision:      cdc23866444b1ef863f917ec0adaaa9bec31126b
Last modified: 2020-07-30 23:40:40

% nix registry remove nix

% nix registry list
global flake:blender-bin github:edolstra/nix-warez
…
global flake:nix github:NixOS/nix
…

%  nix flake info nix
Resolved URL:  github:NixOS/nix
Locked URL:    github:NixOS/nix/ed52cf632bf9db90311014600ca0f042ef57ca20
Description:   The purely functional package manager
Path:          /nix/store/fj0a88q98zjc5kgz2pd5gaqdgkj4dj4v-source
Revision:      ed52cf632bf9db90311014600ca0f042ef57ca20
Last modified: 2020-08-04 10:44:47
```

**Note:**
In the `nixUnstable` version currently shipped by [nixpkgs](https://github.com/NixOS/nixpkgs/blob/85819d4bbf71c3f067234969e58248687fbfad88/pkgs/tools/package-management/nix/default.nix#L197) (ff314f186e3f91d87af6ad96c0ae3b472494b940) the `nix registry pin` command is bugged and essentially a noop. This was fixed in #3854.

**Comment by Mic92** [comment]
Thanks!

**Comment by Mic92** [comment]
There you go: https://nixos.wiki/wiki/Nix_command/registry_pin#Examples
