### ISSUE TITLE
`nix run` should call a flake package by it's pname

### ISSUE THREAD

**Issue by nrdxp** [NixOS/nix#4422]
contenxt numtide/flake-utils#17

When absent an `app` declaration, a binary in `packages` should be called by `"$out/bin/${pname}"`. Currently [this](https://github.com/nrdxp/nixflk/blob/b7016c8d92a132c2e4d63861ac0357bc9f994a3a/pkgs/misc/drivers/wii-u-gc-adapter/default.nix) fails with `nix run` by attempting to call the binary: `"$out/bin/${pname}-{version}"`.

**Comment by zimbatm** [comment]
The issue is that when it parses the name, it's not able to make out the version number:
```
nix-repl> builtins.parseDrvName "wii-u-gc-adapter-ae6b46d"
{ name = "wii-u-gc-adapter-ae6b46d"; version = ""; }
```
The version has to start with a number, that's why you often see an ISO date in nixpkgs for unstable versions.
```
nix-repl> builtins.parseDrvName "wii-u-gc-adapter-2021-01-01ae6b46d" 
{ name = "wii-u-gc-adapter"; version = "2021-01-01ae6b46d"; }
```

Here is where the conversation from derivation to app is happening:
https://github.com/NixOS/nix/blob/8a2ce0f455da32bc20978e68c0aad9efb4560abc/src/nix/app.cc#L38

**Comment by edolstra** [comment]
Right, the issue in https://github.com/nrdxp/nixflk/blob/b7016c8d92a132c2e4d63861ac0357bc9f994a3a/pkgs/misc/drivers/wii-u-gc-adapter/default.nix is using a Git commit hash as a version, which is not supported by Nix (but unfortunately not checked by `stdenv.mkDerivation`).
