### ISSUE TITLE
Write Nix 2.4 release notes

### ISSUE THREAD

**Issue by edolstra** [NixOS/nix#4521]

**Comment by asymmetric** [comment]
@edolstra in order to start working on this, we should decide what the scope of 2.4 is. Does the 2.4 [milestone](https://github.com/NixOS/nix/milestone/11) reflect your current view of 2.4's scope?

If so, can we freeze it? It's difficult to start documenting parts when e.g. option names are still in flux.

**Comment by ldesgoui** [comment]
I'm going to attempt to get the set of PRs merged in the range `2.3-maintenance..master`, filter out the ones that were backported (which should show up in the range `master..2.3-maintenance`), and then categorize
