### ISSUE TITLE
API rate limited when updating flakes

### ISSUE THREAD

**Issue by 06kellyjac** [NixOS/nix#4653]
**Describe the bug**

I'm getting API rate limited when updating my flakes. Is there a way to pass an API token to nix currently?

```
error: unable to download 'https://api.github.com/repos/chriskempson/base16-vim/commits/HEAD': HTTP error 403 ('')

       response body:

       {"message":"API rate limit exceeded for 82.15.117.246. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"}
```

Related #2849 (?)

**Steps To Reproduce**

1. `nix flake update`

**Expected behavior**

I'd like to update my flake deps and avoid the API rate limit either with a token or some other method

**`nix-env --version` output**

`nix-env (Nix) 2.4pre20210308_1c0e3e4`

**Additional context**

**Comment by edolstra** [comment]
Yes, see `access-tokens` in `nix.conf`.

**Comment by 06kellyjac** [comment]
https://nixos.org/manual/nix/unstable/command-ref/conf-file.html

Awesome, thanks!

**Comment by piperswe** [comment]
> Yes, see `access-tokens` in `nix.conf`.

Is there a way to make Nix refer to an external file? I configure my `nix.conf` with NixOS, so I don't want to put secrets in my NixOS configuration.

**Comment by grahamc** [comment]
Yeah, I forget the syntax but the docs for the nix.conf present a way to
include a file. @ I think?

On November 10, 2021, GitHub ***@***.***> wrote:
> > Yes, see access-tokens in nix.conf.
> >
>
> Is there a way to make Nix refer to an external file? I configure my
> nix.conf with NixOS, so I don't want to put secrets in my NixOS
> configuration.
>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/NixOS/nix/issues/4653#issuecomment-965820597>, or
unsubscribe <https://github.com/notifications/unsubscribe-
auth/AAASXLGB4ZO7DM5EGHBTWRDULL2O7ANCNFSM4ZNNESJQ>.
Triage notifications on the go with GitHub Mobile for iOS
<https://apps.apple.com/app/apple-store/id1477376905?ct=notification-
email&mt=8&pt=524675> or Android
<https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-
email%26utm_medium%3Demail%26utm_source%3Dgithub>.

**Comment by cole-h** [comment]
From the docs linked above:

> The configuration files consist of `name = value` pairs, one per line. Other files can be included with a line like `include path`, where path is interpreted relative to the current conf file and a missing file is an error unless `!include` is used instead.

**Comment by arynh** [comment]
If you have the [github cli](https://search.nixos.org/packages?channel=unstable&show=gh&from=0&size=50&sort=relevance&type=packages&query=gh) and are logged in, you can generate a token using that:

```bash
nix flake update --option access-tokens "github.com=$(gh auth token)"
```

to wrap it into a one-liner

**Comment by gberche-orange** [comment]
@arynh 

> If you have the [github cli](https://search.nixos.org/packages?channel=unstable&show=gh&from=0&size=50&sort=relevance&type=packages&query=gh) and are logged in, you can generate a token using that:
> 
> nix flake update --option access-tokens "github.com=$(gh auth token)"
> 
> to wrap it into a one-liner

[`gh auth token`](https://cli.github.com/manual/gh_auth_token) prints out the current token used by a user. Typically, users would give permissions to this token to act on their repo and possibly packages and other github resources. This is dangerous since a corrupted nix installation could leverage this token to act on behalf of the user. Since public nix packages don't require permissions to get accessed, it seems safer to generate a dedicated personal access token without any granted scope from https://github.com/settings/tokens/new which would be sufficient to get beyond api rate limits

see https://docs.github.com/en/rest/using-the-rest-api/rate-limits-for-the-rest-api?apiVersion=2022-11-28#primary-rate-limit-for-unauthenticated-users

> You can make unauthenticated requests if you are only fetching public data. Unauthenticated requests are associated with the originating IP address, not with the user or application that made the request.
> 
> The primary rate limit for unauthenticated requests is 60 requests per hour.
> 
> You can use a personal access token to make API requests. 
> All of these requests count towards your personal rate limit of 5,000 requests per hour.  ...

**Comment by Malix-Labs** [comment]
> `nix flake update --option access-tokens "github.com=$(gh auth token)"`

For nushell :
`nix flake update --option access-tokens $"github.com=(gh auth token)"`
