### ISSUE TITLE
Build sandbox seems broken on macOS 11 Big Sur

### ISSUE THREAD

**Issue by emilazy** [NixOS/nix#4658]
**Describe the bug**

I get the error `error: getting attributes of path '/usr/lib/libSystem.B.dylib: No such file or directory` when attempting to run builds with the sandbox enabled on Big Sur.

**Steps to reproduce**
Set `sandbox` to `true` or `relaxed` and try to build anything.

**Comment by lilyball** [comment]
I'm hitting this too.

It looks like the issue is nixpkgs puts `/usr/lib/libSystem.B.dylib` into `stdenv.__extraImpureHostDeps`, which means it ends up in the `__impureHostDeps` of every derivation produced using the stdenv.

And then Nix itself, if `useChroot` is on (which it is by default for any pure derivation while the sandbox is enabled), takes the set of `__impureHostDeps`, verifies that they belong to the set of allowed paths, and adds them to `dirsInChroot`. And then, at least for darwin, for every entry in `dirsInChroot`, it either must exist or it must be marked optional. If it doesn't exist and isn't optional, it produces this error.

This only happens on Big Sur because Big Sur removed `/usr/lib/libSystem.B.dylib` as it's part of the shared dylib cache (and Big Sur removed the library duplicates on disk).

Fundamentally, the issue is that when Nix adds `__impureHostDeps` to `dirsInChroot` it doesn't mark them optional. It probably should, as I don't see any reason why the set of `__impureHostDeps` should be assumed to actually exist on disk.

**Comment by lilyball** [comment]
@edolstra It would be really great to have this resolved. `sandbox = relaxed` finally started working reliably not that long ago, with all of the fixes to the default sandbox paths, and I'd love to keep using it, but I don't see any way for me to hack my Nix setup to remove `/usr/lib/libSystem.B.dylib` (or mark it as optional) without rebuilding the entire world.

**Comment by emilazy** [comment]
I’ve opened #4761 with a fix to this, but I’m not actually sure nixpkgs needs to keep `/usr/lib/libSystem.B.dylib` in the impure paths. Presumably the toolchain uses the dyld cache in general now, so maybe that line could just be removed? Maybe it’d be a good idea to file an issue with nixpkgs to figure out if we need to patch Nix here; it’d be nice to not require a bleeding-edge Nix to use sandboxing.

**Comment by emilazy** [comment]
(Thanks to @lilyball for tracking down exactly what’s going on here!)
