### ISSUE TITLE
What about enhancing toFile?

### ISSUE THREAD

**Issue by MarcWeber** [NixOS/nix#473]
nixpkgs writeTextFile fails on such large files (happens with my httpd.conf file), toFile is not an alternative yet due to
error: in ‘toFile’: the file ‘abc’ cannot refer to derivation outputs, at "/tmp/x.nix":8:32

```
# this file tries to write a 400k file appending the store
# path of gnused. 400k is fine, appending gnused not.
# 
# Reason for this test case: I run into a problem that my apache configuration file got too large.
let pkgs = import <nixpkgs> {};
    repeat= n: s: if n == 0 then "" else s + repeat (builtins.sub n 1) s;
    s = repeat 400 (repeat 1024 "x");
in pkgs.runCommand "x" {file = builtins.toFile "abc" (s + "${pkgs.gnused}");} "mv $file $out"
```

I create this pull request to get guidance from the master about which would be the best fix, eg improve toFile, or use another solution?

The main problem is that echo "$FOO" > $out/$PATH in writeTextFile fails for large files. like the one in this test case. There are many ways to fix, eg bash allows splitting strings as well. Thus what is what you would consider to be a "real fix" in this case? Rewrite writeTextFile or improve builtins.toFile or something else?

**Comment by bennofs** [comment]
If you choose to rewrite `writeTextFile`, there is no need to use bash string splitting magic, I heredoc should work as well:

```bash
cat > << EOF
$text
EOF
```
I wonder whether passing `$text` via the environment could also become an issue? In that case, you could just use `${text}` (but you'd need to use `<<'EOF'` instead of `<<EOF` to get the escaping rules right)

**Comment by MarcWeber** [comment]
Nice idea, but fails with the same error: http://dpaste.com/15R3T2B (argument list too long) copy paste to a .nix file and nix-build it to reproduce.

**Comment by wmertens** [comment]
Since the standard build process relies on passing inputs via the
environment, either directly or via a file, the only way to send large
input texts to the builder is via some alternative of builtins.toFile that
allows putting derivations in output text. @edolstra am I correct?

**Comment by edolstra** [comment]
I don't think the `echo` fails, because `echo` is a shell built-in. The problem is that the builder cannot be started because its environment is too large.

**Comment by wmertens** [comment]
@edolstra right, hence the need for a built-in function...

**Comment by edolstra** [comment]
Enhancing `toFile` is not easy because currently "source files" (i.e. files added via `addToStore`) cannot depend on derivations. Probably the easiest fix is to add some mechanism to the `derivation` primop to denote attribute values that should be passed via files rather than environment variables. E.g.
```
mkDerivation {
  _passAsFile = ["foo"];
  foo = "a very long string";
}
```
Then `build.cc` would write the contents of `foo` to a temporary file and put the file name in the environment variable `foo` (e.g. `/tmp/nix-build-.../foo`).

**Comment by MarcWeber** [comment]
There is another option: add a primop "gzipping" the text, then echo -n
"$text"  | gunzip > $n should work nicely for my use case without
exceeding bash limits that fast.

There is yet another option: Implement a second way to pass inputs to a
builder, eg by "writing" a file instead of setting an env var? Eg
mkDerivation { files_contents.foo = "xyz" } and make the builder write
$TMP/foo ? Then RAM should be the only remaining limit.

**Comment by edolstra** [comment]
Gzipping is not a real solution because it only increases the limit by some small factor.

And writing a file is exactly what I just proposed...

**Comment by MarcWeber** [comment]
My case httpd.conf: 141K x, 6.4K  x.gz,  22 times is not a "small factor' IMHO. But I agree.

**Comment by wmertens** [comment]
I would love a `_passAsFile` list! That should cut down on a lot of intermediate derivations in the store (writing a script, storing it in the store, copying it into a build product and waiting until it gets GCed...)

Should the environment variables stay the same or should they get a "File" suffix? So `fooFile` instead of `foo`?

**Comment by wmertens** [comment]
Nice! So now writeText needs to use this, right? The problem is that
because the environment variable is named the same, its builder can't
differentiate between accidental filenames and a Nix version that doesn't
support passAsFile yet... :-/

**Comment by wmertens** [comment]
@edolstra ^

**Comment by edolstra** [comment]
Hm, good point. Nix could set `$<attrName>File` instead of `$<attrName>` if `passAsFile` is used.

**Comment by wmertens** [comment]
I think that would be good!

**Comment by edolstra** [comment]
Done in bd9106415099b32a51f66be886d18271e65ac9dd.

**Comment by copumpkin** [comment]
> because currently "source files" (i.e. files added via addToStore) cannot depend on derivations

@edolstra can you elaborate on why that is?

**Comment by edolstra** [comment]
When a file is added to the store, all its dependencies must be valid as well. In the case of a string that contains the path of a derivation output, the derivation output wouldn't be valid yet (since the derivation hasn't been built yet).

**Comment by copumpkin** [comment]
Ah, I see, thanks!
