### ISSUE TITLE
`lib` could be a supported output in flakes

### ISSUE THREAD

**Issue by domenkozar** [NixOS/nix#4744]
There's currently no officially supported way of exposing functions from a flake.

Existing examples are:

- https://github.com/NixOS/nixpkgs/blob/master/flake.nix#L12
- https://github.com/numtide/flake-utils/blob/master/flake.nix#L4

**Comment by FRidh** [comment]
Would this be about reserving the name only, or also testing types? For example, I think `lib` should contain only pure functions, and not builders or derivations.

**Comment by domenkozar** [comment]
What about plain values? In other words, no derivations.

**Comment by roberth** [comment]
Derivations are just attribute sets and you'd have to traverse to arbitrary depth to find them.
I wouldn't bother with such a restriction. It will just make people write `lib = { ... }: actualLib`, complicating the code and losing memoization.

**Comment by zseri** [comment]
`lib` is occasionally used to put generic builders in there (which don't fit into `packages`, at least, because they expect arguments about what they should do), so...

**Comment by zseri** [comment]
still necessary/useful.

**Comment by jmgilman** [comment]
What needs to happen for this to receive approval?  The next steps are not readily apparent reading through the comments.

**Comment by zseri** [comment]
btw the thing I meant was https://github.com/YZITE/flake-utils/blob/main/lib.nix and related files

**Comment by roberth** [comment]
Without something like `lib`, people start guessing where to put their functions, e.g. https://github.com/pinpox/lollypops/blob/4ef65c94bbb217861efc522a0c41936a6f500c23/flake.nix#L47

When we bless `lib`, we should also think about libraries that depend on the `system` parameter, as most functions and libraries do depend on it one way or another, and it would be good to have a standard, so that `system` can be injected by Nix code that abstracts over `system`.

`lib.<system>` is appealing, but mixes the namespace of system types with the namespace of system-independent functions.

I'd prefer `lib.systems.<system>`, so that we steal only one name from the namespace of system-independent functions.

`lib.perSystem system` could be an alternative that isn't memoized by default, but supports potentially all systems. I suppose this might be controversial until we have a general solution for `system`-parametric expressions in flakes.

**Comment by roberth** [comment]
Done in #7606, nix >= 2.13
