### ISSUE TITLE
Installation script not working on arch linux

### ISSUE THREAD

**Issue by PicoGeyer** [NixOS/nix#4762]
I started by trying to install NixOS for the Daedelus wallet development (https://github.com/input-output-hk/daedalus#nix)
curl -L https://nixos.org/nix/install | sh
which then fails with:
copying Nix to /nix/store......................................
installing 'nix-2.3.10'
error: while setting up the build environment: getting attributes of path '/System/Library/Frameworks': No such file or directory
/tmp/nix-binary-tarball-unpack.OSzxGZ8KJw/unpack/nix-2.3.10-x86_64-linux/install: unable to install Nix into your default profile

The instructions on https://nixos.org/download.html seem to be identical.

System details:
Distro: Arch linux
Kernel: 5.11.16-arch1-1

Is there a bug in the installer or do I have issues with my system?

**Comment by abathur** [comment]
@PicoGeyer Not sure. I just peeked in here because I've worked on the installer recently, but I don't think this is the installer itself. Definitely something odd here, though. 

I only see this path in the Nix source [once](https://github.com/NixOS/nix/blob/2.3.10/src/libstore/globals.cc#L66-L69):

```cc
#if __APPLE__
    sandboxPaths = tokenizeString<StringSet>("/System/Library/Frameworks /System/Library/PrivateFrameworks /bin/sh /bin/bash /private/tmp /private/var/tmp /usr/lib");
    allowedImpureHostPrefixes = tokenizeString<StringSet>("/System/Library /usr/lib /dev /bin/sh");
#endif
```

- I'm not sure why `__APPLE__` would be defined. Do you have any ideas?
- Your log does indicate that Nix is using the `x86_64-linux` install script, so the installer presumably got the right information from `"$(uname -s).$(uname -m)"`.

I'm not very knowledgeable about anything covered here beyond the installer, so if the above doesn't give you a sense of what's going on, we'll probably need to track down someone who is.

**Comment by matthewbauer** [comment]
I think the daedalus instructions are messing things up. `/etc/nix/nix.conf` shouldn't have a `extra-sandbox-paths = /System/Library/Frameworks` entry on Linux. You should be able to remove that safely.

**Comment by abathur** [comment]
Definitely worth checking, and that would make a lot more sense out of this. I didn't keep reading the instructions past the install line itself, which looked fine. 😬

**Comment by PicoGeyer** [comment]
@matthewbauer Oh yes, you're absolutely right. Thanks.
Sorry that I didn't spot that.
I'll chat to them about fixing it.
