### ISSUE TITLE
Multi user Installation failed

### ISSUE THREAD

**Issue by FranciscoAndaur** [NixOS/nix#4797]
**Installation failed**

`---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo mkdir -pv -m 0755 /nix /nix/var /nix/var/log /nix/var/log/nix /nix/var/log/nix/drvs /nix/var/nix /nix/var/nix/db /nix/var/nix/gcroots /nix/var/nix/profiles /nix/var/nix/temproots /nix/var/nix/userpool /nix/var/nix/gcroots/per-user /nix/var/nix/profiles/per-user

to make the basic directory structure of Nix (part 1)

mkdir: /nix: Read-only file system
mkdir: /nix/var: Read-only file system
mkdir: /nix/var/log: Read-only file system
mkdir: /nix/var/log/nix: Read-only file system
mkdir: /nix/var/log/nix/drvs: Read-only file system
mkdir: /nix/var/nix: Read-only file system
mkdir: /nix/var/nix/db: Read-only file system
mkdir: /nix/var/nix/gcroots: Read-only file system
mkdir: /nix/var/nix/profiles: Read-only file system
mkdir: /nix/var/nix/temproots: Read-only file system
mkdir: /nix/var/nix/userpool: Read-only file system
mkdir: /nix/var/nix/gcroots/per-user: Read-only file system
mkdir: /nix/var/nix/profiles/per-user: Read-only file system

---- oh no! --------------------------------------------------------------------
Jeeze, something went wrong. If you can take all the output and open
an issue, we'd love to fix the problem so nobody else has this issue.`

I'm using a MacbookPro from 2017

**Steps To Reproduce**

1. sh <(curl -L https://nixos.org/nix/install). --daemon
2. hit yes on everything
3. See error

**Expected behavior**

nix installed properly.

**`nix-env --version` output**

**Additional context**

I did try installing nix earlier using 
**curl -L https://nixos.org/nix/install | sh**
and I followed instructions online on how to delete it.  Maybe that's the case. I missed something.

because it created a file in the ROOT directory that was read only.

**Comment by abathur** [comment]
@FranciscoAndaur The underlying issue here is fixed in #4289 (but a new release hasn't been cut since it was merged), so I'll focus on trying to get you back on the road.

Did you have a Nix install before the initial attempt you mention? This sounds like what happens when you have a previous install that still has nix in `/etc/synthetic.conf` (or one that hasn't been rebooted since it was removed). 

`synthetic.conf` causes macOS to create an empty read-only root folder which is intended to be used as a mount point for the Nix volume. There's a gap in the check used in the most-recent Nix release (2.3.10) that decides if you need a Nix volume before the install can continue.

If you find it there, I think you can proceed one of two ways:
1. remove the file if Nix is the only entry, or remove the line otherwise.
2. Check for nix in `/etc/fstab`. If you find it there, remove it via `sudo vifs`.
3. Check for an existing Nix volume (in the graphical Disk Utility, or with `diskutil list`). If so, destroy the data volume using the GUI or `diskutil apfs deleteVolume <disk_identifier>`.
4. Re-run whatever uninstall steps you used before.
5. Once you've got it cleaned up, reinstall with **one** of the below:
    - the [test installer from #4289](https://github.com/NixOS/nix/pull/4289#try-it-out)
    - the official installer with the darwin volume creation flag: `sh <(curl -L https://nixos.org/nix/install) --darwin-use-unencrypted-nix-store-volume --darwin`
        
        Note to anyone referring to this in the future: the volume creation flag will stop working when #4289 is released.
