### ISSUE TITLE
Manual: Note in macOS installation section is incomplete

### ISSUE THREAD

**Issue by toonn** [NixOS/nix#4987]
The second note in the [macOS installation section](https://nixos.org/manual/nix/stable/#sect-macos-installation) is incomplete. The ordered list is missing entirely.

I wanted to look into this but building the manual from the repo results in the expected HTML including the list. My next guess was CSS but the HTML source of the page is actually missing the list entirely.

Source:

```xml
  <note>
    <title>Eventual solutions?</title>
    <para>
      All of the known workarounds have drawbacks, but we hope
      better solutions will be available in the future. Some that
      we have our eye on are:
    </para>
    <orderedlist>
      <listitem>
        <para>
          A true firmlink would enable the Nix store to live on the
          primary data volume without the build problems caused by
          the symlink approach. End users cannot currently
          create true firmlinks.
        </para>
      </listitem>
      <listitem>
        <para>
          If the Nix store volume shared FileVault encryption
          with the primary data volume (probably by using the same
          volume group and role), FileVault encryption could be
          easily supported by the installer without requiring
          manual setup by each user.
        </para>
      </listitem>
    </orderedlist>
  </note>
```

Hosted manual:

> Note: All of the known workarounds have drawbacks, but we hope better solutions will be available in the future. Some that we have our eye on are:

**Comment by abathur** [comment]
Hmm. Not sure why it is eating it.

https://tdg.docbook.org/tdg/5.0/orderedlist.html says note is a valid parent for orderedlist, that it should default to arabic numbering without the numeration, and I don't see any obvious difference between the structure of the example. The wayback machine suggests it's been this way since at least September.

Additional context:
- this section was [correctly converted to markdown in the pandoc commit](https://github.com/NixOS/nix/blame/dc6a8f154856be4a969fc9a03ff2aa0529abbbf9/doc/manual/src/installation/installing-binary.md#L128-L141) 
- it has been [removed entirely](https://github.com/NixOS/nix/commit/eab14a642cbcbc35f4473888d906f9de7deda07b#diff-7ea632297d22708f34a045bb5fb65e4903965831d13aeb37e4f7c45360351744L128-L141) in master after #4289

**Comment by abathur** [comment]
@toonn I guess this can be closed :)

**Comment by toonn** [comment]
Yep, this is gone entirely so no need for a fix : )
