### ISSUE TITLE
Nix fetches paths from the binary cache even when a different store location is specified

### ISSUE THREAD

**Issue by malte-v** [NixOS/nix#5142]
**Describe the bug**

When setting the `store` option to something other that `/`, Nix should not use the binary cache since the packages there will not work in the nonstandard store location.

**Steps To Reproduce**

```
nix build --option store /my-nix-store nixpkgs#hello
# Nix fetches GNU hello from cache.nixos.org.
```

**Expected behavior**

Nix should build GNU hello and its dependencies from source, not putting in any references to `/nix/store`.

**`nix-env --version` output**
nix-env (Nix) 2.4pre20210802_47e96bb

**Comment by edolstra** [comment]
The store URL `/my-nix-store` denotes a chroot store, so it still uses `/nix/store`, just rooted at `/my-nix-store` (i.e. it will create `/my-nix-store/nix/store`). So it can still use cache.nixos.org as a substituter.

To really use a different store prefix, you have to use the `store=...` parameter, like this:

```
$ nix build --store '/tmp/my-nix-store?store=/tmp/my-nix-store' nixpkgs#hello
asked 'https://cache.nixos.org' for '/tmp/my-nix-store/w6msaxcyi978jg5z227x8p68l2j5lqfd-hello-2.10.tar.gz' but got '/nix/store/3x7dwzq014bblazs7kq20p9hyzz0qh8g-hello-2.10.tar.gz'
asked 'https://cache.nixos.org' for '/tmp/my-nix-store/436gvw62cpfsly5y4c0f1yb8xdsxi9g2-bash-4.4.tar.gz' but got '/nix/store/rv68r40mwx7xa7vrlmanczkkjcnkc452-bash-4.4.tar.gz'
...
```

You probably will need to nuke `~/.cache/nix` first since currently it gets confused if you mix different store prefixes.

**Comment by malte-v** [comment]
I see, thanks!
