### ISSUE TITLE
macOS Catalina install fails on insufficient permissions to create volume

### ISSUE THREAD

**Issue by nrdxp** [NixOS/nix#5198]
**Describe the bug**

Originally reported: numtide/nix-unstable-installer#13
and: https://github.com/NixOS/nix/issues/4994#issuecomment-909371702

@abathur requested I start a new issue since it is not exactly like #4994 

Essentially an install fails on Mac OSX Catalina with the following error:
```console
13>Aug 30 18:59:06 mac-mini-2-signing sudo[619]: getgroupcount called triggering group enumeration
~~> Creating a Nix volume

11>Aug 30 18:59:06 mac-mini-2-signing com.apple.xpc.launchd[1] (com.apple.xpc.launchd.domain.pid.diskutil.625): Failed to bootstrap path: path = /usr/sbin/diskutil, error = 2: No such file or directory
Error starting APFS Volume creation: Insufficient privileges (-69863)
```

**Steps To Reproduce**

1. Get a fresh install of OSX Catalina somehow
2. Easiest way to quickly reproduce would be to run numtide/nix-unstable-installer, which only packages the latest version of the install script and overwrites the binary path

**Expected behavior**

Install should work as it did before #4289

**Additional context**
We use a pristine image of Mac OSX running as a zfs volume, which is then provisioned with a script which install Nix and some other required stuff (like secrets). I can trivially destroy and reprovision this image as needed for testing.

**Comment by nrdxp** [comment]
I know you requested a full log @abathur but there really isn't much to report since it fails pretty early on. The message out of the ordinary is the one shown above.

**Comment by abathur** [comment]
Most-interested in the log to see how it's invoked.

**Comment by abathur** [comment]
> 1. Get a fresh install of OSX Catalina somehow
> 2. Easiest way to quickly reproduce would be to run numtide/nix-unstable-installer, which only packages the latest version of the install script and overwrites the binary path

To clarify a little (mostly for later travellers), this issue is almost certainly narrower than this. A fair number of people have confirmed it working fine on ~normal Mac hardware with ~normal nonvirtualized macOS installs, but we've also had a slow trickle of hard-to-debug issues with virtualized/cloud/CI setups. (partial backstory in #4779 and #3156)

> ~~> Creating a Nix volume
> 
> 11>Aug 30 18:59:06 mac-mini-2-signing com.apple.xpc.launchd[1] (com.apple.xpc.launchd.domain.pid.diskutil.625): Failed to bootstrap path: path = /usr/sbin/diskutil, error = 2: No such file or directory
> Error starting APFS Volume creation: Insufficient privileges (-69863)

My initial guess (because of the `Error starting APFS Volume creation: Insufficient privileges: Insufficient privileges` bit) was that your case might need the installer to use sudo when it creates the volume, but I hadn't scrolled off to the end of the long log line to see the diskutil error. I stripped off the code block above to make this stand out more.

In a [small set of Google search results](https://www.google.com/search?q=%22Failed+to+bootstrap+path%22+%22%2Fusr%2Fsbin%2Fdiskutil%22+%22com.apple.xpc.launchd.domain.pid.diskutil%22) drilling down on this I see a number of VMWare Fusion users turning up.

I'm curious if you're just seeing a slightly different part of this elephant than others have reported. Curious what `/usr/sbin/diskutil info -plist / | xmllint --xpath "(/plist/dict/key[text()='GlobalPermissionsEnabled'])/following-sibling::*[1]" -` prints on one of these systems?

**Comment by nrdxp** [comment]
so the provisioning script is open here:
https://github.com/input-output-hk/ci-ops/blob/master/modules/macs/guest/apply.sh#L66

You'll see here I am using the stable installer, that's because these machines are live and in production so I never committed the failed attempt to upgrade. Just imagine calling numtide/nix-unstable-installer on this line instead

output of your command: `<true/>`

**Comment by abathur** [comment]
True is what we're hoping for, at least. I have a few ideas, but I'll be happy if we can sudo our way through it.

I pushed a test commit to my fork that adds sudo back to the addVolume invocation, but I didn't realize tests seem to be failing on master at the moment, so it just fell over after ~30 minutes. 

I re-applied this after the last commit I see with a clean CI run, but I don't think I'll still be on when it finishes. 

If https://github.com/abathur/nix/actions/runs/1188686737 succeeds, it'll generate an installer you can use to try it out. You should be able to look for that run's equivalent of this line https://github.com/NixOS/nix/runs/3463842681?check_suite_focus=true#step:4:10 and then adapt `sh <(curl https://abathur-nix-install-tests.cachix.org/serve/<hash from CI output>/install) --tarball-url-prefix https://abathur-nix-install-tests.cachix.org/serve` to install it.

(I'm cutting a corner in the change for testing, if this works it'll still take a little more brainpower to get a full fix.)

**Comment by nrdxp** [comment]
Thanks for the script, but the curl command above just returns:
```json
{"error":"No such file install"}
```

**Comment by abathur** [comment]
Sorry, it's been a few months; grabbed the wrong URL out of the test. I've updated it above (and linked to where the installer URL shows up in the test output).

**Comment by nrdxp** [comment]
so it looks like we are back to the hash mismatch like the other scripts you sent me:
```
/Users/nixos/install-nix: SHA-256 hash mismatch in 'https://releases.nixos.org/nix/nix-2.4pre19700101_e6dba53/nix-2.4pre19700101_e6dba53-x86_64-darwin.tar.xz'; expected f80acb1fe64995c695f8b70b2a607229e0623dbaba1e58076351f54a9ff74b06, got b2325624c274158ad212e7d3ac51382278ce1be5cdb50c0e0de4c571f0a91aae
```

**Comment by abathur** [comment]
It shouldn't be hitting releases.nixos.org if you're specifying the `--tarball-url-prefix`.

**Comment by nrdxp** [comment]
this is how it was invoked:
```
    curl -L https://abathur-nix-install-tests.cachix.org/serve/k6c7p3fw0ql1bsyn9ky2c9l1c3rqn622/install > ~nixos/install-nix
    sudo -i -H -u nixos -- sh ~nixos/install-nix --daemon --tarball-url-prefix https://abathur-nix-install-tests.cachix.org/serve < /dev/null
```

**Comment by abathur** [comment]
It looks like the outer installer only handles `--tarball-url-prefix <url>` as the first and second arguments; it should work if you'd move --daemon to the end.

**Comment by nrdxp** [comment]
okay that finally worked. I still saw the errors about `/usr/sbin/*: no such file or directory` for a couple different files, but it didn't seem to affect the installation.

**Comment by abathur** [comment]
> I still saw the errors about `/usr/sbin/*: no such file or directory` for a couple different files, but it didn't seem to affect the installation.

These make me a little squeamish, but perhaps they're just noise. Will your next-step be to put these installs through the paces? If so, I'm interested in hearing how that goes. I'll also try to find a little time to try this out on a spare macbook.

**Comment by nrdxp** [comment]
Yes well I can say that this "noise" never occurred with the stable install script, so it might be something, but so far none of our CI pipelines seem to mind the update on the one machine I'm testing this on atm.

**Comment by abathur** [comment]
I used a spare macbook running an 11.4 BigSur beta for a fairly basic test of the same installer you tried and didn't have any trouble. 

I just pushed a commit that takes a more-realistic swing at this and am re-installing macOS on the spare macbook so that I can give it a try when the test wraps up.
