### ISSUE TITLE
nix-store 2.3 incompatible with nix-daemon 2.4pre

### ISSUE THREAD

**Issue by ck3d** [NixOS/nix#5299]
Using nix-store 2.3 on a system where nix-daemon 2.4pre is running results in unexpected behavior.

**Steps To Reproduce**

Following script
```
#!/usr/bin/env nix-shell
#!nix-shell -i sh -p nix

nix-store --version
echo hello > test.txt
STORE=$(nix-store --add-fixed sha256 test.txt)
hexdump -C "$STORE"
```

produces following output:
```
warning: unknown setting 'experimental-features'
nix-store (Nix) 2.3.15
warning: unknown setting 'experimental-features'
00000000  68 65 6c 6c 6f 0a 00 00  00 00 00 00 00 00 00 00  |hello...........|
00000010  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
00010000  00 00 00 00 00 00                                 |......|
00010006
```

The host system runs nix version `2.4pre20210908_3c56f62`.

**Expected behavior**

nix-store shall not add 65536 zeros at the end of the file.

**Comment by regnat** [comment]
I can indeed reproduce it. It’s a bit hard to understand what’s going on because the messages exchanged when using the 2.3 and 2.4 clients are very different. I bisected it however to be introduced by bc109648c41f8021707b55b815e68a890a09f2f6, which should narrow the scope of the possible culprits quite a bit.

/cc @Ericson2314

**Comment by Ericson2314** [comment]
Thanks @regnat! There was some confusions about whether the protocol was using raw dump vs nar dump vs raw dump with references, that might be related too.

**Comment by Ericson2314** [comment]
I am taking a look.
