### ISSUE TITLE
Nix search does not show subPackages  like haskellPackages

### ISSUE THREAD

**Issue by jakobneufeld** [NixOS/nix#5617]
**Is your feature request related to a problem? Please describe.**
Everytime I run nix search nixpkgs, I do not get the submodules like `haskellPakcages`.
When I run `nix search nixpkgs xmo` I get no haskellPackages.
**Describe the solution you'd like**
I want when I run `nix search nixpkgs xmo`
I get search results
for haskellPackages.xmonad, haskellPackages.xmonad-contrib, and other haskellPackages. 
**Describe alternatives you've considered**
I have considered interacting with the elastic search instance of `search.nixos.org` but I think this is an overkill for many usecases.
**Additional context**

**Comment by jakobneufeld** [comment]
One thing I have to point out. I want this feature because I am writing a script which searched nixpkgs with json output.

**Comment by regnat** [comment]
That’s because `nix search` respects `recurseForDerivations` and `haskellPackages.recurseForDerivations` is set to false. So that’s the intended behavior as far as Nix is concerned I think (now whether it should have `recurseForDerivations` set is another matter on which I’ve no opinion whatsoever but which should rather be discussed on the nixpkgs issue tracker)

> One thing I have to point out. I want this feature because I am writing a script which searched nixpkgs with json output.

Just in case you’re not aware of it, `nix search --json` might do what you want already

**Comment by jakobneufeld** [comment]
Maybe, there should be an option that allwos recurseForDerivations.

**Comment by jakobneufeld** [comment]
What do you think @regnat?

**Comment by regnat** [comment]
I’m afraid just doing so would cause some infinite recursions, since for example `nixpkgs` has some top-level values which are themselves instantiations of `nixpkgs` − like `pkgsStatic` − meaning that you can recurse infinitely (`pkgs.pkgsStatic.pkgsStatic.pkgsStatic.pkgsStatic.pkgsStatic.pkgsStatic.pkgsStatic.pkgsStatic.pkgsStatic.pkgsStatic.pkgsStatic.pkgsStatic...`)

**Comment by jakobneufeld** [comment]
Thats ok. I will rewrite by script by using the toplevel `nix search nixpkgs --json`

**Comment by jakobneufeld** [comment]
Wierd, toplevel does not show haskell packages...
