### ISSUE TITLE
`0.1+0.2 == 0.3`

### ISSUE THREAD

**Issue by dasJ** [NixOS/nix#5686]
**Describe the bug**

The sum of two floats is a different thing than a float representing the same number 

**Steps To Reproduce**
```
nix-repl> 0.3 == 0.3
true

nix-repl> 0.1 + 0.2
0.3

nix-repl> 0.1 + 0.2 == 0.3
false

nix-repl> a = 0.1 + 0.2

nix-repl> a == 0.1 + 0.2
true
```

**Expected behavior**

0.1 + 0.2 should be the same as 0.3

**`nix-env --version` output**

`nix-env (Nix) 2.3.16`

**Additional context**

None, really

**Comment by edolstra** [comment]
0.1 + 0.2 is not equal to 0.3 due to limited floating point precision, see [here](https://betterprogramming.pub/why-is-0-1-0-2-not-equal-to-0-3-in-most-programming-languages-99432310d476). The hex representation (%a) of 0.3 is 0x1.3333333333333p-2, but 0.1 + 0.2 is 0x1.3333333333334p-2. So there is not much we can do about this.

An associated problem is that we're using `std::to_string()` for displaying floats, which only shows 6 digits. We could use more, but then we'd have to deal with numbers like 0.1 being printed as 0.10000000000000000555...
