### ISSUE TITLE
User Manual: Anchor links for nix.conf options are gone

### ISSUE THREAD

**Issue by rickynils** [NixOS/nix#5745]
**Describe the bug**

Before the switch to the Markdown-generated user manual (available at https://nixos.org/manual/nix/stable) it was possible to link directly to the description of individual Nix configuration options with URLs like https://nixos.org/manual/nix/stable/#conf-enforce-determinism. It is no longer possible, because the nix.conf page (https://nixos.org/manual/nix/stable/command-ref/conf-file.html) doesn't contain any anchors for the options.

Maybe it is possible to get the HTML generator to add such anchors automatically? I could look into it myself, but I haven't found any documentation on how the user manual is built.

Having direct links to Nix config options seems useful to me, and I used it in https://docs.nixbuild.net

**Comment by regnat** [comment]
I think that’s because the renderer ([mdBook](https://github.com/rust-lang/mdBook)) doesn’t support definition lists, so the page is rendered using a plain list, which doesn’t add any anchor (unlike titles for example, which can be linked to).

> Maybe it is possible to get the HTML generator to add such anchors automatically?

In theory it’s possible to use [Preprocessors](https://rust-lang.github.io/mdBook/format/configuration/preprocessors.html), but that seems to be a pretty big hammer.
Alternatively, the markdown source is generated from a [Nix file](https://github.com/NixOS/nix/blob/c7b66caaca0833f0b88f3a93cbeaad73b4da1089/doc/manual/generate-options.nix), maybe it’s possible to inline some html in there, assuming it doesn’t screw up the other renderers.

**Comment by rickynils** [comment]
In the [built-in functions documentation](https://nixos.org/manual/nix/stable/expressions/builtins.html), there are anchors (it looks like that list is rendered as a definition list). Can't we switch to the same kind of list for the config settings?

**Comment by thufschmitt** [comment]
Indeed, the [Nix file generating the list of builtins](https://github.com/NixOS/nix/blob/master/doc/manual/generate-builtins.nix) generates an html definition list. We could probably do the same for the nix.conf options [here](https://github.com/NixOS/nix/blob/master/doc/manual/generate-options.nix)
