### ISSUE TITLE
Official example from website not working on latest Nix version

### ISSUE THREAD

**Issue by raymond-h** [NixOS/nix#5850]
**Describe the bug**

Running a command from the official website to create an ad-hoc "reproducible" environment fails.

The `nix-shell` snippet is gotten from https://nixos.org/guides/ad-hoc-developer-environments.html, and as of creating this issue, is literally called "a fully reproducible example", and meant to exactly examplify that "A fully reproducible example would give exactly the same results no matter **when** or on **what machine** you run the command".

I am admittedly uncertain whether this is an issue with the website being outdated, or a bug in Nix itself, although given the intended purpose of Nix, I imagine the same old line should work even with the currently-latest version of Nix.

**Steps To Reproduce**

1. `docker --rm -it nixos/nix:2.5.1` (The same version that `nixos/nix:latest` refers to, as of creating this issue)
2. `nix-shell --pure -p git -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/82b5f87fcc710a99c47c5ffe441589807a8202af.tar.gz`
3. See error message stating this: `error: anonymous function at /nix/store/y2fh997ssq4i68di86q60mwfviqjvh28-source/pkgs/top-level/default.nix:20:1 called with unexpected argument 'inNixShell'`

**Expected behavior**

I expected the output to match the website text box, which illustrates a new shell, where `git --version` is run and expected to output `git version 2.25.4`.

**`nix-env --version` output**

`nix-env (Nix) 2.5.1`

**Comment by tomberek** [comment]
The underlying issue was fixed here: https://github.com/NixOS/nixpkgs/pull/99316/files

It is a bit annoying that the example is old. It originates from nix.dev: https://github.com/nix-dot-dev/nix.dev/blob/master/source/tutorials/ad-hoc-developer-environments.md

The website has an open issue here: https://github.com/nix-dot-dev/nix.dev/issues/219

Closing as that is a better place to track this.
