### ISSUE TITLE
Can't install the nix

### ISSUE THREAD

**Issue by luoyunxi77** [NixOS/nix#5940]
When I use the command `sh <(curl -L https://nixos.org/nix/install)` to install the nix, it **failed** and told me need to do the following steps one by one:
- Back up (copy) /etc/bash.bashrc and /etc/bash.bashrc.backup-before-nix
   to another location, just in case.
- Ensure /etc/bash.bashrc.backup-before-nix does not have anything
   Nix-related in it. If it does, something is probably quite
   wrong. Please open an issue or get in touch immediately.

- Once you confirm /etc/bash.bashrc is backed up and
   /etc/bash.bashrc.backup-before-nix doesn't mention Nix, run:
   mv /etc/bash.bashrc.backup-before-nix /etc/bash.bashrc

But for the step2, I found /etc/bash.bashrc.backup-before-nix file has some nix-related code. 
![image](https://user-images.githubusercontent.com/51731378/150113057-00acf236-c029-4929-96e7-92551cebe6ab.png)

So I wrote this issue, Could you help me to resolve it?

**Comment by abathur** [comment]
Does `/etc/bash.bashrc` have it, as well? 

If so, you can probably just remove these lines from `/etc/bash.bashrc` and then remove `/etc/bash.bashrc.backup-before-nix` copy (but not the copies the installer suggested you make).

This does indicate something unexpected's happened to your rc files, so I do recommend diffing the two files, and skimming the bash.bashrc to make sure it has any expected customizations.

You may need to repeat this for any other /etc/*.backup-before-nix files.

**Comment by luoyunxi77** [comment]
Hi @abathur, Thanks for reply.
 I manually removed the nix related code in the `/etc/bash.bashrc` file.
And then Nix install successfully. It displays the following message.
![image](https://user-images.githubusercontent.com/51731378/150245986-e6e6f3dc-1589-45e0-968b-d4d840ee520b.png)

But when I open the new term to run the `nix-shell -p nix-info --run "nix-info -m"`.
It displays the `not find nix-shell`. Does any additional step need I do?
![image](https://user-images.githubusercontent.com/51731378/150247783-37195c42-1478-492d-aaad-1aa75d0bb628.png)


---
By the way, When I installed the nix successfully, it auto append the nix related code in the `/etc/bashrc` , `/etc/zshrc` , 
![image](https://user-images.githubusercontent.com/51731378/150247913-b60ad2c7-e8f8-42d4-8ed6-dea72a3ad227.png)

**Comment by abathur** [comment]
You'll have to dig around in your profile/rc files. Nix isn't making it onto your PATH, but there are too many possible configurations to know for sure why.

You might be able to get some better real-time help in the Nix / NixOS room on Matrix (link @ https://nixos.org/community/index.html), my knowledge of the default startup files and orders isn't the best.

Usually, something early is returning before startup gets to source that file, or something late is hard-setting the PATH to one that doesn't include what was already added.

Some broad thoughts:

1. See if it works in `bash`, since that'll help you it narrow it down to a difference between the startup processes.
2. If you add `set -x` early enough (I think maybe `/etc/profile` or `/etc/zshenv`--but I'm not sure), it'll show what's executing and make it a little easier to figure out what it is doing.

**Comment by luoyunxi77** [comment]
Yep, I will dig into this issue. Thanks for your help.
I will close this issue.
