### ISSUE TITLE
nix-env --upgrade silently converts profile to new experimental format (on Ubuntu)

### ISSUE THREAD

**Issue by vojtechkral** [NixOS/nix#6032]
**Describe the bug**

After running `nix-env -u`, my nix single-user profile apparently gets upgraded to a new format as if I used the experimental `nix profile` command (which I **never did**). All subsequent `nix-env` calls such as installing a package or `-u` report:

    error: profile '/nix/var/nix/profiles/per-user/vojtech/profile' is incompatible with 'nix-env'; please use 'nix profile' instead

**Steps To Reproduce**

1. Install nix based on the instructions [here](https://nixos.org/download.html), single-user variant.
2. Install a couple of packages...
3. Update them once in a while with `nix-env -u`/
4. The profile becomes unusable, `nix-env` reports the above error.
5. I have to rollback the profile, which works, but I can no longer upgrade with `nix-env -u` as that will (reproducibly) lead to the problem again.

**Expected behavior**

Profile stays in the non-experimental format?

**`nix-env --version` output**

`nix-env (Nix) 2.6.0`

**Additional context**

I didn't do anything special with the profile at all, basically the only commands I use are `nix-env -iA $package`, `nix-channel --update`,  `nix-env -u`, and `nix-collect-garbage --delete-older-than 30d`. (And the rollback one I guess after this started happening.)

**Comment by avh4** [comment]
I ended up in this same situation, only using `nix-env -i` and `nix-collect-garbage` since first installing nix (also on Ubuntu 21.10).

Here's my recollection of the steps I took:
- install nix (multi-user mode) (Nix 2.7.0)
- installed some packages with `nix-env -i`
- created `~/.config/nix/nix.conf` with `experimental-features = nix-command`
- did some stuff with `nix-shell` and `nix-collect-garbage`
- installed some more packages with `nix-env -i`
- everything was still fine at the point
- log out of my user session
- log in as the same user
- install another package with `nix-env -i`
- now things are broken as described in the original issue (`nix-env -i`, `nix-env --uninstall`, and `nix-env -q` commands now give "profile is incompatible with 'nix-env'")

As with the original poster, `nix-env rollback` (and removing `experimental-features` from my `nix.conf`) seems to have gotten things working again.

**Comment by edolstra** [comment]
Hm, it's hard to see how this could happen without running `nix profile` at some point, since the only place that writes `manifest.json` (which marks a new-style profile) is in `nix profile`:
```
$ git grep manifest.json
src/nix-env/user-env.cc:    if (pathExists(userEnv + "/manifest.json"))
src/nix/profile.cc:        auto manifestPath = profile + "/manifest.json";
src/nix/profile.cc:        writeFile(tempDir + "/manifest.json", toJSON(*store));
src/nix/profile.md:-r--r--r-- 2 root root 1402 Jan  1  1970 manifest.json
src/nix/profile.md:The file `manifest.json` records the provenance of the packages that
```

**Comment by avh4** [comment]
Hmm, maybe some other cli I was trying out used `nix profile` internally because of my `nix.conf`?

My first thought is maybe `lorri`, which I did install at some point around the "things are still fine".  But a quick search of its code doesn't show anything obvious.  Maybe it uses some other nix command that then indirectly uses `nix profile`?

Checking my logs to see if there's any other possibilities... I did use also use `nix-build`, `nix-instantiate`, `nix show-config`, `cabal2nix` and `node2nix` in the suspect time period.

**Comment by avh4** [comment]
.. but what's also weird is that here's the exact list of commands when things went wrong:
```sh
nix-env -qaP obsidian
nix-env -i obsidian    # <-- this worked fine
nix-env -qaP obsidian
tree /nix/store/sysf63x9m1wgv6w4b829j18aw0pilpnb-obsidian-47.05/
nix-env --help
nix-env --uninstall obsidian    # <-- now things are broken
```

And I'm pretty sure I was not doing anything in any other terminals/apps during that sequence.  So it seems like is _has to be_ the `nix-env -i obsidian` that upgraded things to the new profile format.

Also, that `nix-env -i obsidian` created generation 9, and `ls -l /nix/var/nix/profiles/per-user/$USER/*/manifest.json` shows only generation 9 has the new profile format.

**Comment by edolstra** [comment]
I see the problem: the obsidian package contains an unrelated file named `manifest.json` in its root directory.

**Comment by avh4** [comment]
Ah, okay, a weird coincidence for me, then.  (That obsidian package looks like it's some dwarf fortress graphics theme and not even what I wanted to install anyway!)  I guess my issue is likely unrelated to the original one, then, unless there are other packages with the same issue.
