### ISSUE TITLE
Regression in Nix ≥2.6: Evaluation error in `--impure` mode, breaks NixOS builds

### ISSUE THREAD

**Issue by erikarvstedt** [NixOS/nix#6156]
When evaluating the following derivation...
```bash
read -d '' src <<'EOF' || :
  # NixOS 21.11 as of 2022-02-24
  with (builtins.getFlake "github:NixOS/nixpkgs/40ef692a55b188b1f5ae3967f3fc7808838c3f1d").legacyPackages.x86_64-linux;
  let
    file = pkgs.writeText "json" "{}";
    fileLink = pkgs.runCommand "fileLink" {} ''
      ln -s ${file} $out
    '';
    json = builtins.fromJSON (builtins.readFile fileLink);
    jsonFile = pkgs.writeText "json" (builtins.toJSON json);
  in
    jsonFile.outPath
EOF
# nix 2.6.1
nix shell nixpkgs/38346f64616c3176f73ad0f20e51557ec0f3d75d#nix_2_6 -c nix eval --impure --expr "$src"

```
...nix fails with error:
```
error: the string '{}' is not allowed to refer to a store path (such as '/nix/store/yf8dkhp2a8wzf4c4d1sbpkw1ryl047cm-json')
```

This happens for all Nix versions ≥2.6, including `master`.
Nix versions <2.6 work correctly:
```bash
nix shell nixpkgs/38346f64616c3176f73ad0f20e51557ec0f3d75d#nix_2_4 -c nix eval --impure --expr "$src"
nix shell nixpkgs/38346f64616c3176f73ad0f20e51557ec0f3d75d#nix_2_5 -c nix eval --impure --expr "$src"
#=> /nix/store/yf8dkhp2a8wzf4c4d1sbpkw1ryl047cm-json
```

### Background, NixOS breakage

This bug always appears when using Nix ≥2.6 to build a NixOS 21.11 system with `mattermost` enabled.
This is how I encountered this bug. The above snippet is a compressed repro of this system build failure:

```bash
read -d '' nixosSystem <<'EOF' || :
  # NixOS 21.11 as of 2022-02-24
  ((builtins.getFlake "github:NixOS/nixpkgs/40ef692a55b188b1f5ae3967f3fc7808838c3f1d").lib.nixosSystem {
    system = "x86_64-linux";
    modules = [{
      services.mattermost.enable = true;
      boot.loader.systemd-boot.enable = true;
      fileSystems."/".device = "_";
    }];
  }).config.system.build.toplevel
EOF
# nix 2.6.1
nix shell nixpkgs/38346f64616c3176f73ad0f20e51557ec0f3d75d#nix_2_6 -c nix build --impure --no-link --expr "$nixosSystem"
```

**Comment by thufschmitt** [comment]
That seems to be a consequence of https://github.com/NixOS/nix/pull/1643 (which fixes a real bug). Not sure what should be done about it 🤔

(fwiw, this involves IFD, so probably the mattermost module should be changed as as far as I remember it isn’t allowed in nixpkgs)

**Comment by erikarvstedt** [comment]
The JSON string `{}` (and also the mattermost config) contain no store paths and therefore shouldn't have a string context.
Am I missing something here?

**Comment by erikarvstedt** [comment]
Also, why does the following cause no error?
```bash
read -d '' src <<'EOF' || :
  # NixOS 21.11 as of 2022-02-24
  with (builtins.getFlake "github:NixOS/nixpkgs/40ef692a55b188b1f5ae3967f3fc7808838c3f1d").legacyPackages.x86_64-linux;
  let
    file = pkgs.writeText "json" "{}";
    fileLink = pkgs.runCommand "fileLink" {} ''
      ln -s ${file} $out
    '';
    jsonFile = pkgs.writeText "json" (builtins.readFile fileLink);
  in
    jsonFile.outPath
EOF
# nix 2.6.1
nix shell nixpkgs/38346f64616c3176f73ad0f20e51557ec0f3d75d#nix_2_6 -c nix eval --impure --expr "$src"
```

**Comment by thufschmitt** [comment]
> The JSON string `{}` (and also the mattermost config) contain no store paths and therefore shouldn't have a string context. Am I missing something here?

String contexts aren’t (directly) related to the content of the string, but to how it was built. Having `foo` in the context of `s` means that `foo` has been involved in the construction of `s` (which means that for example, `lib.substring 0 0 pkgs.hello` will have `pkgs.hello` in its context, despite being an empty string). And since a file in a derivation potentially depends on all the inputs of the derivation, the result of `builtins.readFile`-ing it must have them in its context.

> Also, why does the following cause no error?
> ...

It’s perfectly OK to manipulate a string that has a non-empty context (and even to write it). The only disallowed thing is `builtins.fromJSON`. I assume the reason for that is that it discards the context (since the context is only attached to strings) but I’m not entirely sure

**Comment by ncfavier** [comment]
> The JSON string `{}` (and also the mattermost config) contain no store paths and therefore shouldn't have a string context. Am I missing something here?

Agreed, fixed in https://github.com/NixOS/nix/pull/7260:

```
~ $ nix run nix/daf1423a4a07f3d8a0c88a590b4ec454d64233cc -- eval --impure --expr "$src"
"/nix/store/yf8dkhp2a8wzf4c4d1sbpkw1ryl047cm-json"
```

To be entirely honest I don't understand why `builtins.substring 0 0 str` inherits `str`'s context. A string's context tells you how to ensure that the store paths referred to by the string are valid. Context about paths that are not in the string is meaningless.

If anything I think every built-in operation that returns a string should re-scan the resulting string and filter down its context just like `readFile` now does (e.g. `builtins.substring 0 0 str` would always return a context-free `""`), but that might be a bit too much, performance- and compatibility-wise?
