### ISSUE TITLE
Flake: nixConfig options don't get used by nix run

### ISSUE THREAD

**Issue by Kranzes** [NixOS/nix#6170]
**Describe the bug**

When using `nix run`, the command does not use the `nixConfig` options declared in the flake.nix. `nix build` does read it accordingly.

For example when using `nixConfig.extra-substituters` with `nix run` the build process won't use the binary cache, but when using `nix build` it does.

**Steps To Reproduce**

1. Execute `nix run github:AmitHalpert/contamination` 
2. ^ binary cache is **not** used ^
3. Execute `nix run github:AmitHalpert/contamination \
--option extra-substituters 'https://contamination.cachix.org/' \
--option extra-trusted-public-keys 'contamination.cachix.org-1:KmdW5xVF8ccKEb9tvK6qtEMW+lGa83seGgFyBOkeM/4='`
4. ^ binary **is** being used ^
5. Execute `nix build github:AmitHalpert/contamination` (binary cache is used and the options are prompted when running)

**Expected behavior**
When executing `nix run` on a flake with the `nixConfig` options set I expect `nix run` to read those options and use them accordingly.

**`nix-env --version` output**
`nix-env (Nix) 2.7.0pre20220127_558c4ee`

**Comment by tomberek** [comment]
perhaps: https://github.com/flox/nix/commit/48483e7154462ee82e91e7059d48e094c9f69255 ?
I'm not sure what else might be impacted (or "double-locked") by adding that unconditionally there

**Comment by thufschmitt** [comment]
The issue seems to be that `lockFlags.applyNixConfig` is false by default. Most commands overrides it − but `nix run` doesn’t 

So I think there’s two possibilities out of this:

1. Change the definition of `lockFlags` in [flake.cc](https://github.com/NixOS/nix/blob/c9a29d0d92529338026190374d0e7e886f486e47/src/nix/flake.cc#L672) to have `.applyNixConfig = true` since that seems to be the most sensible default. But maybe there are some catches to be aware of (thinking of completion in particular. I wouldn’t want `nix build .#<TAB>` to try and apply the nix config)
2. Just set `lockFlags.applyNixConfig = true;` in `nix run`’s `run()` function like it’s done for other commands

**Comment by edrex** [comment]
Are there any other nix subcommands that will need to `applyNixConfig`?
