### ISSUE TITLE
Unintuitive priority of `or`?

### ISSUE THREAD

**Issue by vcunat** [NixOS/nix#629]
A while ago I was taken unawares by the fact that the operator priority is higher for `or` than for function application. That is strognly against my functional-programming intuition of application always binding the strongest. Example of the current state:

``` nix
{ truth =
  set.attribute or function param == (set.attribute or function) param;
}
```

I'm aware that changing such things is not to be taken lightly &ndash; maybe in nix-1.10 it might be bearable? (Unless you actually prefer the current priority.)

**Comment by vcunat** [comment]
Perhaps there are some good arguments for that decision. One can't find such information in the nix manual... (but the priority order *is* documented in there clearly)

**Comment by vcunat** [comment]
I don't think there's sufficient motivation to keep an open ticket for this :shrug:

**Comment by zimbatm** [comment]
It belongs on a "language quirks" inventor page :-)

**Comment by vcunat** [comment]
:smile:  the formulation made me recall http://lambda-the-ultimate.org

**Comment by roberth** [comment]
I think we could make the parentheses in the third operand semi-mandatory, by emitting a warning if the third operand's ast node is a function application without parentheses. This would have to be done during the parsing, because the ast is too lean (and we probably want to keep it that way).
It's not perfect, but at least we can fix the confusion without breaking compatibility.

> Perhaps there are some good arguments for that decision.

Fwiw, there's no `or` operator; only the `_ . _ or _` ternary operator, with the same priority as `_ . _`.

**Comment by vcunat** [comment]
Sounds like a good idea, from UX perspective at least.  I think it will be rare to use `or` with a function on the right side, so warn-forcing explicit parenthesis in that case should be a low price overall.
