### ISSUE TITLE
getRev seems to assume SHA1 hashes

### ISSUE THREAD

**Issue by Uthar** [NixOS/nix#6368]
Hello

I am making a fetcher plugin that uses sha256 hashes for revisions, but there is one thing holding me back:

https://github.com/NixOS/nix/blob/c0ad86f6817684efc2955dae904f548ea99ad6ee/src/libfetchers/fetchers.cc#L239-L243

Line 242 in `fetchers.cc`: it seems that it assumes that every hash is sha1.

I have also tried to simply not call `getRev` in plugin code and get the `Hash` manually, but I'm still getting errors like this:
```
$ src/nix/nix --extra-experimental-features 'nix-command flakes' flake metadata fsl+https://fossil.galkowski.xyz/nix-cl?ref=flake
fetching Fossil repository 'https://fossil.galkowski.xyz/nix-cl'
Resolved URL:  fsl+https://fossil.galkowski.xyz/nix-cl?ref=flake
Locked URL:    fsl+https://fossil.galkowski.xyz/nix-cl?ref=flake&rev=a89ab27eacb1736c22630d9824a9b1147683fa41fa2f2c482c9d4ea456c993e4
Description:   Common Lisp package sets and `withPackages` wrappers
Path:          /nix/store/nwbhqqwgi1phpxxhikrfff8gcypah0sp-source
error: hash 'a89ab27eacb1736c22630d9824a9b1147683fa41fa2f2c482c9d4ea456c993e4' has wrong length for hash type 'sha1'
```
I think this is because other parts of the code are using the version of `getRev` from `fetchers.cc`. By looking at the above stderr, I think it's line 202 in `flake.cc` that's erroring out:

https://github.com/NixOS/nix/blob/c0ad86f6817684efc2955dae904f548ea99ad6ee/src/nix/flake.cc#L199-L205

I have two questions:
- Is the `htSHA1` in `fetchers.cc` there on purpose, or should it be changed to allow for other hash types?
- Is there some smart way to make my plugin work, without changing Nix source code itself or without truncating my hash to 40 characters?

*full code here: https://gist.github.com/Uthar/8b360cc12153ecd827a33fe990e2eb82*

**Comment by thufschmitt** [comment]
Indeed, Nix assumes that the `rev` field is a sha1 (which makes sense given that it has been designed with Git in mind, and git is still essentially using sha1 everywhere). I think it’s fine to make it virtual so that individual fetchers can override it.

In the short term, the simplest solution might just be to not use `rev` for the fossil revision. The only shortcoming I can think of is that it won’t be nicely displayed in `nix flake metadata` but apart from that everything _should_ work just fine

**Comment by edolstra** [comment]
I think it's fine to allow `Input::getRev()` to return arbitrary-sized hashes. The various fetchers should check that the rev has the size expected by that fetcher (e.g. 20 bytes for git).

**Comment by thufschmitt** [comment]
Looking a bit further at the code, we could get around by only removing the `assert(type == htSHA1);` calls, because the `parseAny` function can actually accept any (known) kind of hash, provided that the hash type is specified (see the doc at https://github.com/NixOS/nix/blob/master/src/libutil/hash.hh#L39-L43=). So (except for these assertions), you should be able to specify your hashes as `sha256:<hash>`
