### ISSUE TITLE
MacOS: `file 'nixpkgs' was not found in the Nix search path` after install

### ISSUE THREAD

**Issue by Strum355** [NixOS/nix#6388]
**Describe the bug**

When running `nix-shell -p 'bash'` as normal user (not root/no sudo), I get the following:

```
error: file 'nixpkgs' was not found in the Nix search path (add it using $NIX_PATH or -I)

       at «string»:1:25:

            1| {...}@args: with import <nixpkgs> args; (pkgs.runCommandCC or pkgs.runCommand) "shell" { buildInputs = [ (bash) ]; } ""
             |                         ^
(use '--show-trace' to show detailed location information)
```

Running `sudo nix-shell -p 'bash'` works without issue.

**Steps To Reproduce**

1. Use fish shell (don't know if this affects it or not)
2. Install Nix with `sh (curl -L https://nixos.org/nix/install | psub)` (fish workaround for no `<(...)`
3. Accept all the defaults
4. Add `fenv "source /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh || true"` to `~/.config/fish/config.fish`
5. Restart laptop (or not, didnt affect it)

**Expected behavior**

Running `nix-shell -p 'bash'` just works:tm:

**`nix-env --version` output**

nix-env (Nix) 2.7.0

**Additional context**

Monterey 12.2.1

```
> echo $NIX_PATH
<no output>
```

```
> sudo $NIX_PATH
<no output>
```

`$HOME/.nix-profile` didn't exist until either a reboot or I ran `zsh`, not sure which of the two created it. Issue still not resolved anyways

**Comment by Strum355** [comment]
Edit: I had `set -x NIX_PATH $HOME/.nix-defexpr/channels:$NIX_PATH` in ~/.config/fish/config.fish` but it seems to be getting overwritten, probably by `fenv "source /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh || true"` (that returns exit code 0 btw).

Running `env NIX_PATH=$HOME/.nix-defexpr/channels nix-shell -p 'bash'` works perfectly.

Of extra note, running `nix-shell -p 'bash'` in `zsh` also has the same behaviour, so I dont think this is a `fish` issue

**Comment by abathur** [comment]
I haven't really read into it very deeply since I don't use fish, but I've noticed that there are some malingering problems with fish support in the issues. 

I think that file probably isn't sourcing cleanly if you're doing it from fish. If you're running the other nix-shell command from the same shell, it may also not be taking. The profile hook sets `__ETC_PROFILE_NIX_SOURCED=1`, and then the hook won't run again if it is set. I guess you could test that with `echo $__ETC_PROFILE_NIX_SOURCED`.

Fish users might have a better sense (I'm not sure, but at least @lilyball @cole-h?), but some combination of these may get you moving again:
- https://github.com/NixOS/nix/pull/4689
- https://github.com/NixOS/nix/pull/3985
- https://github.com/lilyball/nix-env.fish/

**Comment by lilyball** [comment]
`__ETC_PROFILE_NIX_SOURCED` isn't exported, so it shouldn't end up in the fish environment with `fenv`.

Why do you have the `|| true` there? The script should succeed. If it's failing that suggests something is wrong.

Looking at the `nix-daemon.sh` script right now, it's not actually setting `NIX_PATH` anyway. It looks like this was removed in Nix v2.4.0 in favor of having Nix define a default path to use if `NIX_PATH` is unset. If you have the variable as set but empty, that will break the default. Please make sure the `$NIX_PATH` var is unset (you can run `set -S NIX_PATH` to check; it should print nothing if the var is unset).

> `$HOME/.nix-profile` didn't exist until either a reboot or I ran `zsh`, not sure which of the two created it. Issue still not resolved anyways

The profile script used to create this dir for you, but this was also removed in Nix v2.4 in favor of just having `nix-env` create it as needed.

In any case, my best guess here is that you have something that sets `$NIX_PATH` to an empty string. You should find this and remove it.

Beyond that, if you install Fish through Nix you can use an overlay to override the fish derivation's `fishEnvPreInit` attribute to have it source the profile for you (see https://github.com/NixOS/nixpkgs/blob/b14c5adb2df6222ce7eaee23b0222698f378a25c/pkgs/shells/fish/default.nix#L29-L37). This does unfortunately make it rebuild fish instead of using the binary cache, but it imports the profile at the same point that NixOS loads the profile info, which means it will run init in the exact same order, including having the profile set up prior to any `conf.d` scripts.

If you don't want to rebuild fish, or want to install fish outside of nixpkgs, then https://github.com/lilyball/nix-env.fish/ is the next best thing. It's a fish plugin that does its best to set up fish with the same environment, in particular ensuring that the function/completion dirs pick up your nixpkgs config and sourcing nix-installed Fish conf.d dirs, but it has to repair stuff after the fact so init doesn't run in the exact same order.

**Comment by Strum355** [comment]
Forgot to follow up with this, but I believe I had `$NIX_PATH` set (relic from sharing configs across systems, not great I know). Unsetting it solved it, thanks for the pointer @lilyball
