### ISSUE TITLE
nix-env -qP doesn't list attribute names

### ISSUE THREAD

**Issue by domenkozar** [NixOS/nix#642]
It's probably since it doesn't know to what attributes those packages belong, but should we then make the flags conflict with a nice message?

```
$ nix-env -qP
0  atom-1.0.4
6  bind-9.9.5-W1
2  libnotify-0.7.6
3  pm-utils-1.4.1
1  python2.7-deluge-1.3.11
5  rbtools-0.7.2
4  zed-1.1.0
```

**Comment by vcunat** [comment]
Related: #521.

**Comment by fiksn** [comment]
BTW: what do the numbers that are printed instead of attribute name mean?

Guess one can always "reverse engineer" through "nix-env -qaP", but it'd be great if nix-env did it by itself. If name (-version) matches then you (probably) have the correct hit. I know it is still "fuzzy" but IMHO more consistent than before. Either that or prevent -P in such cases like Domen said.

**Comment by domenkozar** [comment]
Haven't seen this since
