### ISSUE TITLE
nix develop impure by default, contrary to documentation

### ISSUE THREAD

**Issue by charles-dyfis-net** [NixOS/nix#6439]
**Describe the bug**

The man page spawned by `nix develop --help` documents an option `--impure` to allow access to environment contents not listed in a flake's devShell. No `--pure` is available.

However, _the default behavior is impure_: `nix run github:NixOS/nix# develop` leaves `$HOME/.nix-profile/bin` in the PATH, meaning the _default behavior_ is `--impure`.

**Steps To Reproduce**

As of this writing, `nix run github:NixOS/nix# -- --version` emits `nix (Nix) 2.9.0pre20220422_7f814d6`

1. Using any flake-enabled version of Nix, in an environment that already has `$HOME/.nix-profile/bin` in the PATH, run:
   ```
   testCmd() { printf '%s\n' "${PATH//:/$'\n'}"; }
   nix run github:NixOS/nix# -- develop github:NixOS/nix# -c bash -c "$(declare -f testCmd); testCmd"
   ```
   Observe that the final lines of output include `$HOME/.nix-profile/bin`, `/nix/var/nix/profiles/default/bin`, and `/run/current-system/sw/bin`.
2. Compare to `nix-shell --pure`:
   ```
   testCmd() { printf '%s\n' "${PATH//:/$'\n'}"; }
   nix-shell --pure --run "$(declare -f testCmd); testCmd"
   ```
   ...properly emits system- and user-specific paths.

**Expected behavior**

Either behavior should be pure by default (user-account and system-provided locations should not be in the PATH inside a `nix develop` shell), or a `--pure` flag should be provided and `--impure` should be documented as off-by-default.

**`nix-env --version` output**

Observed between Nix 2.4 and 2.9.0pre20220422, inclusive. Picking one of the (many) revisions against which this has been observed:

```
nix-env (Nix) 2.5.0pre20211206_d1aaa7e
```

**Comment by tomberek** [comment]
Thanks for the report. The situation can be confusing. Sadly it is difficult to provide a completely satisfactory solution to this problem. 

First I’ll directly address your points and hopefully clarify a few things. The purity option you are looking for is “-i”/“—ignore-environment”. The “—impure” option you refer to is in the evaluation options section, meaning that it impacts how the Nix code is evaluated, not necessarily about the purity/impurity of the shell you are given. The use of the letter i here is unfortunate, perhaps that needs to be improved. Perhaps we change the wording to use “pure-eval”/“impure-eval” to clarify this. Or better docs. 

Next is the UX issue. There is an easy confusion between purity of eval and of the resulting shell. The default at the moment is an impure shell, because it seems that is what people want more often. They want their other tools to be in PATH ( “why can’t I use git, ls, or mkdir?!” ) and so some exceptions are made. Another example is HOME. This is in line with the idea that they are using “nix develop” to develop, not debug a build. Then there are other issues like people using other SHELL, or wanting to preserve tab-completion, and so on. 

It should be better clarified what options are available since no single solution meets everyone’s use case, though we try to make the simplest commands meet most of them: (somewhat in order of pure to impure environment)

1) nix build
1) env -i bash --norc --noprofile ; nix develop -i
1) nix develop -i
1) nix develop
1) nix shell (only adjusts PATH)
1) nix shell nixpkgs#bashInteractive --command bash ; . <(nix print-dev-env)
1) . <(nix print-dev-env)

Then when you bring in other complications like people wanting to use direnv/lorri/editors/IDEs or that their SHELL configuration/bashrc is still respected and that each SHELL has its own quirks; well, it is not always clear what the best option is.

**Comment by charles-dyfis-net** [comment]
Per above, this is not in fact a bug; closing ticket. Apologies for the noise.

**Comment by synalice** [comment]
The UX here is not just terrible, but actually horrifying... There is a ton of legacy documentation talking about `nix shell --pure`. And then you introduce `nix develop` as a replacement where the flag not has a completely different name. And when you search for it you find `--impure` and think to your self that `nix develop` is pure by default. But it isn't.

I understand that nix is kind of niche, and flakes are _technically_ experimental, but that' not an excuse, when there is already so much stuff built around them. Just make them stable, god damn it. It's all really frustraiting.

I _want_ to love nix. Hell, there isn't any alternative to it really. But you need to get you s together.

**Comment by qknight** [comment]
@synalice You are right with your remarks. The '--pure' for `nix develop` is called `--ignore-environment`

    --ignore-environment / -i Clear the entire environment (except those specified with --keep).
