### ISSUE TITLE
Feature request: Provide `-eA`, inversible of `-iA`

### ISSUE THREAD

**Issue by matthiasbeyer** [NixOS/nix#648]
As discussed [here](https://github.com/NixOS/nixpkgs/issues/9937) we really should have a `-eA` option, to uninstall packages with attr path. Would be a nice feature, really!

**Comment by gleber** [comment]
Please do! I am maintaining my environment with Nix and mismatch explained in #9937 is making it really annoying to writing install + uninstall scripts.

**Comment by Ericson2314** [comment]
I'm sympathetic, but what should the semantics be? For example, if one does `nix-env -iA foo.bar`, and then `nix-channel --update`, `foo.bar` might no longer correspond to the installed package.

**Comment by matthiasbeyer** [comment]
@Ericson2314 If the channel update moved the attr path, the command should simply fail.

My usecase is: I install something via nix-env in userspace because I want to try out. If it doesn't work, I remove it. I don't want to guess around about how to remove it, I want to remove it in the same way I installed it.

For me, "long term installed packages" go to my configuration.nix - so I won't have the issue you described.

**Comment by gleber** [comment]
It is even more pronounced with Haskell packages. E.g. I want to install and uninstall structured-haskell-mode:

```bash
nix-env -f "<nixpkgs>" -iA haskellPackages.structured-haskell-mode
nix-env -e structured-haskell-mode
```

I **can not** install it in other way than with `-iA haskellPackages.structured-haskell-mode` (AFAIK just `-i` won't work since haskell packages are not exported at top level), but I **have to** uninstall with `-e structured-haskell-mode`.

In this case there's a mismatch which is impossible to overcome with current feature set.

**Comment by Ericson2314** [comment]
Yeah I'm totally with you both on the practical need. And I don't the way things currently work well is good either. In fact, I rather have it that Nix did not know about names and versions at all---rather that they were just extra "uninterpreted" fields in a derivation and just a nixpkgs ideom. While they are a fine bit of a metadata on a package, they are a woefully inadequate way to reference derivations, not the least bit because there is nothing stopping two derivations from having the same name.

> If the channel update moved the attr path, the command should simply fail.

"moving" is the wrong word. If even a transitive dependency changes, the attr path now points to a totally different derivation as far as Nix is concerned. The point is the most natural definition of `-eA`--- uninstall the derivation at that path if it is installed---does not do what we want.

Here in lies the heart of the problem---it's awkward one has packages installed that one no longer has the nix expression source for. We currently use names to refer to installed packages, because doing so doesn't rely on having the source around, and well somebody must have thought it was the best of the poor options that didn't require keeping the source.

I think just biting the bullet and finding a way to pin the source would be better. For one, then `-eA` is guaranteed to find the exact package one installed just be having it look up that path in all pinned sources. Second of all, there is the well-known awkward situation where channel updates leak through nixos rollbacks. and doing so could help plug that (keep a copy of channel for old revision, and old configuration.nix)

There are some design hurdles, namely that nix-channel lives on top of nix and it would be nice to keep it that way, but I don't see any other path going forward that isn't more of a hack.

**Comment by thomastjeffery** [comment]
So.... What happened to this?? Is there a workaround? How do I remove a package that does not have a toplevel name??

**Comment by peti** [comment]
This feature is impossible to implement right now. A package that's been installed into a profile has no relationship whatsoever to the attribute name it was stored under in Nixpkgs at the time that `nix-env` command was run. The attribute name is meaningless on that layer; it's not store anywhere and even if it were then that still wouldn't guarantee that it would be useful because attributes get renamed and moved around in Nixpkgs all the time.
