### ISSUE TITLE
A way to list all locally realised fixed output derivations

### ISSUE THREAD

**Issue by lucasew** [NixOS/nix#6508]
**Is your feature request related to a problem? Please describe.**
I am looking for a way to PoC a distribution of fixed output derivation outputs over a distributed system like torrent or IPFS but AFAIK there is no way to list all the fixed output derivation outputs in my system to seed.

**Describe the solution you'd like**
A way to get this using `nix-store --query` or at least discover a hidden gem to get this from `/nix/var/nix/db/db.sqlite`

**Describe alternatives you've considered**
```sql
select path, ca from ValidPaths limit 10; 
```
but I am unsure about how to read the ca column

**Additional context**

An example query result limiting by 10 items returns the following:

```
/nix/store/9krlzvny65gdc8s7kpb6lkx8cd02c25b-default-builder.sh|fixed:r:sha256:1a7grsnd09snvdrp7nx5xlzap1b9982k4a2fghpbm2k9qn9q71ai
/nix/store/b7irlwi2wjlx5aj1dghx4c8k3ax6m56q-busybox.drv|text:sha256:0c6p0g0zhnx9k9if3g341mg9z91gjpkzzcm48a9y17p9n17pn99c
/nix/store/bzq60ip2z5xgi7jk6jgdw8cngfiwjrcm-bootstrap-tools.tar.xz.drv|text:sha256:1sxgfd3q7rga8bady9c6nlyppzigv7rhb34392m7xr0jgkr6cxm9
/nix/store/dsyj1sp3h8q2wwi8m6z548rvn3bmm3vc-builder.sh|fixed:r:sha256:1hsb5r8l6ip56sfgshdvlb5cpv76cr155cdvrpn7bpqvin7rm6dk
/nix/store/mjjy30kxz775bhhi6j9phw81qh6dsbrf-move-docs.sh|fixed:r:sha256:1zzwbz7j664hiicjvaf9cc9z9wcgmri6zfgjh6lmh6bzry75f851
/nix/store/kxw6q8v6isaqjm702d71n2421cxamq68-make-symlinks-relative.sh|fixed:r:sha256:0ss3ld51pbgw3sh3bcqk47gavqgqjgd344hkdda5arfjiz36860q
/nix/store/rvg5a5nwa7cihpmbzlwzh931w3g4q108-compress-man-pages.sh|fixed:r:sha256:09hgpklajjiy01rxgqz70dmq8ivcx2f16s41gqhj6frc7d446yip
/nix/store/4ygqr4w06zwcd2kcxa6w3441jijv0pvx-strip.sh|fixed:r:sha256:1022d5zjp1vrmxfj7nbj596d408ll51nbqgm6m192fxsk24k8rsg
/nix/store/cickvswrvann041nqxb0rxilc46svw1n-prune-libtool-files.sh|fixed:r:sha256:16y8hwyxqvcjpsgjzqm5qgbzrlrh2jijpzcz01vb28z8iwzvhc6h
/nix/store/8zxndz5ag0p6s526c2xyllhk1nrn4c3i-audit-tmpdir.sh|fixed:r:sha256:0bf6z2xh8fkfcgh719mv7hfarwp4kwf660nil64zi8m08p3i7l9p
```

**Comment by thufschmitt** [comment]
I don’t think it’s possible to get exactly the FO derivation outputs because Nix doesn’t make a difference between a FO derivation output and any other kind of content-addressed path (for example anything added to the store at eval-time).
The best you can do if you really want that is to list all your derivations and for each of these get their outputs if they are CA (which requires a bit of scripting). But that only takes into account the paths whose deriver is still in the store.

If you’re okay with taking all the content-addressed paths, then either getting dirty with the sqlite db (just `select path from ValidPaths where ca is not null;`) should do it, or if you can afford something less hacky but slower, `nix path-info --json --all | nix run nixpkgs#jq -- -r '.[] | select(.ca) | .path' should have the same effect

**Comment by lucasew** [comment]
That's what I tried [1]

I was just not sure if that value can be used in that way

[1] https://github.com/lucasew/playground/blob/master/nix/ls-fixed-output

**Comment by thufschmitt** [comment]
Ah indeed :) Yes, that looks good.

Closing since I don’t think there’s a need for anything fancier than hooking into the db or filtering the output of `path-info --all`. But feel free to reopen if you think there’s more to do on our side
