### ISSUE TITLE
Nix-env tries to create "homeless-shelter" directory in root

### ISSUE THREAD

**Issue by leftaroundabout** [NixOS/nix#670]
Following [this guide](https://nixos.org/wiki/How_to_install_nix_in_home_%28on_another_distribution%29), I managed to install Nix in the home folder on a machine where I don't have root access. Nice. (It it require [some funny manual tweaks, mind...](https://github.com/NixOS/nix/issues/566))

After everything was in place and `$HOME/.nix-profile/bin` in my `$PATH`, I logged in freshly to see if it works.

```
$ nix-env --verbose -qa git
error: creating directory ‘/homeless-shelter’: Permission denied
```

Well, it's kind of obvious that it doesn't have permission to create a directory `/homeless-shelter`, but why does it try this? How can I make `nix-env` use only user-accessible paths?

**Comment by rened** [comment]
I am having the same problem. The directory name is explicitly used because it does not exist (https://github.com/NixOS/nix/blob/1f735a34406c1856fd2f6f9a522a06b429c4f799/src/libstore/build.cc#L1702), but the problem remains: why does nix try to create it?

**Comment by Ericson2314** [comment]
This problem is somewhat familiar, I think the issue is external software which see a dangling $HOME, and thus try to create it. Try checking bashrcs (your user or global) for any lines that might do this (that is my best recollection on where the culprit was found before)?

**Comment by aTick** [comment]
I am having the same issue with nix-managed install of nix, version 1.11.6, installed via a bootstrap nix (also version 1.11.6), following the instructions in (this section)[https://nixos.org/wiki/How_to_install_nix_in_home_(on_another_distribution)#Manual_Installation] of the instructions linked in the original section.

It appears that the nix-managed version has several paths which default to being under "/homeless-shelter". This seems strange to me, given that comments and documentation state that this directory is used because it should not exist.

With my install, the offending file is "$HOME/.nix-profile/lib/perl5/site_perl/5.22.2/x86_64-linux-thread-multi/Nix/Config.pm". Setting the referenced shell variables to their appropriate directories (NIX_STATE_DIR, NIX_MANIFESTS_DIR, NIX_LOG_DIR, NIX_CONF_DIR, NIX_STORE_DIR) under $HOME/nix resolved this issue for me.

I'm very new to nix, so I don't know if this is the preferred way to resolve this issue, if there are options that should have been given when installing nix that are not called out in the referenced instructions, or if a code/config change to nix is necessary. Hopefully someone more knowledgeable than I can update this issue accordingly.

Let me know if any more detail is required.

**Comment by benvvalk** [comment]
@aTick:

Thanks! I was also getting the error about not being able to create the `/homeless-shelter` directory, and the your tip helped me get past the problem.

Instead of manually editing `.../Nix/Config.pm`, I instead set some the Nix environment variables you mentioned, prior to running `nix-env -i ...`:

```
export NIX_STORE_DIR=$HOME/nix/store
export NIX_STATE_DIR=$HOME/nix/var/nix
export NIX_LOG_DIR=$HOME/nix/var/log/nix
```

**Comment by winny-** [comment]
Is there a better workaround than asking users to change their nix installation settings?

**Comment by peeech** [comment]
In my build I have also experienced a similar error:
```
Internal Error: EACCES: permission denied, mkdir '/homeless-shelter'
Error: EACCES: permission denied, mkdir '/homeless-shelter'
```
It turns out that my builder was setting a value of $HOME to `/homeless-shelter'`, which it didn't have permissions to create.
My workaround was to add a line in a buildPhase of a derivation:
```
    buildPhase = ''
      # this line removes a bug where value of $HOME is set to a non-writable /homeless-shelter dir
      export HOME=$(pwd)
      ...
```
That way entire build happens in a "source" directory which bulder has permissions to write to.

**Comment by mash808** [comment]
da
