### ISSUE TITLE
error: renaming '/nix/store/add-NUMBER/x' to '/nix/store/HASH-NAME'

### ISSUE THREAD

**Issue by bjornfor** [NixOS/nix#6823]
**Describe the bug**

I *think* this happens when auto-GC cannot free enough space.

Here it's represented by `nix flake update --commit-lock-file`, but it happens with `nix-build` too (the stable CLI).

```
+ nix flake update --commit-lock-file
running auto-GC to free 230875004928 bytes
waiting for the big garbage collector lock...
finding garbage collector roots...
deleting garbage...
deleting unused links...
note: currently hard linking saves -0.00 MiB
error: renaming '/nix/store/add-14603-0/x' to '/nix/store/zkjybwz3wlc0vsyjsnpgi5nmln8vb48g-source'
(use '--show-trace' to show detailed location information)
```

**Steps To Reproduce**

1. Configure Nix to do auto-GC, for example with `min-free = 17179869184  # 16 GiB` in `/etc/nix/nix.conf`. (I also have a `max-free = ` setting, but I don't think that matters.)
2. Fill up the disk.
3. Start a build and watch auto-GC kick in. (And additionally, if my theory is correct, auto-GC must fail to actually free any/enough space.)
3. Hopefully you'll see the above error.

**Expected behavior**
If the problem is that after auto-GC there isn't actually more/enough space available, then Nix should say that (e.g. `error: insufficient free disk space, aborting build`) instead of a very low-level `error: renaming A to B` message. (It's not like the disk is _full_, it just has less than `min-free =` available, so it doesn't make sense to me that a rename operation should fail.)

**`nix-env --version` output**

```
$ nix-env --version
nix-env (Nix) 2.9.0
```

**Comment by agbrooks** [comment]
We've been encountering the same problem under similar conditions.

Our steps for reproducing the issue are:

1. `nix-collect-garbage -d`
2. Increase `min-free` above `total disk size - store size`, then restart Nix daemon to pick up config.
3. Use `builtins.fetchGit` to acquire some sources not currently in the store. 

Interestingly, neither `builtins.fetchTarball` nor `builtins.path` seems to exhibit this problem. I'm not sure if this problem is specific to `builtins.fetchGit`. In your situation, are you also using `builtins.fetchGit` somewhere or something else, @bjornfor ?

Not sure if it makes any difference, but we're on Nix 2.9.1 and running Nix on an Ubuntu installation.

For a `broken.nix` containing `builtins.fetchGit { url="https://github.com/NixOS/nixpkgs.git"; ref="master"; }`, running `nix-build --debug broken.nix` gives us:
```
did not find cache entry for '{"name":"source","type":"git","url":"https://github.com/NixOS/nixpkgs.git"}'
locking path '/home/andrew.brooks/.cache/nix/gitv3/061ac0jn4zjqj359dh25hfi4qs1ny94z1bbkv2kh9x7n2y2c50p5.lock'
lock acquired on '/home/andrew.brooks/.cache/nix/gitv3/061ac0jn4zjqj359dh25hfi4qs1ny94z1bbkv2kh9x7n2y2c50p5.lock.lock'
lock released on '/home/andrew.brooks/.cache/nix/gitv3/061ac0jn4zjqj359dh25hfi4qs1ny94z1bbkv2kh9x7n2y2c50p5.lock.lock'
using revision 0f147b79e5621fcb7cda40acc91fcb4c99c2a163 of repo 'https://github.com/NixOS/nixpkgs.git'                                                        
did not find cache entry for '{"name":"source","rev":"0f147b79e5621fcb7cda40acc91fcb4c99c2a163","type":"git"}'
killing process 11769                                                                                                                                         
acquiring write lock on '/nix/var/nix/temproots/11785'                                                                                                        
locking path '/nix/store/zp1ir9c5wgc96dv8b5ml986i8rrli0nw-source'                                                                                             
lock acquired on '/nix/store/zp1ir9c5wgc96dv8b5ml986i8rrli0nw-source.lock'                                                                                    
running auto-GC to free 15570311168 bytes                                                                                                                     
finding garbage collector roots...                                             
got additional root '/nix/store/65hafbsx91127farbmyyv4r5ifgjdg43-glibc-2.33-117'
got additional root '/nix/store/65hafbsx91127farbmyyv4r5ifgjdg43-glibc-2.33-117'
--- SNIP ---
got additional root '/nix/store/lxpdbaazqd2s79jx6lngr8nak2rjdaq1-glibc-2.34-210'
got additional root '/nix/store/59ljqxx0gzc0xzac8pwl5a765j3zy87f-nix-2.9.1'
got additional root '/nix/store/scd5n7xsn0hh0lvhhnycr9gx0h8xfzsl-glibc-2.34-210'
got additional root '/nix/store/6mn0a0hfzzamhfbwlkadi8ii3k66rqic-libkrb5-1.19.3'
got additional root '/nix/store/aks5q9criaswch436zwfhc136k6w86jm-keyutils-1.6.3-lib'
got additional root '/nix/store/lxpdbaazqd2s79jx6lngr8nak2rjdaq1-glibc-2.34-210'
got additional root '/nix/store/yy2gk4ivbfqf8fnnfp6n8x5dm7f9x29r-aws-c-compression-0.2.14'
reading temporary root file '/nix/var/nix/temproots/11785'
got temporary root '/nix/store/zp1ir9c5wgc96dv8b5ml986i8rrli0nw-source'
deleting garbage...
cannot delete '/nix/store/yxwdqanz54qanybs8mvp3p4769aqafn4-user-environment' because it's a root
cannot delete '/nix/store/59ljqxx0gzc0xzac8pwl5a765j3zy87f-nix-2.9.1' because it's a root
cannot delete '/nix/store/zp1ir9c5wgc96dv8b5ml986i8rrli0nw-source.lock' because it's a temporary root
cannot delete '/nix/store/43s1dwafm1bja60hhpcbf29j56wcfh2a-user-environment' because it's a root
deleting '/nix/store/add-11785-0'
cannot delete '/nix/store/svxx373rqp1i4namvyz3jbx6m87adcjb-flake-registry.json' because it's a root
deleting unused links...
note: currently hard linking saves 21.85 MiB
GC roots server shutting down
lock released on '/nix/store/zp1ir9c5wgc96dv8b5ml986i8rrli0nw-source.lock'
error: renaming '/nix/store/add-11785-0/x' to '/nix/store/zp1ir9c5wgc96dv8b5ml986i8rrli0nw-source'
(use '--show-trace' to show detailed location information)
```

To my untrained eye, it looks like Nix should be adding a lock on `/nix/store/add-11785-0` (or maybe referencing it from a temp root? not sure) to prevent premature garbage collection. Because it doesn't, the GC deletes this directory before `fetchGit` can complete.

This bug is real headache when you're working on a shared Nix dev box with a lot of disk pressure and using `fetchGit` to access private git repos. Unfortunately, the cryptic error message is also pretty off-putting, especially to inexperienced Nix users.

**Comment by bjornfor** [comment]
Yes, I'm using builtins.fetchGit.
