### ISSUE TITLE
Is nix suitable as a second tier package manager?

### ISSUE THREAD

**Issue by fhaust** [NixOS/nix#691]
I am currently in the process of setting up a development environment in a centrally managed Linux system. The current setup looks like this:
1. A centrally managed _Ubuntu 14.04_ installation. I can't change anything here, but the Support team is supportative.
2. A per group volume that is used to house common files and libraries.
3. A per user folder that contains projects from a central svn. There is some tooling in place to facilitate building projects from this folder.

I would like to use nix to replace the second layer of this setup. That is: I want _nix_ to provide binaries and libraries for the group. Currently this is handled manually. Other groups use `stow`.
In the long term, we might include _nix_ in the build process for our own projects. A plus would be if after an initial setup step, use for new group members should be "minimal invasive". 

My current plan of action:
1. Install nix in the group volume. Probably using the [manual installation](https://nixos.org/wiki/How_to_install_nix_in_home_%28on_another_distribution%29#Manual_Installation). Using `proot` is possible, but is an unnecessary hassle for other users and I don't mind extra compiliations.
2. Include a _how to setup nix_ in our initial setup procedure. Set up everything so that current projects can access libraries and header files.
3. ???
4. Profit!

The goal of this issue is to gather recommendations and evaluate the general feasibility of the plan of action outlined above.

Relevant resources:
- [Installing Nix as non root](https://nixos.org/wiki/How_to_install_nix_in_home_%28on_another_distribution%29)

**Comment by Ericson2314** [comment]
Two questions:
1. Are the are multiple computers on the network which share the per group volumes, or is this actually a single machine? (I assume the former, but just want to double check.)
2. Do you care whether normal users can use nix, or is a central CI tool that uses nix to build the repo fine?

I ask because it is a little tricky at the moment for multiple machines to share a store. In general, check out https://github.com/NixOS/nix/issues/324 for more discussion.

Of particular note (also mentioned in that thread) is `unshare`, which allows on to use user namespaces (no special perms needed) to accomplish what proot does without extra software or the overhead. https://www.mail-archive.com/nix-dev@lists.science.uu.nl/msg17108.html goes into more detail.

**Comment by fhaust** [comment]
1. Multiple computers and users have access to the group volumes. They get mounted at boot time. Everybody from the group has read/write access to the volumes.
2. I should have specified: I want nix to provide development environments to the users. For now one default environment is fine, but if this proves to be successful nix's profiles might get used.

Reading #324 now.

**Comment by Ericson2314** [comment]
Don't worry about ACLs. You're choices then are:

1. Trust NFS locks and use multi-user mode: have admin create separate user accounts for nix daemon and the build users. The build users are created as normal. Nix daemon is normally run as root, but I believe the only thing necessary is that the only the daemon user has write access to the store. If you want to use sandboxed builds, you will want to run the nix daemon in a user namespace, in which case might as well use `/nix` so you can have `cache.nixos.org` binaries. Users must have the store mounted in the same place as the daemon, so if you use `unshare` to mount `/nix` for the daemon, users need to do that too.

2. Single user mode: Everybody has their own store, which of course increases space usage baring extra effort. A CI service can publish a binary cache, however, which at least will save CPU time. `unshare` is definitely not necessary in this case.

I'd start with route 2 as its simpler. Once your coworkers learn to love nix or admins complain about space usage, switch to 1 ;).

> Just checked, but apparently I can't use unshare. `unshare -m /bin/bash` gives me an Operation not permitted error.

That should fail, because root is needed for plain mount namespace. Try `unshare -rm /bin/bash`. `-r` implies `-u`, which creates a new user namespace so root can be spoofed, and additionally maps the calling user as root. Conceptually there is an ordering of namespace creation here so that once the user namespace exists, the new root "user", i.e. the calling user, has permission to make a mount namespace.

Hopefully it works with `-r` but there is a some chance it won't I should admit. I tried to get Nix working at school on Debian without proot and it didn't work for reasons I couldn't figure out. According to the `unshare` C function man page, it's not an actually permission error but a few other things that that they lumped onto `EPERM` (yay Linux!). None of them seemed to apply to my school environment, but maybe they would for you.

**Comment by fhaust** [comment]
I fear that adding build users is out of the question. Is it possible to get by without having builders and the nix daemon?

**Comment by fhaust** [comment]
So i started with getting the required dependencies and a nix tarball. After

    /tmp/nix $ ./configure --prefix=/volume/nix --with-store-dir=/volume/nix/store --localstatedir=/volume/nix/var
    /tmp/nix $ make
    /tmp/nix $ make install

The nix tools are installed in the volume and I get them on my path with
    
    $ export PATH=$PATH:/volume/bin
    $ source /volume/etc/profile.d/nix.sh

Setting up channels:

    $ nix-channel --add https://nixos.org/channels/nixpkgs-unstable
    $ nix-channel --update

At this point I should be set up and ready to install stuff, right? But apparently there is a problem with the `coreutils-8.24` package in combination with our linux setup that prevent the tests to complete successful which leads to a failed install. Can I somehow disable the tests? Are they necessary?

**Comment by vcunat** [comment]
Tests are there just to uncover (potential) problems. You can disable them for coreutils e.g. by a combination of packageOverrides, overrideDerivation and `doCheck = false;` https://nixos.org/wiki/Nix_Modifying_Packages#Overriding_Existing_Packages

**Comment by fhaust** [comment]
{                                                                                                                                                                                                                                             
      packageOverrides = pkgs: {                                                                                                                                                                                                                  
        coreutils = pkgs.coreutils.override {                                                                                                                                                                                                     
          doCheck = false;                                                                                                                                                                                                                        
        };                                                                                                                                                                                                                                        
      };                                                                                                                                                                                                                                          
    } 

in `.nixpkgs/config.nix` yields:

    error: anonymous function at /volume/nix/store/q8913s5nwwyvinpbfgcr20rjldbyah1c-nixpkgs-16.03pre71332.f490186/nixpkgs/pkgs/tools/misc/coreutils/default.nix:1:1 called with unexpected argument ‘doCheck’, at /volume/nix/store/q8913s5nwwyvinpbfgcr20rjldbyah1c-nixpkgs-16.03pre71332.f490186/nixpkgs/lib/customisation.nix:56:12

**Comment by fhaust** [comment]
The `doCheck` variable exists in the coreutils nix expression. So my guess
is that there is another path part I have to specify?
Am 11.11.2015 2:36 nachm. schrieb "Vladimír Čunát" <notifications@github.com

**Comment by vcunat** [comment]
@fhaust: it's not a parameter. You need to use `coreutils = pkgs.lib.overrideDerivation pkgs.coreutils {`

There may still be some other problems...

**Comment by rened** [comment]
This worked for me:

{
   packageOverrides = pkgs: rec {
       coreutils = pkgs.stdenv.lib.overrideDerivation pkgs.coreutils (oldAttrs : {
           doCheck = false;
       });
   };
}




Am 11.11.2015 um 15:37 schrieb Vladimír Čunát <notifications@github.com>:

**Comment by vcunat** [comment]
Ah, yes, I forgot you need the `oldAttrs` extra parameter.

**Comment by fhaust** [comment]
This seems to work. Thank you.

Does it make sense now to install nix into the new environment?
Am 11.11.2015 3:58 nachm. schrieb "Vladimír Čunát" <notifications@github.com

**Comment by Ericson2314** [comment]
@fhaust If you can't do build users, then you want to go with my second option, which doesn't require daemon, daemon user, or build users.

Did you try `unshare -rm /bin/bash`? I'm very curious if it will work for somebody else :).

**Comment by fhaust** [comment]
There is no `-r` option our unshare:

    $ unshare -rm /bin/bash
    unshare: invalid option -- 'r'

This is on Ubuntu 14.04.
Am 11.11.2015 16:26 schrieb "John Ericson" <notifications@github.com>:

**Comment by Ericson2314** [comment]
Ah, I checked the man pages and 14.10 is the first version to have user namespaces it seems :(.

**Comment by fhaust** [comment]
Trying to understand nix expressions here: is the `rec` in the expression above necessary?

Some things:

1. With a non-chroot single-user installation each user would have a nix store in a separate path. Afaik that means that I can't share a central binary store.
2. I tried to naively share a nix installation in the group volume. I guess it could be made to work when there is one privileged user who is able to install packages. 
3. `nix-shell` apparently doesn't respect the `storeDir` and `stateDir` overrides I did for `nix`.

I guess nix is just not meant to be installed in a position that is not `/nix` :(

**Comment by rened** [comment]
@fhaust I had the same problem with the non-respected `storeDir`/`stateDIR`. This shell script ([gist](https://gist.github.com/rened/5285d45639988f437b71)) summarizes my latest attempt, explicitly setting the paths in `.profile` on login.

But I have since moved to looking into nix within lxc containers, as I simply can't get this to work...

**Comment by vcunat** [comment]
> I guess nix is just not meant to be installed in a position that is not /nix :(

Mainly it's little tested, I believe.

**Comment by fhaust** [comment]
Which is basically "not (yet) usable for this use case". I don't mind
messing around with nix, but spending three days without real results
doesn't convince my superiors to consider nix as an replacement for our
current system. No offense meant.
Am 12.11.2015 3:54 nachm. schrieb "Vladimír Čunát" <notifications@github.com

**Comment by vcunat** [comment]
As I understand it, the only bug seen in this thread is (3) nix-shell. (Some coreutils tests are filesystem sensitive, so that's more about working around upstream issues.)

**Comment by fhaust** [comment]
To be honest I wrote the last post after rage 'rm - rf'ing my nix
installation while my boss stared down my neck.

Is there a wiki page yet devoted to the whole "multi-user non-root nix on a
shared (nfs) volume with a trusted user group"?

Else I would create one to summarize the goals and track my process.
Am 12.11.2015 6:22 nachm. schrieb "Vladimír Čunát" <notifications@github.com

**Comment by Ericson2314** [comment]
@fhaust Sorry to here that. Most of the pieces are small, easily-fixable bugs, but I completely understand that the sum total of all that is rather more annoying. "Institution-wide" use for nix like this comes up fairly often, and I agree it should be easier/better supported, if for no reason than this is an essential component for Nix gaining wider adoption.

I don't know of any wikipage for that, so I'd be fine if you make one. I should probably also add something about `unshare` to the non-`/nix` page.

**Comment by fhaust** [comment]
So ... some time has passed and I have used a personal instance of `nix` based on the `proot` approach for a while now. It is working quite well I have to say.

I have the following lines in my `.zshrc` and so far haven't had problems with it:

    if [ ! -d /nix ]; then
      exec proot -b $HOME/.nix:/nix /bin/zsh
    fi
    if [ -d $HOME/.nix-profile ]; then
      source $HOME/.nix-profile/etc/profile.d/nix.sh
      export MANPATH=$MANPATH:$HOME/.nix-profile/share/man
    fi

Next step would be share the `store` with several users.

**Comment by rasendubi** [comment]
(triage) any updates?

**Comment by Ericson2314** [comment]
Doubt it :/

**Comment by fhaust** [comment]
I had some success with using `proot` to replace `/nix` on a university
network. Set up the shell config so that it automatically runs in an proot
environment.

This if course doesn't help sharing the repository between users.

Am 09.08.2016 01:58 schrieb "John Ericson" <notifications@github.com>:

**Comment by rrnewton** [comment]
We were trying to do this too, but eventually just talked one sysadmin into installing /nix and nix-daemon on some machines, and gave up on university machines where we could not do this.

We (at Indiana University) are still eager testers for an NFS-shared solution -- i.e. with a common group account to run the daemon -- if someone has a script to try.

**Comment by fhaust** [comment]
What I currently do is to have this in my `.zshrc`:

    if [ ! -d /nix ]; then
      exec proot -b $HOME/.nix:/nix /bin/zsh
    fi

This starts a new shell that thinks `/nix` points to `~/.nix`. This lets me use nix like it is supposed to and I can install the precompiled packages as a normal user. The only downside is that it uses up my quota, but I am not too concerned about that right now.

**Comment by edolstra** [comment]
Closing, nothing to be done here.
