### ISSUE TITLE
HTTP narinfo downloads don't seem to keep HTTP connection alive

### ISSUE THREAD

**Issue by roberth** [NixOS/nix#7011]
**Describe the bug**

When running `nix-store -r` to perform multiple substitutions, with `-vvv` to increase verbosity, I see many messages:

```
verify TLS: Nix CA file = '/etc/ssl/certs/ca-certificates.crt'
```

This _suggests_ that a new connection is established for every narinfo.

Both `cache.nixos.org` and cachix respond with HTTP/2 and without `Connection:` response headers, so they support keep-alive, as is to be expected.

Alternatively, the `verify TLS` messages may not be indicative of new connections being established. This seems unlikely.

**Steps To Reproduce**

1. `nix-store -r -vvv` on your favorite path
2. See many `verify TLS:` messages

**Expected behavior**

After establishing a (pool of) connections, no new TLS connections are made. All HTTP requests flow through the already opened connections, for minimal latency.

Same for nar downloads.

**`nix-env --version` output**

nix-env (Nix) 2.8.1

**Additional context**

**Comment by thufschmitt** [comment]
Duh, that would explain why some things are so slow :flushed: 

Hopefully it's just a matter of tweaking the right flag in libcurl :crossed_fingers:

**Comment by thufschmitt** [comment]
After some investigations (thanks @rapenne-s and @YorikSar for the help), it turns out that this message is just misleading: Nix prints it before fetching anything, but the underlying `curl` layer does all the required multiplexing in the background just fine – you can see that by only looking at the `curl:` messages from the `-vvvv` output and seeing that there's only
