### ISSUE TITLE
need a way to trust flake nixConfig -- `nix flake trust` or `nix flake metadata --trust`

### ISSUE THREAD

**Issue by colemickens** [NixOS/nix#7086]
**Is your feature request related to a problem? Please describe.**

Yes. I want to use nixConfig from my flake in CI. I'd like to be able to run a command on initialization that instructions nix to trust my flake nixconfig.

**Describe the solution you'd like**

A way to run `nix flake trust` or `nix flake metadata --trust` to automatically opt-in to the settings specified in the current-context's flake.

**Describe alternatives you've considered**
Not sure.

**Additional context**
n/a

**Comment by jlesquembre** [comment]
there is a `--accept-flake-config` flag, would that work in your case?

**Comment by colemickens** [comment]
Yes, it would. I guess its just yet another undocumented flag.

**Comment by thufschmitt** [comment]
> I guess its just yet another undocumented flag.

It is actually documented (both in https://nixos.org/manual/nix/stable/command-ref/conf-file.html#conf-accept-flake-config and https://nixos.org/manual/nix/stable/command-ref/new-cli/nix3-flake.html#flake-format).

However, we could make the "ignoring untrusted option" warning point to that flag to make it more discoverable since people who need this flag will _a priori_ be the people who see this warning
