### ISSUE TITLE
Incorrect linux grouping on Kali Linux.

### ISSUE THREAD

**Issue by fxfactorial** [NixOS/nix#736]
Just tried installing nix from source on Kali Linux, a security minded distro. 

Now trying to install normal packages, 

```shell
nix-env -i emacs
warning: the group ‘nixbld’ specified in ‘build-users-group’ does not exist
error: getting information about ‘/root/.nix-defexpr’: No such file or directory
root@osboxes:~/Downloads/nix-1.10# nix-channel --update
downloading Nix expressions from ‘https://nixos.org/releases/nixpkgs/nixpkgs-16.03pre71923.3087ef3//nixexprs.tar.xz’...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 6095k  100 6095k    0     0   150k      0  0:00:40  0:00:40 --:--:--  119k
warning: the group ‘nixbld’ specified in ‘build-users-group’ does not exist
unpacking channels...
warning: the group ‘nixbld’ specified in ‘build-users-group’ does not exist
error: the group ‘nixbld’ specified in ‘build-users-group’ does not exist
cannot unpack the channels at /usr/local/bin/nix-channel line 169.
```

**Comment by fkz** [comment]
This is used for multi-user installations as described in the manual: https://nixos.org/nix/manual/#idm46912468019984/. If you want to use single-user mode first which is probably simple to set up, you can set `build-users-group` in `/etc/nix/nix.conf` (also look into the manual for a description of this option).

**Comment by fxfactorial** [comment]
Okay, this config file was never created for me. 

:/# find . -name nix.conf
 
yielded nothing.

**Comment by fkz** [comment]
unfortunately I'm not the most competent person to answer since I never installed nix from source on a system which didn't already have nix installed before. So I'm not even sure if the warnings that `nixbld` doesn't exist are the real problem.
`nixbld` seems to be the default if `nix.conf` doesn't exist I think; I'm not sure if nix.conf is really needed.
Maybe you can try running `export NIX_DAEMON=` and see if that helps.
Otherwise, if noone else answers here you might want to try asking on the mailing list or maybe the IRC channel (links both on https://nixos.org/nixos/community.html).

**Comment by fxfactorial** [comment]
Okay, giving up on this, back to aptitude it is.
