### ISSUE TITLE
scripts: install base tools

### ISSUE THREAD

**Issue by urandom2** [NixOS/nix#7566]
> I am against hardcoding such core programs into packages, if other distros require them, add them to the nixos installation.

_Originally posted by @SuperSandro2000 in https://github.com/NixOS/nixpkgs/pull/208333#discussion_r1063508244_

we ran into an issue with non-nixos systems and runtime dependencies, where the underlying distro packages fundamentally different versions of coreutils and other base installed tools from nixos. it was recommended that this be done during nixos install, so I am spawning this ticket to track.

**Comment by roberth** [comment]
The linked discussion is about things that should or should not happen inside a derivation, but that decision can be made without changing Nix.
The installer was mentioned, but by its own nature, the installer can bundle any store paths or tools.
Without a problem in the Nix package manager itself, this issue will not be actionable.

**Comment by urandom2** [comment]
yep, happy to be overruled on this one; I was mostly looking for an authoritative view on what the installer can/should do.

also, I think @SuperSandro2000 was advocating for this to happen as part of `source $HOME/.nix-profile/etc/profile.d/nix.sh`, not during or before the install process. we clearly add and setup some binaries (`nix`, `nix-shell`, `nix-build`, etc.), so it strikes me that we /could/ add some core programs to that set?

**Comment by roberth** [comment]
> I was mostly looking for an authoritative view on what the installer can/should do.

It was unclear to me what the purpose of the issue was. It looked like a bug report for the installer or for Nixpkgs, hence my response.
If you think the installer should offer to install a default package at the very end, e.g. `nixpkgs#recommendedPackages`, that's something that could be discussed. In that case, please open a new issue and make the description a bit more complete so that both the context and the suggested solution are clear. I'd rather give it a fresh start rather than have a mostly irrelevant discussion at the top.

**Comment by urandom2** [comment]
I will also preface that this is mostly coming second hand from @SuperSandro2000, so I am tempted to wait for them to spawn that second issue.; but if I can see the benefits, so I will if they do not in a week or so.
