### ISSUE TITLE
Nix install script should check tarball checksum

### ISSUE THREAD

**Issue by jozko** [NixOS/nix#778]
Hi,

It would be nice if the Nix install script would check the downloaded tarball checksum. Here's a POC I wrote using shasum - https://gist.github.com/jozko/05741de96f5966d8be3b . For use in a generic installation script checksums file should be published with the Nix tarballs and then compared against downloaded tarball.

**Comment by davidak** [comment]
please create a pull request against the website repo.

https://github.com/NixOS/nixos-homepage/blob/master/nix/install.in

**Comment by copumpkin** [comment]
What's the checksum checking here? It doesn't seem like a security measure, because https already guards us against in-flight modifications, and if the server is compromised enough to serve you a bad tarball, it'll also serve you a bad hash.

I could imagine @edolstra signing the outermost script (once it has a hash of the tarball embedded in it) and us having a separate mechanism for verifying that signature, but without that I struggle to see the benefit of adding this.

**Comment by jozko** [comment]
Modified script was just an example. You can always publish checksums with the tarball or embed them into signed install script as you suggested. It's just another way of ensuring that I actually downloaded what I expected to download and that there were no problems during the download and/or writing the tarball to the filesystem.

**Comment by domenkozar** [comment]
This is now fixed: http://nixos.org/nix/install
