### ISSUE TITLE
error: mounting /dev/pts: Operation not permitted

### ISSUE THREAD

**Issue by xunfeng1980** [NixOS/nix#7791]
### Describe the bug
sudo HOME=/root /nix/store/lsr79q5xqd9dv97wn87x12kzax8s8i1s-nix-2.13.2/bin/nix-env -i /nix/store/lsr79q5xqd9dv97wn87x12kzax8s8i1s-nix-2.13.2 --show-trace
installing 'nix-2.13.2'
error:
       … while setting up the build environment

       error: mounting /dev/pts: Operation not permitted

### Steps To Reproduce
Ubuntu 20.04 install nix

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
output here
```

**Comment by thufschmitt** [comment]
Discussed during the Nix maintainers meeting on 2024-02-16.

@xunfeng1980 is that still an issue? If so, can you try with `--option sandbox false`?

<details>

Old and not actionable atm.

- @roberth: might be due to an old kernel (Ubuntu 20.03, so old)
- @thufschmitt: Might be our “can we sandbox” check that's not exhaustive enough and doesn't detect that it's not possible in that case
- Decision: Add a comment on the issue asking for status, and react based on that
