### ISSUE TITLE
could not resolve host name

### ISSUE THREAD

**Issue by matejc** [NixOS/nix#784]
I am trying to install Nix on Android (4.x), inside chroot environment, it compiles beautifully, sourcing nix.sh and `nix-channel --update` does its job, but installing anything produces error: https://gist.github.com/matejc/4c20bdb9becc60a97b17

Nix version 1.11.1

I can reproduce it with rootfs: ubuntu 14.04 core armhf and in arch linux armv7

Nix on Android has no special application in real life (for me it is just for fun) but since I used the same procedure as compiling and installing Nix on x86, there is a posibility that I found more serious issue

**Comment by t184256** [comment]
The issue is totally not Nix's fault, it's `/etc/resolv.conf` not being present on Android. [Creating it](https://github.com/t184256/nix-in-termux/blob/f5c0982052bd0ec985a811d2f7f6845bf6d3343a/nix-in-termux#L63) and [proot pseudo-bind-mounting it](https://github.com/t184256/nix-in-termux/blob/f5c0982052bd0ec985a811d2f7f6845bf6d3343a/nix-in-termux#L120) did the trick for me.
