### ISSUE TITLE
What to do about third party package managers?

### ISSUE THREAD

**Issue by fxfactorial** [NixOS/nix#785]
I can't seem to get a straight answer about this and its incredibly painful, my experience with nix has been overall of frustration. 

I need to add many OCaml packages to nix and I'm running into this trouble. 

Starting with: 
```nix

{ stdenv, ocaml, findlib, fetchzip, opam }:

stdenv.mkDerivation rec {

  pname = "lambda-soup";
  name = "${pname}-${version}";
  version = "0.5.1";

  src = fetchzip {
    url = "https://github.com/aantron/${pname}/archive/${version}.tar.gz";
    sha256 = "1g25f7gb31rsz493vbixvxyzrk67jyipkv91dix03ib5czmjgg9x";
  };

  buildInputs = [ ocaml findlib opam ];

  meta = with stdenv.lib; {
    description =
    "Lambda Soup is a functional HTML scraping and manipulation library";
    license = licenses.bsd2;
    platforms = ocaml.meta.platforms;
  };
}
```

But nix craps out with: 

```shell
opam pin add . -y
[ERROR] No OPAM root found at /homeless-shelter/.opam.
        Please run 'opam init' to initialize the state of OPAM, or specify
        '--root'.
        See 'opam init --help' for details.
Makefile:88: recipe for target 'install' failed
make: *** [install] Error 66
builder for ‘/nix/store/gd22q7fc7zs2zfj4gxaynzmiclj3pc46-lambda-soup-0.5.1.drv’ failed with exit code 2
error: build of ‘/nix/store/gd22q7fc7zs2zfj4gxaynzmiclj3pc46-lambda-soup-0.5.1.drv’ failed
```

With no indication of what to do. I don't see any docs either for third party packages either. Do I now need to write patch files for each thing that uses opam?

(No I don't want to use fetchFromGitHub)

**Comment by copumpkin** [comment]
First off, you'll probably find better support over at the nixpkgs issue tracker, since this Nix issue tracker is for the Nix suite of programs and far fewer people monitor this tracker.

Second of all, I don't know much about OPAM, but you'll find that most of the bigger package ecosystems define their own `build*` function and use that instead of the standard `mkDerivation`. This way, people factor out various sorts of hackery they need to do to convince their package builder to play nice with our immutable systems. So in your case (and judging from nixpkgs, it doesn't look like anyone's done this yet), I expect someone would need to write a `buildOpamPackage` that automatically invokes `opam` with some sort of configuration or hackery that convinces it to leave your home directory alone. I don't know what it wants to put there, but that might be as simple as telling it to put its `.opam` in `$TMP` or similar, and any other hackery that's needed.

Typically for most package managers I've, this won't generally involve actually patching the package being built, but just the manager. Or if you do need to patch the package being built, it's in a standard manner that doesn't mean you'll need a unique patch file per package.

Also, out of curiosity, why not `fetchFromGitHub`?

**Comment by vcunat** [comment]
Yes, this certainly doesn't belong into nix repo. Best file this against nixpkgs and ping people who changed OCaml stuff recently.

**Comment by fxfactorial** [comment]
Okay sorry for the wrong listing, will look what can be done.
