### ISSUE TITLE
Change in documentation - part with "Package manager"

### ISSUE THREAD

**Issue by Dregorio1** [NixOS/nix#8041]
## Problem

Hello. I started interest in nix because I thought that I would be able to remove completely others package managers. But on forum/discord. After few conversations, people convinced me that nix is only a build system.

For example when I want to use i3 (tilling window manager) I am not able to use nix for that.

So I am not able to remove e.g. Apt or snap completely and start using nix. 

## Proposal

The documentation should be corrected, because right now it kinda lies.

**Comment by balsoft** [comment]
You can use Nix as the only package manager on your system -- but it would probably require installing a different distribution. The most common option is [NixOS](https://nixos.org/manual/nixos/stable/), but there are also others (e.g. [not-os](https://github.com/cleverca22/not-os)).

As for installing i3 on your distro, that is also definitely possible, but you would have to alter your startx script so that it could find the location where Nix installed it (e.g. `$HOME/.nix-profile/bin/i3`).

**Comment by Dregorio1** [comment]
@balsoft Ok, but on Ubuntu you have APT or Snap and it works perfectly. It does not matter by which you "download" i3 and I do not need to add "the location". Anyway right now I think I started to understand what you mean. Thank you.

BTW. 
> You can use Nix as **the only** package manager

So nix can be use also as build system, right?

**Comment by Dregorio1** [comment]
@balsoft Thank you so much for clarification :)
