### ISSUE TITLE
Blacklisted store paths

### ISSUE THREAD

**Issue by shlevy** [NixOS/nix#812]
In the wake of the recent glibc vuln, it would have been nice to be able to say "if any new build takes a runtime dependency on the old glibc path, make it fail" to avoid silently keeping the vuln alive.

**Comment by edolstra** [comment]
The problem is that there can be any number of store paths that are vulnerable, and it's impossible to enumerate them all.

A long time ago I wrote a tool to scan the build-time dependency graph of a store path (as determined using `nix-store -qd`) for vulnerable packages, by applying checks like "if package X is version <= V and it doesn't have patch P applied, then it's vulnerable to CVE-xxxx-xxx". This never got very far though.

Last version of the blacklist scanner: https://github.com/NixOS/nix/commit/eb94581d399b8d0945b883b14c4a892fdab95dfc

Example blacklist: https://github.com/NixOS/nix/blob/9a7f95882c5e32ad5c41799016f749964221cad4/blacklisting/blacklist.xml

**Comment by shlevy** [comment]
How often in practice do you have versions of, say, glibc or openssl installed besides pkgs.glibc and the 32-bit versions thereof?

**Comment by edolstra** [comment]
A lot:
```
$ ls -ld /nix/store/*glibc-* | grep '^d' | wc -l
54
```

**Comment by cleverca22** [comment]
when i was cleaning up my system to change filesystems, i discovered 7 different GCC's in the closure of my ~/.nix-profile/

**Comment by copumpkin** [comment]
Ah, the wonders of `nix-env`!
