### ISSUE TITLE
MacOSX 13.3 upgrade broke nix

### ISSUE THREAD

**Issue by sw7892** [NixOS/nix#8128]
## Platform
- [x] macOS Ventura 13.3 M1 Max

## Additional information

Nix previously installed fine alongside home-manager, recent update to OS broke nix, ~/nix-profile directory missing. Volume not mounted. Newbie to nix so tried a reinstall - had to clean /etc/bash profiles; the install script worked until the error below.

## Output

<details><summary>Output</summary>

```log

I am executing:

    $ sudo HOME=/var/root /nix/store/8w0v2mffa10chrf1h66cbvbpw86qmh85-nix-2.13.3/bin/nix-store --load-db

to load data for the first time in to the Nix Database

/var/folders/82/vx9gcf013yx8jc55mbd8g2340000gn/T/nix-binary-tarball-unpack.XXXXXXXXXX.62XJEAzf/unpack/nix-2.13.3-aarch64-darwin/install-multi-user: line 347:  6687 Killed: 9               sudo "$@"


```

</details>

Then examined state of the launchctl nix-daemon; its failing to start with:

## Output

<details><summary>Output</summary>

```log
Service could not initialize: posix_spawn(/bin/sh), error 0xd - Permission denied
```
## Priorities

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by abathur** [comment]
Yes. Unfortunately the installer is not currently idempotent and will only work from a fairly clean state.

For anyone else landing here via search, you'll have to follow the uninstall instructions before reinstalling it: https://nixos.org/manual/nix/stable/installation/installing-binary.html#macos

For future reference: If you are reinstalling because Nix was missing from your PATH after a macOS update, you don't have to reinstall to fix this. The macOS update is overwriting the shell hook, but you can just replace it. See #3616 for more.You'll have to follow the uninstall instructions before reinstalling it: https://nixos.org/manual/nix/stable/installation/installing-binary.html#macos
