### ISSUE TITLE
Can't compile development checkout: syntax error near unexpected token `OPENSSL,'

### ISSUE THREAD

**Issue by timbertson** [NixOS/nix#823]
I'm trying to make modifications to nix-prefetch-url, and I'm having no luck compiling nix locally.

`./dev-shell` sounds like what I want. Since there's a `configure.ac`, I assume I need to run `autoconf`. After that I run `./configure $configureFlags`, which fails with:

```
( ... )
checking whether Perl is recent enough... yes
checking for the Perl installation prefix... ${exec_prefix}/lib/perl5/site_perl/5.20.3/x86_64-linux-thread-multi
checking for cat... /nix/store/9s9r019176g7cvn2nvcw41gsp862y6b4-coreutils-8.24/bin/cat
checking for tr... /nix/store/9s9r019176g7cvn2nvcw41gsp862y6b4-coreutils-8.24/bin/tr
checking for openssl... /nix/store/ik8d2g12y2hj5y4k32ca3cgm53v3h0va-openssl-1.0.1q/bin/openssl
./configure: line 6130: syntax error near unexpected token `OPENSSL,'
./configure: line 6130: `PKG_CHECK_MODULES(OPENSSL, libcrypto, CXXFLAGS="$OPENSSL_CFLAGS $CXXFLAGS")'
```

Given that this is `nix`, I was hoping that my working nixpkgs installation would be enough to get me set up with the appropriate dev dependencies.

**Comment by zimbatm** [comment]
Getting the same issue on nixos-unstable. It looks like it's not able to find openssl even if openssl and pkgconfig are in the path.

https://github.com/s3fs-fuse/s3fs-fuse/issues/81

**Comment by fkz** [comment]
Was there :smile:
The following works for me:

    $ ./dev-shell
    [nix-shell]$ ./bootstrap.sh
    [nix-shell]$ configurePhase
    [nix-shell]$ make
    [nix-shell]$ make install

**Comment by timbertson** [comment]
Thanks @fkz, that works. Is it worth adding some documentation about this? Sounds like both myself and @zimbatm were unable to find the right invocation to build locally, so this is likely to trip up others too.

**Comment by Unip0rn** [comment]
I also ran into this when building on Armbian, so for the source-tar-ball I suggest adding something like "If ./configure fails due to some missing dependencies, but you are sure to have them installed, try re-running ./bootstrap.sh. It is known to help sometimes."
However when trying to build from the repo (commit 18ecd087ae772885fb223e1771b93a6b0eee1a31) it fails complaining about a missing libeditline, which is installed pretty sure. Also when building from the tar-ball it works just fine on the same installation.
