### ISSUE TITLE
nix-shell interpreter is started interactively

### ISSUE THREAD

**Issue by wmertens** [NixOS/nix#848]
[Nix v1.11.2]

When I write scripts with this header:

```
#!/usr/bin/env nix-shell
#! nix-shell -i bash -p bash
```

My Bash will run my `.bashrc` in interactive mode, meaning the test `[ -t 0 ]` succeeds, meaning stdin is a tty.

I am not sure what is happening, but normally `.bashrc` should not be read when running a script. I would expect interpreter mode to act as if the interpreter was run directly…

**Comment by zimbatm** [comment]
This is also an issue with stack which invoked nix-shell. I've definitely had cases where it weirdly drops me into a shell. Also running `nix-shell --pure` often causes problems because the tools in the ~/.bashrc are not available.

I think that bash should be invoked with `--norc` and `--noprofile` in those cases.

**Comment by armijnhemel** [comment]
Same as #824 ?

**Comment by Shados** [comment]
This is also an issue when using nix-shell-shebang scripts with a non-bash interpreter specified in `-i`, as it appears nix-shell always starts an interactive bash shell when building its environment before launching the specified interpreter with the script. This is a pretty large source of _unexpected_ impurity, at least to me.

**Comment by edolstra** [comment]
This already appears to be fixed on master.
