### ISSUE TITLE
[NixOS feature] Better shebang shell script compatability

### ISSUE THREAD

**Issue by dnkmmr69420** [NixOS/nix#8558]
So right now there is only `/bin/sh` and `/usr/bin/env`. It should be done in a different way. `/bin` should be symlinked to `/usr/bin` first of all and there should also be a symlink to bash and possibly a symlink to python if python is installed.
**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by endgame** [comment]
Your issue is probably a better fit for the [nixos issue tracker](https://github.com/nixos/nixos/issues), since this is not a problem with Nix itself.
Did you know that you can use `nix-shell` as a `#!` interpreter? https://nixos.org/manual/nix/stable/command-ref/nix-shell.html#use-as-a--interpreter

**Comment by dnkmmr69420** [comment]
the repo you linked to has been archived. there are some scripts that use `#!/bin/bash` and even `#!/usr/bin/sh` it should be there for better compatability

**Comment by endgame** [comment]
My mistake, the nixos repo is not relevant any more. Try the [nixpkgs issue tracker](https://github.com/nixos/nixpkgs/issues).

**Comment by cole-h** [comment]
Closing, as this is more appropriate for https://github.com/NixOS/nixpkgs/.
