### ISSUE TITLE
#! /usr/bin/env bash for all scripts that rely on it

### ISSUE THREAD

**Issue by sonjiku** [NixOS/nix#8644]
Hey.

I like to use dash as my posix shell for shell scripts, by simlinking it to /usr/bin/sh. I've heard that nix uses a lot of shell scripts that rely on bash, which could be affected by a change like that. Could you verify if that's true? If it is, could you perhaps correct the shebangs to reflect the reliance on bash instead of just any shell?

**Comment by abathur** [comment]
> I've heard that nix uses a lot of shell scripts that rely on bash, which could be affected by a change like that. Could you verify if that's true? 

The Nix ecosystem does indeed use a lot of bash. 

>  If it is, could you perhaps correct the shebangs to reflect the reliance on bash instead of just any shell?

Why do you believe there's anything to correct?

(i suspect you have some mistake impression about how nix works. It does not really care about your system executables.)

**Comment by abathur** [comment]
Ah. This is a NixOS question.

This repository is for the Nix package manager itself, and (speaking generally) Nix itself doesn't have this problem. The code for NixOS is in https://github.com/nixos/nixpkgs, so that'll be the appropriate place to follow up on this.

I'm not personally familiar with the details here, but it sounds like whatever you've heard is probably inspired by the description of the option for setting it:

https://github.com/NixOS/nixpkgs/blob/0c3a28f08f207a0b074d5ecbbed21b5b045f690f/nixos/modules/config/shells-environment.nix#L129-L143

You also aren't the only one; I already see a similar issue open in nixpkgs:
- https://github.com/nixos/nixpkgs/issues/74627

I do see some public configs where people use this option (ttps://github.com/search?q=language%3Anix+%2Fenvironment.binsh.*pkgs.dash%2F&type=code), so I guess that's a sign that replacing it works well enough for some people.

The "warning" was added along with the option to make this configurable 10 years ago, so it's possible that other people replacing this with dash have contributed fixes to any issues they personally run into. Nixpkgs should be receptive to fixes if you try this and run into any dash syntax error messages (where a fix might either be avoiding the bashism causing trouble, or making sure it specifies bash).

I'm closing this since it's out of scope here, but you can still reply here if you need me to clarify anything above :)
