### ISSUE TITLE
nix key convert-secret-to-public is broken in 2.17

### ISSUE THREAD

**Issue by arianvp** [NixOS/nix#8844]
**Describe the bug**

It doesn't print anything

**Steps To Reproduce**

```
nix key generate-secret --key-name a > a.key
cat a.key | nix key convert-secret-to-public
```

**Expected behavior**

Public key shows. But it doesn't show any output.

Also noticed that ` nix key generate-secret  --key-name a` when not directed to a file also doesn't generate output. might be related

**`nix-env --version` output**

**Additional context**

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by tomberek** [comment]
Using `write(2)` vs `std::cout <<` means we lost a fsync or similar behavior. Simple stuff like adding a `close` doesn't work. But it seems that switching from `writeFull` to `writeLine` does!

```
diff --git a/src/nix/sigs.cc b/src/nix/sigs.cc
index 45cd2e1a6..dbe79920b 100644
--- a/src/nix/sigs.cc
+++ b/src/nix/sigs.cc
@@ -173,7 +173,7 @@ struct CmdKeyGenerateSecret : Command
         if (!keyName)
             throw UsageError("required argument '--key-name' is missing");

-        writeFull(STDOUT_FILENO, SecretKey::generate(*keyName).to_string());
+        writeLine(STDOUT_FILENO, SecretKey::generate(*keyName).to_string());
     }
 };

@@ -194,7 +194,7 @@ struct CmdKeyConvertSecretToPublic : Command
     void run() override
     {
         SecretKey secretKey(drainFD(STDIN_FILENO));
-        writeFull(STDOUT_FILENO, secretKey.toPublicKey().to_string());
+        writeLine(STDOUT_FILENO, secretKey.toPublicKey().to_string());
     }
 };
```

**Comment by tomberek** [comment]
It seems that the data is being output, but is not visible due to some terminals interpreting RETURN, newline, carriage return, differently. Check with strace to see the "write" being made. I encountered this with a terminal inside of tmux inside of gotty, so it is very likely some odd terminal interaction took place.

The question is if we should just append a newline to the data and make this easier?

**Comment by tomberek** [comment]
try setting your terminal with
```
stty onlcr
```

**Comment by duijf** [comment]
I can reproduce this bug. `stty onlcr` does not work unfortunately.

**Comment by ldicarlo** [comment]
Just to be clear for future people here, the "workaround" here is to run the command prefixed by `strace` and read last lines of the output.

**Comment by tomberek** [comment]
> Just to be clear for future people here, the "workaround" here is to run the command prefixed by `strace` and read last lines of the output.

No, the "strace" comment was only to help us understand what was happening. That is not a good workaround.

If you look at the linked PR, part of the problem is the initialization of the progress bar, removing that from the codepath fixes the problem. The correct data is actually being output to stdout either way, it's just that right now you cannot see it because the initialization of the progress bar clears the current line from the visible terminal. If you just need to pipe the output into a file, that works as expected at the moment. 

```
cat ./private | nix key convert-secret-to-public > ./public
```

If you are looking for a workaround to make the public portion visible, you can do something like this:

```
cat ./private | nix key convert-secret-to-public | cat
```
