### ISSUE TITLE
nix develop fails when lockfile is ignored

### ISSUE THREAD

**Issue by viraptor** [NixOS/nix#8854]
**Describe the bug**

When I work with a repo where the flake lockfile is ignored, I get:
```
$ nix develop --show-trace          
warning: Git tree '/some/path' is dirty
warning: updating lock file '/some/path/flake.lock':
• Added input 'flake-utils':
...
evaluating derivation 'git+file:///some/path#devShells.aarch64-darwin.default'The following paths are ignored by one of your .gitignore files:
flake.lock
error:
       … while updating the lock file of flake 'git+file:///some/path'

       error: program 'git' failed with exit code 1
```

**Steps To Reproduce**

Use flake with `flake.lock` in gitignore file.

**Expected behavior**

Either:
- `nix develop` doesn't try to commit the changes for ignored files, or
- there's an option for "write updates, but don't commit"

**`nix-env --version` output**

`nix-env (Nix) 2.13.3`

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by viraptor** [comment]
Actually, I just realised it's a weird one, because I'm not specifying `--commit-lock-file`, so I'm not sure why git is called in the first place...

**Comment by thufschmitt** [comment]
Regardless of `--commit-lock-file`, Nix will stage the `flake.lock` (as it would be ignored otherwise because Nix doesn't take into account the files that git doesn't know about when working in Git repos).

Possibly, Nix could ignore the `.gitignore` for that (which would be OK-ish since it only stages an empty file iirc, not the actual flake.lock). Or alternatively you can use `nix develop path://$PWD` to bypass the Git integration altogether (but that can be costly as it will copy the entire directory content to the store)

**Comment by 9999years** [comment]
Ran into this today! You can _kinda_ work around it with `--no-write-lock-file`.

**Comment by 9999years** [comment]
From @edolstra on #9284:
> This is intended behaviour. We used to pass --force but we removed that in https://github.com/NixOS/nix/pull/6917 due to https://github.com/NixOS/nix/issues/5810.

I'm not sure how to fix this...
