### ISSUE TITLE
error updating nixos

### ISSUE THREAD

**Issue by Paul75** [NixOS/nix#9118]
**Describe the bug**

when do `[root@nixos:/etc/nixos]# nixos-rebuild switch`

**Steps To Reproduce**

1. # nixos-rebuild switch
2. See error
```
[root@nixos:/etc/nixos]# nixos-rebuild switch
building Nix...
building the system configuration...
error:
       … while calling the 'head' builtin

         at /nix/store/gbmn7sq29r2d9249dbkk5yg0fnqlhpsg-nixos/nixos/lib/attrsets.nix:820:11:

          819|         || pred here (elemAt values 1) (head values) then
          820|           head values
             |           ^
          821|         else

       … while evaluating the attribute 'value'

         at /nix/store/gbmn7sq29r2d9249dbkk5yg0fnqlhpsg-nixos/nixos/lib/modules.nix:807:9:

          806|     in warnDeprecation opt //
          807|       { value = builtins.addErrorContext "while evaluating the option `${showOption loc}':" value;
             |         ^
          808|         inherit (res.defsFinal') highestPrio;

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: Teams app for Linux has been removed as it is unmaintained by upstream. (2023-09-29)
```

**Expected behavior**

**`nix-env --version` output**
`nix-env (Nix) 2.17.0`

**Additional context**

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by cole-h** [comment]
Hi! Issues with NixOS should be filed against the [Nixpkgs repository](https://github.com/NixOS/nixpkgs) (which contains NixOS) instead of this Nix repository (which only contains the `nix` tool).

Additionally, your issue appears to be that you're using a package that has been dropped from Nixpkgs (Teams for Linux). If you remove that from your NixOS configuration, you may find it working again. If that doesn't work, please check to see if someone has already filed an issue against the [Nixpkgs repository](https://github.com/NixOS/nixpkgs), and if not, file a new issue :)
