### ISSUE TITLE
Turn off Git smugding in `fetchGit`

### ISSUE THREAD

**Issue by fricklerhandwerk** [NixOS/nix#9327]
**Describe the bug**

As discussed with @nixos/nix-team:

While it's been around for a long time, smudging being enabled in `fetchGit` can be considered a bug.

More detailed discussion: https://github.com/NixOS/nix/pull/4635#issue-830999404

**Steps To Reproduce**

```console
$ nix build git+ssh://git@github.com/tomberek/export-magic -L
text> /nix/store/8fdx2h960yf292czd4ik2f6fza63wlqh-.version
text> HEAD -> main
text>  (HEAD -> main)
text> f0fe26485056d92e78d84de3daf14a8875548783
text> Tue, 21 Feb 2023 19:51:28 -0500
text> 2023-02-21 19:51:28 -0500
text> 2023-02-21T19:51:28-05:00
text> HEAD -> main
text>  (HEAD -> main)
text> f0fe26485056d92e78d84de3daf14a8875548783
text> Tue, 21 Feb 2023 19:51:28 -0500
text> 2023-02-21 19:51:28 -0500
text> 2023-02-21T19:51:28-05:00
```

**Expected behavior**

It should output the unchanged contents of https://github.com/tomberek/export-magic

**Proposal**

- resolve commit hashes to tree hashes, this will incur a ~one-time overhead to fetch metadata; a trade-off towards correctness
    - GitHub tarballs are pre-smudged, but fetching those is an optimisation anyway
    - the new semantics will be much simpler

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by roberth** [comment]
We've recently used the term smudging to cover all behaviors that make file system objects diverge from the simple, well defined, and therefore well reproducible git tree data model.

The example in this issue is technically about **export-ignore** and not the git **smudge filter** feature. **Submodules** should also be considered, as they are a layer on top of git trees.

A more extensive explanation and discussion centered around the smudge filter feature can be found here https://github.com/NixOS/nix/pull/4635#issue-830999404

Essentially what we're trying to achieve is NAR hash-levels of reproducibility by other means, specifically a **definitive** translation from git objects to Nix file system objects.

Definitive is the keyword here. We won't have the luxury of changing this translation after stabilization, except for the addition of parameters that tweak the translation in ways such that their default value is aforementioned "definitive" behavior.

**Comment by roberth** [comment]
> It should output the unchanged contents of https://github.com/tomberek/export-magic/tarball/master

Not sure what you mean by unchanged contents. That URL produces contents where export-ignore has been applied.

**Comment by fricklerhandwerk** [comment]
> > It should output the unchanged contents of https://github.com/tomberek/export-magic/tarball/master
> 
> Not sure what you mean by unchanged contents. That URL produces contents where export-ignore has been applied.

Typo, fixed.

**Comment by fricklerhandwerk** [comment]
> Essentially what we're trying to achieve is NAR hash-levels of reproducibility by other means, specifically a **definitive** translation from git objects to Nix file system objects.

Should we open a tracking issue from your comment then?

**Comment by thufschmitt** [comment]
This should hopefully be fixed by #9240

**Comment by roberth** [comment]
- See https://github.com/NixOS/nix/issues/5313
  - [start of recent messages](https://github.com/NixOS/nix/issues/5313#issuecomment-1780650439)

**Comment by roberth** [comment]
Duplicate
