### ISSUE TITLE
All experimental feature flags should have a tracking issue, shown in docs, and enforced mechanically

### ISSUE THREAD

**Issue by Ericson2314** [NixOS/nix#9345]
## Problem

We have a number of experimental features in flight, which I think is fine. However, that means we should be extra diligent about keeping track of them all. Users/developers/etc. should clearly know what is the main place we keep track of each experimental feature.

## Proposal

In `ExperimentalFeatureDetails` in `src/libutil/experimental-features.cc` we write down an issue number, and render a link to the issue as part of the docs for that experimental feature.

## Priorities

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by Ericson2314** [comment]
2023-11-17 Nix team meeting notes:

Seems reasonable.

- @edolstra: What does “enforce mechanically” mean?
    - Just have the link as part of the `ExperimentalFeature` data structure

Idea approved.

**Comment by thufschmitt** [comment]
On that topic: I've been reworking the old [implementation board](https://github.com/orgs/NixOS/projects/49/views/2), and I think it can be utterly useful for tracking experimental features if we properly map them to milestones (see [this very incomplete one](https://github.com/orgs/NixOS/projects/49/views/2?sliceBy%5Bvalue%5D=CLI+Stabilisation) for instance). So rather than having tracking issues it could be great to use a milestone per xp feature
