### ISSUE TITLE
Versions of Nix >= 2.4 disappear from nixpkgs frequently

### ISSUE THREAD

**Issue by amjoseph-nixpkgs** [NixOS/nix#9419]
In

- https://github.com/NixOS/nix/issues/9412

@RaitoBezarius asked what regressions still exist, relative to Nix 2.3.16.  I would like to add this one: `nix_2_3` has been continuously available in nixpkgs for years, whereas all the other versions seem to appear and disappear at random intervals.

This unstable availability can be considered a regression relative to the 2.3.x series.

**Comment by roberth** [comment]
Backporting to that many versions is not feasible for us, and we don't think it would add much value to do so.
See the manual for [what we support](https://nixos.org/manual/nix/stable/release-notes/release-notes.html?highlight=latest%20NixOS#nix-release-notes) - basically the range down to the NixOS release.
We make an exception for 2.3 because some users are still stuck on that release. I suppose when more of #9412 gets done, they will be able to upgrade too.

Technically this is a Nixpkgs issue, but I don't think Nixpkgs maintainers want to maintain their own patch sets. If I'm wrong about that I'll be happy to reopen this to discuss how we can support such effort in this repo instead.

**Comment by Ericson2314** [comment]
Yeah I think the 2.3 -> 2.4 did not feel like a minor version release, because there was much unintentional breakage, but since then we've been getting more stable, so there should be little reason to keep around a 2.5 or whatever.

**Comment by amjoseph-nixpkgs** [comment]
> Technically this is a Nixpkgs issue

Fair enough.

- https://github.com/NixOS/nixpkgs/issues/271321
