### ISSUE TITLE
Allow 'double dash' syntax for nix-shell command

### ISSUE THREAD

**Issue by expipiplus1** [NixOS/nix#945]
It would be nice to be able to do something like this:

`nix-shell -p my-package -- exe using -my --package` which is equivalent to `nix-shell -p my-package --command 'exe using -my --package'`

There plenty of precedence for this in other packages, and even elsewhere in the nix ecosystem: `nixops ssh machineName -- some command -with --flags`.

Of course this might not make sense to do now while the tools are being rewritten in C++.

Originally posted as NixOs/nixpkgs#16364

**Comment by chris-martin** [comment]
I'm currently trying to write a wrapper script that passes args into nix-shell, and the requirement of passing the command as a string rather than as a list of args is a headache. It seems very unusual to me that nix-shell wants a command string to parse on its own; I can't think of any other program that works like that.

**Comment by Ericson2314** [comment]
You're not the first to want something like this https://github.com/NixOS/nix/issues/534 :)

**Comment by domenkozar** [comment]
Closing as we don't want to keep a duplicate then. Comment on #534
