### ISSUE TITLE
Broken `NIX_PATH` tracking issue

### ISSUE THREAD

**Issue by roberth** [NixOS/nix#9574]
**Describe the bug**

`NIX_PATH` environment variable does not work when `nix.conf` has a `nix-path` setting.
This is highly unexpected and not intentional.
Multiple issues and PRs exist, but solving this problem has proven difficult within the established abstractions for settings handling.

**Issues**

- #8784
- #8890

**PRs**

- #7871 
- #8902

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by colonelpanic8** [comment]
@roberth @fricklerhandwerk I'm happy to take another swing at this one.

Seems like https://github.com/NixOS/nix/pull/9066/files should probably be used as a starting point for testing.

w.r.t. your comment here https://github.com/NixOS/nix/pull/8902#issuecomment-1724260762

it seems like you are saying that there is probably some issue with what I did in this pr, w.r.t. the interaction between NIX_PATH and restrict-eval, but its not quite clear to me what exactly the issue is, and whether you and @thufschmitt ever did sit down and figure out a resolution or not. Just want to make sure that I'm not missing any details that you guys worked out or decided on before I spend more time on this.

Happy to jump on a call or discuss over text chat or something as well.

Thanks!

**Comment by colonelpanic8** [comment]
Would also be happy to use https://github.com/NixOS/nix/pull/7871 as a starting point if we feel like that is a better route.

I don't have a super strong recollection of what I even did in my PR, but I do vaguely recall that it did have the advantage of having a more "correct" version of the behavior w.r.t. precedence of the command line arguments.

**Comment by fricklerhandwerk** [comment]
@colonelpanic8 thanks a lot, I appreciate your support! Feel free to join the [maintainer meetings](https://calendar.google.com/calendar/event?eid=NTM1MG1wNGJnOGpmOTZhYms3bTB1bnY5cWxfMjAyMjExMjFUMTIwMDAwWiBiOW81MmZvYnFqYWs4b3E4bGZraGczdDBxZ0Bn) if you'd like to talk.

We did sit down, which resulted in the top post of https://github.com/NixOS/nix/pull/9066 that describes the expected behavior, which is currently violated. It should be tested exhaustively and then fixed. [We discussed last time](https://discourse.nixos.org/t/2024-04-24-nix-team-meeting-minutes-141/44083#h-2024-04-22-nix-team-meeting-minutes-141-4) (and the details aren't written down because there were too many) that the test setup as it is stands in the way to do this cleanly, and we'd like to first see how to approach that.

**Comment by colonelpanic8** [comment]
@fricklerhandwerk oh, wait so it seems like you just happened to pick this up again recently? I had assumed that since so much time had passed since the creation of #9066 that no one was actively working on this and that there may not even be any plans to fix the issue.

I'm definitely eager to help out here (this issue is kind of a major annoyance for me) but if you are already actively working on fixing the issue (and it sounds like maybe you have plans to pair on it with eelco), I wonder if I might just be stepping on toes by involving myself.

I'd love to hear your honest opinion on whether my involvement would be helpful at this stage. I'm definitely happy to attend the meeting, and work on any parts of this (even if they are tedious as with the testing).

**Comment by SuperSandro2000** [comment]
I have the suspicion that the search.nixos.org import broke because of this https://github.com/NixOS/nixos-search/actions/runs/8851738555/job/24308951178

Discussion in matrix https://matrix.to/#/!RROtHmAaQIkiJzJZZE:nixos.org/$CW01HdjRSMSyxXZlVw5cHassVIidQBjYDN8sAqDcR54?via=nixos.org&via=matrix.org&via=nixos.dev

**Comment by fricklerhandwerk** [comment]
> already actively working on fixing the issue

This would be an exaggeration. It's on my mind and I dabbled at it, but I didn't make progress. Talking it through and walking through the code with someone would definitely help with that. But don't rely on me. Feel free to make your own investigations and discuss them here or as pull requests.

**Comment by mobsenpai** [comment]
This happened to me as well when trying to set nix shell to use flake inputs nixpkgs version. using [Misterio/nix-starter-configs](https://github.com/Misterio77/nix-starter-configs/blob/main/minimal/nixos/configuration.nix). Why isn't it default to use whatever is defined in flake.nix file?

**Comment by piegamesde** [comment]
While this is definitely a Nix bug, I'd argue that the NixOS module is broken as well: The `nix.nixPath` option sets `environment.sessionVariables.NIX_PATH` instead of `settings.nix-path`, which is surprising.

However, even with both of these fixed, I'd argue that the general behavior and interaction between these two would be suboptimal and surprising: If one configures the Nix path through `nix.conf` and then a script goes along and wants to append to `NIX_PATH`, it will effectively override the existing path instead of appending, which is clearly not intended. (The alternative of appending/merging both is equally problematic for other reasons. Maybe the two simply should not coexist …)
