### ISSUE TITLE
error "value is a list while a set was expected" is too vague

### ISSUE THREAD

**Issue by domenkozar** [NixOS/nix#963]
It's extremely hard to debug such errors. It would help to print out the value of the list to see what's there that shouldn't be.

EDIT: donate to https://opencollective.com/nix-errors-enhancement to help improve --debugger

**Comment by bjornfor** [comment]
Oh, seems I was here already with a "thumbs up". Just hit this again. Isn't this really easy to fix? CC @edolstra.

**Comment by mkg20001** [comment]
Any updates?

**Comment by mkg20001** [comment]
Hit this issue again.

**Comment by trusktr** [comment]
Newb here, I'm gettin this error when running `nix-shell -E '(import ./default.nix).nodejs."13.6.0"'`, and the files are:

**./default.nix**

```nix
{pkgs ? import <nixpkgs> {}}: {
  nodejs = (import ./nodejs { inherit pkgs; })."13.6.0";
}
```

**./nodejs/default.nix**

```nix
{pkgs ? import <nixpkgs> {}}: {
  "13.6.0" = pkgs.callPackage ./nodejs.nix {
    inherit pkgs;
    version = "13.6.0";
    sha256 = "00f01315a867da16d1638f7a02966c608e344ac6c5b7d04d1fdae3138fa9d798";
  };
}
```

**./nodejs/nodejs.nix**

```nix
{ pkgs ? import <nixpkgs> {}, version, sha256 }:
  let
    inherit (pkgs) stdenv autoPatchelfHook platforms fetchurl;
    inherit (stdenv) mkDerivation lib;  
  in mkDerivation {
    inherit version;  
    name = "nodejs-${version}";  
    src = fetchurl {
      url = "https://nodejs.org/dist/v${version}/node-v${version}-linux-x64.tar.xz";
      inherit sha256;
    };
    nativeBuildInputs = with pkgs; [autoPatchelfHook];
    buildInputs = with pkgs; [glib];
    installPhase = ''
      mkdir -p $out
      cp -R ./ $out/
    '';  
    meta = {
      description = "Event-driven I/O framework for the V8 JavaScript engine";
      homepage = https://nodejs.org;
      license = lib.licenses.mit;
      platforms = lib.platforms.linux;
    };
  }
```

**Comment by deliciouslytyped** [comment]
This issue is generally not the best place to get help with specific nixpkgs related errors. This issue tracker if for the evaluator for the Nix language.
You could try on the discourse at https://discourse.nixos.org/ , or the #nixos channel on freenode at https://webchat.freenode.net/  , or perhaps on the nixpkgs issue tracker https://github.com/NixOS/nixpkgs/issues . Preferably one of the first two IMHO.
That said, next time you have a problem it would help if you post a traceback. Which if fitting, because we have no idea where to even look. :P

**Comment by domenkozar** [comment]
cc @bburdette this one should be high priority for phase 3 of https://opencollective.com/nix-errors-enhancement

**Comment by bburdette** [comment]
I think this one is going to be helped a lot with the new format error messages, where the line of code is displayed.  The current error is something like this (using trusktr's example, above):

```
bburdette@BB-5520:~/code/nix-error-project/963$ nix-shell -E '(import ./default.nix).nodejs."13.6.0"'
error: value is a function while a set was expected, at (string):1:1
```

With the current version of nix, we get to set the context of the error: 

```
bburdette@BB-5520:~/code/nix-error-project/963/test-case$ ./opcode-nix-test.sh 
error: value is a function while a set was expected

       at «string»:1:1:

            1| (import ./default.nix).nodejs."13.6.0"
             | ^
```

I think this is helpful because it shows the site of the error, which is in the cmdline argument passed to nix.  The statement that the error was in a 'string' I think is confusing to noobs because maybe my code has a lot of strings?  I don't think the message by itself is very clear that the error is in the cmdline argument.  However, it pretty clear when accompanied by the line of code.  

And it shows the exact expression that's supposed to be a set rather than a list/function/etc.  

It might be helpful to show the value of that expression as well, but I'm not sure its strictly necessary.  

similar (albeit contrived) example of the list error:

```
bburdette@BB-5520:~/code/nix-error-project/963/test-case$ ~/op-code/nix/outputs/out/bin/nix-shell -E '([1 2]).nodejs."13.6.0"'
error: value is a list while a set was expected

       at «string»:1:1:

            1| ([1 2]).nodejs."13.6.0"
             | ^
```

**Comment by bburdette** [comment]
@DavHau if you have an example that doesn't show traces when it should, I'd be interested in seeing it.  The traces are built up during exception handling, and its not impossible that there might be a catch clause someplace that manages to throw away the traces.

**Comment by DavHau** [comment]
> @DavHau if you have an example that doesn't show traces when it should, I'd be interested in seeing it. The traces are built up during exception handling, and its not impossible that there might be a catch clause someplace that manages to throw away the traces.

Sorry, I noticed that I was accidentally using a pre-release version of nix 2.5. After upgrading to nix 2.7, the traces came back.

**Comment by yu-re-ka** [comment]
@bburdette

```
$ git clone https://github.com/yu-re-ka/robotnix
$ git checkout 946af3391337293e860b3803ca9098c4f0b36fa3
$ nix --version
nix (Nix) 2.10.3

$ nix-instantiate release-filtered.nix -A cached --show-trace
error: value is a set while a Boolean was expected

$

**Comment by thufschmitt** [comment]
Closing since https://github.com/NixOS/nix/pull/6204 should have fixed most of these. Don't hesitate to open new issues if you encounter misleading or bad error messages on master.
